### ISSUE TITLE
Addressing Customizations/Configurations

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#1]
Customization is a pretty big topic and this issue just lays it all out (what we extracted so far). Other issues will do further structuring and address the specifics.

**Levels**
We attempt to address customization at increasing level of flexibility at the cost of increasing level of expertise needed. You can gradually customize an instance by:
1. setting configuration values -- least effort, no customization beyond what developers have marked as customizable.
2. installing more modules (and setting their configuration values) -- need (very little) knowledge of command line
3. creating your own modules and installing them -- more effort and expertise, but more flexibility
4. adding code to your instance (do we even want to go there, or just tell people to fork at this point?) -- much more effort and expertise, but even more flexibility
5. forking (you do you!) -- most effort, expertise and maintenance cost for most flexibility

**Customization points**
Obviously this is an open source project, so one could theoretically customize anything by forking (see 5.) and going off. This is not recommended. We want to have clear configuration points that address clear configuration needs.

- `config,py` and `invenio.cfg` are used for tier-1 customizations mostly. `invenio.cfg` is needed/helpful for differing context: local development, production, staging as well as secrets/API keys, while `config.py` is helpful for settings common across contexts and non sensitive values. Using environment variables should be possible too (`invenio-config` does it all!). Configuration files for deployment also fall in this bucket. 
- loaded data. Customization can be achieved by loading + using different controlled vocabularies for otherwise fields (or loading roles for instance). Usually the size of the controlled vocab explains why `config.py` is not used. CLI tool is needed out of the box with some means of letting caller configure how things should be loaded. (tier 2 if user is doing it, tier 1 if provided by choice of profile). Examples: resource types, terms, relation_types
- placing templates / static files in predefined locations. To customize look and layout, custom stylesheets and html templates can be placed in locations where InvenioRDM will pick them up. (tier-4 or so)   
- data model extensions. This should be achieved either through a module containing the extensions or potentially placing the extension file somewhere. Profiles will need to be able to provide these customization.
- dynamic admin controlled customizations. It should be possible to enable / disable features, add / remove db entries from the admin to customize the instance. For instance, role assignation, static page creation, feature toggle.  

**Profiles**
As the person in charge of installing an InvenioRDM instance, I want to select a "profile" that has a set of customizations more appropriate to my domain. Examples are "BioMedical" or "Physics" (better names needed). These profiles are available out of the box and you can create your own as a module (see 3.)

**What can be customized**
- choice of profile
- choice of controlled vocabularies
- layout and look (css and html) - at tier 1. through some configuration values, at tier 3 or 4 to make your own
- roles and permissions
- data model (at high cost to prevent chaos :sweat_smile: )
- static pages like the frontpage
- the "collections" strategy
- deployment configuration
- data backing volumes / hosts
- installed modules
- citation styles
- licenses

**Documentation**
Documentation to explain our approach to configuration should be written. Documentation should be placed at different locations with different audience in mind: in module for developers and on InvenioRDM website for less technical user.

**Comment by ppanero** [comment]
@fenekku should this be discussed here https://github.com/inveniosoftware/rfcs/pull/6 ?

**Comment by fenekku** [comment]
@ppanero yeah that makes sense. I wrote this before we started doing RFCs, so we could port it there.

**Comment by lnielsen** [comment]
I'm closing the ticket as I've made a product roadmap issue to look into easy customization. See https://github.com/inveniosoftware/product-rdm/issues/51
