### ISSUE TITLE
Save Draft (Neuer Eintrag) button text overlap

### ISSUE THREAD

**Issue by mb-wali** [inveniosoftware/invenio-app-rdm#1012]
Package version (if known): v5.0.0

## Describe the bug
**Save draft button text is overlapping with icon button**
## Steps to Reproduce
1. add german language: `I18N_LANGUAGES = [('de', _('German'))]`
2. Select German (Deutsch) language from the dropdown.
3. Go to the New upload (Neuer Eintrag) page.
4. See Screenshot
![german-bug-edit](https://user-images.githubusercontent.com/44528277/126748162-9b200eb5-4315-424e-97a4-21238ad5ab5e.jpg)

**Comment by lnielsen** [comment]
Any ideas for how to fix this? Could it just say ``Speichern`` instead?

**Comment by lnielsen** [comment]
Btw, looks cool that it's possible to switch language 🚀

**Comment by mb-wali** [comment]
> Any ideas for how to fix this? Could it just say `Speichern` instead?

Hi, the easiest and cleanest - would be to change the Button Label alignment from `left` to `center`: somewhere in here: https://github.com/inveniosoftware/react-invenio-deposit/blob/af030775e762c4a2a9b5fc119520860d2fc05846/src/lib/components/SaveButton.js#L40
this means also to change the `Preview Button` so the are the same.
here are some screenshots:
**Before**
![i-1012-before](https://user-images.githubusercontent.com/44528277/127445461-86d5c4c8-fcba-4d41-9026-5fa00d13707a.png)

**After**
![i-1012-en](https://user-images.githubusercontent.com/44528277/127445465-e7a2957f-a77e-4bc5-ac00-7f4e9ce5d10e.png)
![i-1012-de](https://user-images.githubusercontent.com/44528277/127445470-f673d6b4-58f9-497d-b9a6-390687870733.png)

**Comment by chriz-uniba** [comment]
Just as a side-note but maybe related:
invenioRDM-v5 new demo instance. When I change the firefox-window-screen-size to half of my monitor-screen then I get the same issue in English.

![Screenshot_2021-07-29_12-10-24](https://user-images.githubusercontent.com/74763324/127474112-2f6e1b0b-87ad-4ef7-b560-c3746687ff2a.png)

**Comment by mb-wali** [comment]
> Just as a side-note but maybe related:
> invenioRDM-v5 new demo instance. When I change the firefox-window-screen-size to half of my monitor-screen-size then I get the same issue in English.
> 
> ![Screenshot_2021-07-29_12-10-24](https://user-images.githubusercontent.com/74763324/127474112-2f6e1b0b-87ad-4ef7-b560-c3746687ff2a.png)

This PR will solve the button issue also for English in smaller screens - but overall the UI needs work in order to make it mobile friendly.
