### ISSUE TITLE
deposi form: resource type drop down should show more options

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#1016]
The resource type dropdown should show more options (e.g. 15 instead of 6)
![Screenshot 2021-07-23 at 15 52 40](https://user-images.githubusercontent.com/1698163/126792034-b9aae6c5-f1a8-4816-baf8-f3570bdfe048.png)

**Comment by fenekku** [comment]
Huh, I get 8 options (and I didn't do anything except provide custom resource types):

![multiple_resource_types](https://user-images.githubusercontent.com/1932651/126827141-0c1226b5-6fba-4312-9c95-811054f7284b.png)

And to be clear, by scrolling down any resource types can be accessed.
