### ISSUE TITLE
S3 download not working out of the box.

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#1031]
Download of a file is not working

**Comment by ppanero** [comment]
main affecting change: 
- https://github.com/minio/minio/commit/cb0eaeaad86fa6ac30abe585c03ad1fe31b32854#diff-bc8e2150362903d3199e817f2860c59973284093859eb5f9190201e79017e243
- command args needed `--address` and/or `--console-address` to avoid port randomization
