### ISSUE TITLE
landing page: update design for contributors section

### ISSUE THREAD

**Issue by jennur** [inveniosoftware/invenio-app-rdm#1037]
Update according to mockups (ref #988)

- Group all the contributor-types, and display the groups horizontally instead of vertically to avoid too much whitespace, and to make it easier to go through the related content without scrolling and losing context.
- Have only one "show affiliations"-button if they're all showing the same content (it's not necessary to have more than one button for the same thing).
- Move "show-affiliations"-button to the very right, bottom of the section to indicate that the extra content is relevant for all the groups, and that it will show up below.

**Comment by lnielsen** [comment]
Fixed
