### ISSUE TITLE
[ux][landing page] Description, license spacing 

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#1057]
Package version (if known): 6.0

## Describe the bug

The whitespacing between subjects, description and licenses should be more proportioned and deliberate. See:

![image](https://user-images.githubusercontent.com/1932651/128556287-6e049544-5719-4254-8959-fb12ff331e13.png)

## Steps to Reproduce
1. Visit a record landing page filled with description, licenses and subjects

I am sure @jennur can suggest something better :)

**Comment by lnielsen** [comment]
Fixed in landing page redesign
