### ISSUE TITLE
customization: favicon

### ISSUE THREAD

**Issue by tmorrell** [inveniosoftware/invenio-app-rdm#1066]
Package version (if known): v6

## Describe the bug
A favicon placed in /static doesn't get served out

## Steps to Reproduce
1. Copy favicon.ico to /static
2. `invenio-cli assets build`
3. `invenio-cli run`
3. See 404 for /static/favicon.ico

## Expected behavior
Favicon file is served at /static/favicon.ico

## Additional context
The favicon is copied over by invenio-cli, so I'm not sure why there is a different behavior between the favicon and the images in the /static/images directory.

**Comment by chriz-uniba** [comment]
- We have customized the favicon.ico within the app-rdm-cookiecutter template and it works well.
- I also see it here: https://repository.tugraz.at/ adjusted via a theming package (https://github.com/tu-graz-library/invenio-theme-tugraz/blob/master/invenio_theme_tugraz/static/favicon.ico).
- I remember that there was some browser cache issues and maybe a 'rebuild' assets issues. Starting from a fresh instance, putting the icon there, then build the project and taking a look in a fresh browser does work for us.
- Can you confirm that?

**Comment by lnielsen** [comment]
Closing in favour of #1126 to keep it tracked in a single issue.
