### ISSUE TITLE
Feature request: Extensible side bar

### ISSUE THREAD

**Issue by alexdutton** [inveniosoftware/invenio-app-rdm#1083]
## Is your feature request related to a problem? Please describe.

For Invenio-SWH we would like to be able to provide a link to the external SWH record for an item. At the moment the side_bar.html template contains a fixed set of items.

## Describe the solution you'd like

Some way to register or configure side bar components, so that invenio-swh and others can add a section to expose custom metadata,

## Describe alternatives you've considered

We can't override the template without it becoming brittle.

It's possible that there should be a generic "the thing this record describes, described elsewhere" section that invenio-swh should be using. Another approach might be to have invenio-swh (somehow) add the external URL as an "is identical to" related work, but there's an issue there around ownership of the information (i.e. it's information owned by the SWH integration, but the record owner can edit it).

**Comment by lnielsen** [comment]
Superseded by #1186
