### ISSUE TITLE
UI upload files view 

### ISSUE THREAD

**Issue by cfgamboa** [inveniosoftware/invenio-app-rdm#1089]
Package version (if known): RDM 6.2

## Describe the bug
Files can not be uploaded using the UI upload form. Using the REST API the files can be uploaded.
Records can not be published. Publish button is enabled, can be clicked but it does not publish the record.

## Steps to Reproduce
The system is Red Hat Enterprise Linux Server release 7.9 (Maipo)
I am using python3.6.
The installation follows the local installation, there is an [issue](https://github.com/inveniosoftware/invenio-app-rdm/issues/1088) where the environment and installation is shown

**Comment by fenekku** [comment]
@cfgamboa Can you paste the console messages you get when performing a UI upload? i.e. the browser's console tab will probably list some things and having a look at them might elucidate this.

**Comment by cfgamboa** [comment]
Ok, I found the culprit of this behavior, the 
```
SITE_UI_URL
and
SITE_API_URL
```
Need to use the actual user enable URL. IF set to the local hostname the UI deposit form does not work as mentioned on this  issue.
