### ISSUE TITLE
Passing an unsupported organization identifier shows a misleading error

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#1109]
*From librarians testing the system.*

Package version (if known): 6.0

## Describe the bug
Passing an unsupported organization identifier results in "Missing data for required field" because the scheme is missing, instead of a message indicating that the Name Identifiers is unsupported.

## Steps to Reproduce
1. Go to '/uploads/new'
2. Fill out a creator as:
![creator_error](https://user-images.githubusercontent.com/1932651/138144282-665be230-9a07-47df-995e-6443ddc3219b.png)

3. Save
4. See error saying there is missing data but the _incorrect_ data is there.

**Top**
![image](https://user-images.githubusercontent.com/1932651/138144394-3273c5ee-0de9-4b7d-b765-9138677929c7.png)

**in form**
![image](https://user-images.githubusercontent.com/1932651/138144459-fddcbced-2acf-49ae-a733-2ed5b208ad21.png)

**in modal**
![image](https://user-images.githubusercontent.com/1932651/138144885-df61a9ed-c71e-4d97-8137-00ba0cc8fb76.png)

## Expected behavior
A more explicit error message like: "Unsupported scheme." or some such.

**Comment by dfdan** [comment]
We've also hit this, seems to occur with both 'affiliations' and 'name identifiers'
