### ISSUE TITLE
Making a new search doesn't clear the previous search's facets

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#1114]
Package version (if known): 6.0

## Describe the bug
Making a search with some facets selected, and then making a new search by filling the search box and pressing enter, doesn't clear the previously selected facets. This leads to a strange "No results" page that does have results as indicated by the facets. 

## Steps to Reproduce
1. Go to 'https://127.0.0.1:5000/search'
2. Click on facets that are not included in next search
3. Fill the searchbox with a new query
4. See error: "No results" but clearly there are results on the facets from sidebar.

## Expected behavior
Entering a new search should reset the facets.

## Screenshots (if applicable)

1st search with facets:

![image](https://user-images.githubusercontent.com/1932651/139116394-eaf9bed9-6a27-411a-b9c8-2d954971dd27.png)

2nd search 

![image](https://user-images.githubusercontent.com/1932651/139116474-ace7d259-ba58-442c-8044-aa1ca8a248c5.png)

## Additional context
Unless the user is savvy enough to realize that the URL containes the same filtering as before, this result is very confusing.

**Comment by rekt-hard** [comment]
After discussion with @lnielsen, solving this issue in the backend will lead to quite some work. The goal was to keep the facets when changing the query.

The approaches were to
- define default values for elasticsearch aggregations (not possible at the moment)
- apply the `post_filter` only, if the value is present in the aggregations (not possible to access aggregations in `post_filter`).

Another approach could be to apply an interpreter to the search result (as being done for the search) and extend the aggregation buckets with the facets values, if the bucket does not exist. This would lead to having to fetch the extra facets.

For now, a quick fix is to reset the facets in the frontend on a new query.
