### ISSUE TITLE
Background uploader 

### ISSUE THREAD

**Issue by Herrner** [inveniosoftware/invenio-app-rdm#112]
Provide a background upload mechanism that 
-  doesn't rely on lots of http requests for 
-  uploading large numbers of (potentially large) files in parallel 
-  from diverse storage systems (s3 and other cloud storage, sftp, nfs, ...)  

There's something usable from HZDR already:
https://www.hzdr.de/db/!Publications?pNid=head&pSelMenu=0&pSelTitle=27057
And we have a migration task developed by @egabancho working on our zenodo-clone that does something like that in a well defined scenario.

**Comment by lnielsen** [comment]
Tracked on the product board in https://github.com/inveniosoftware/product-rdm/issues/67  https://github.com/inveniosoftware/product-rdm/issues/60 https://github.com/inveniosoftware/product-rdm/issues/59
