### ISSUE TITLE
Deposit page ORCID icon is oversized

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#1144]
Package version (if known): v7

## Describe the bug
When filling out the deposit page, entering an ORCID identifier and saving the draft, the ORCID icon shows up oversized:

![image](https://user-images.githubusercontent.com/1932651/145578471-2929db2c-067d-4c68-85fc-cb845131e754.png)
(this was achieved on the CERN demo site on 2021-12-10) 

## Steps to Reproduce
1. Go to '/uploads/new'
2. Fill out creators with an ORCID id (the id is valid)
3. Click save draft (other fields were filled correctly)

## Expected behavior

A normal size ORCID id.

I suspect it has to do with some accessibility changes.

**Comment by lhenze** [comment]
Hi, I noticed that but actually thought it was pre-existing. Seems like the classname, "inline-orcid," should be "inline-id-icon." Will have a look.

**Comment by lhenze** [comment]
I am looking here - -
https://github.com/inveniosoftware/react-invenio-deposit/blob/2809aae10495cffb65a8a3a19c14e1030fafc1c6/src/lib/components/Creatibutors/CreatibutorsFieldItem.js#L113
Does that seem like the right bit to update?  
(That image also wants an alt tag btw)

**Comment by fenekku** [comment]
That sounds like the right component. The class name or css might have been changed. Try it out! :)

**Comment by lhenze** [comment]
Hi @fenekku 
PR is here -- 
https://github.com/inveniosoftware/react-invenio-deposit/pull/404
Added the classname "inline-id-icon" which is used elsewhere
(https://github.com/inveniosoftware/invenio-app-rdm/commit/3d2d1702c14c2cde1929dc56c31b8b3870b3b1ed#diff-03c62dcb6d10432401c4c9e596011286cb37d5674577bbb04fa464921d2ee6f0R16)
Hard-coded the height and width to conform to ORCID branding requirements
https://info.orcid.org/brand-guidelines/#Example_HTML
And a wrapper span for flexible styling options and consistency with creatributors elsewhere

**Comment by fenekku** [comment]
Closed by https://github.com/inveniosoftware/react-invenio-deposit/pull/404
