### ISSUE TITLE
ui/styling: button.overrides does not use variables

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#1155]
semantic-ui *button.overrides* does not use `@searchButtonColor` as `background-color`.

Tried applying something like:
```
.search.button {
 background-color: @searchButtonColor;
}
```

but it did not work

**Comment by lnielsen** [comment]
Do you have a bit more information. Which result is expected? what is the fix? which files did you try to put it in? was the documentation wrong somewhere etc. Once you've provided the info, can you remove the "question" label and move to high priority column in QA board. Just want to be sure what it is that has to be fixed.

**Comment by lnielsen** [comment]
Forget what I wrote :D Closing in favour of #1064
