### ISSUE TITLE
i18n - spanish translation support

### ISSUE THREAD

**Issue by aperez900907** [inveniosoftware/invenio-app-rdm#1159]
Spanish translation on the roadmap?

will be possible?

thanks

**Comment by lnielsen** [comment]
Thanks. We have just published a guide on how to help with translation - see https://inveniordm.docs.cern.ch/contribute/translators-guide/

If you'd like to help out, jump on #rdm-translations in Discord (see link in guide above) and coordinate with @mb-wali on how to get started.

Thanks a lot :-)
