### ISSUE TITLE
Define quota with a config variable

### ISSUE THREAD

**Issue by rekt-hard** [inveniosoftware/invenio-app-rdm#1160]
It would be a great addition to be able to set upload quotas. This could be done on a per record, per person, per role, per community basis or other configuration possibility.

A few examples:
- a new/default user could have a predefined allowed quota of 10Gb per record
- a researcher (role) could have a quota of 100Gb
- a certain community could set it's quota to 50Gb
- for a one time thing, the quota for a certain record could be set to 100Gb

There are probably other configuration possibilities as well.

## Additional context
The server (e.g. nginx) must be configured properly
Maximum item size per storage bucket must be considered
Updating UI components to reflect allowed upload size

## Current workflow for changing file upload size for records

- cookiecutter (nginx): https://github.com/inveniosoftware/cookiecutter-invenio-rdm/blob/v7.0/%7B%7Bcookiecutter.project_shortname%7D%7D/docker/nginx/conf.d/default.conf#L118
- files-rest: the default configuration doesn't impose limits on the buckets (the limits are set to None: https://github.com/inveniosoftware/invenio-files-rest/blob/d1fb4d2f8d36cf6798a2eab0cb25e7d81df954ca/invenio_files_rest/config.py#L45-L49
- UI: https://github.com/inveniosoftware/invenio-app-rdm/blob/efb3848a710011a2b59dabb0f6eefbf830175948/invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js#L171-L172
  - Copy/Create and adapt react components for UI
  - Export new .js file
  - Copy/Create and adapt .html template (import .js file)
  - Define functions for upload/edit of record
  - Define routes for upload/edit of record

## Benefits
Adapt quotas to own needs
Time saver when only setting a config variable instead of having to go through the above steps

**Comment by lnielsen** [comment]
I've moved the quota management to the product roadmap. This ticket is now only about making it easy to change the hard-coded quota.
