### ISSUE TITLE
ORCID icon display -- not aligned with ORCID brand guidelines

### ISSUE THREAD

**Issue by lhenze** [inveniosoftware/invenio-app-rdm#1161]
Package version: <= 7 

## Describe the bug
Currently, the ORCID icon precedes the creatibutor's name.  It is displayed at 14px * 14px.
## Steps to Reproduce
1. Go to search results such as  `https://127.0.0.1:5000/search?q=&l=list&p=1&s=10&sort=newest` or a record detail page such as `https://127.0.0.1:5000/records/n24pt-mt351`

## Expected behavior

Guidelines are here: https://info.orcid.org/brand-guidelines/

Icon should follow the name and should be displayed at 16px*16px. 

## Additional context

Are there any objections to making this change?  Everywhere the icon appears, it would be after the name.  (So, before the affiliation superscript numbers.)  And slightly larger.

**Comment by fenekku** [comment]
Linked to https://github.com/inveniosoftware/invenio-app-rdm/issues/1165 (moved from react-invenio-deposit)

**Comment by lhenze** [comment]
Here are some screenshots to show the ORCIDs icon larger, and appearing after the names; also some standardizing of the display of the creatibutors lists between landing page and search results -- 

<img width="832" alt="Screen Shot 2022-02-15 at 2 43 46 PM" src="https://user-images.githubusercontent.com/86330/154138481-6bae56f8-d96e-4ddb-8a14-6ef00feeb361.png">

<img width="922" alt="Screen Shot 2022-02-15 at 2 22 18 PM" src="https://user-images.githubusercontent.com/86330/154138500-efb3e60f-1308-423a-98bc-d8b59dba3652.png">
