### ISSUE TITLE
My dashboard: filter URL

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-rdm#1187]
Allow only `uploads`, `communities` and `requests` in the URL `/my/<dashboard_name>` using Flask routing `<any()>`. As default (`None` passed), `uploads` should be displayed.

Inject in the React app and make sure it is used to display that specific tab.

**Comment by zzacharo** [comment]
closed by https://github.com/inveniosoftware/invenio-app-rdm/commit/c5d908c05c798f4ab004491a363c0fb50b3154b1
