### ISSUE TITLE
permissions: check compatibility

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#12]
Check compatibility and perform necessary changes to comply with the latest changes in `invenio-records-permissions` made by @fenekku.

Related to https://github.com/inveniosoftware/invenio-records-permissions/issues/2

**Comment by fenekku** [comment]
Blocked until https://github.com/inveniosoftware/invenio-records-permissions/pull/7 is merged and python package is deployed.

**Comment by ppanero** [comment]
@fenekku This should be moved to `invenio-rdm-records`. Although integration tests are still needed.

See: https://github.com/inveniosoftware/invenio-app-rdm/pull/14 and https://github.com/inveniosoftware/invenio-app-rdm/pull/14

**Comment by fenekku** [comment]
Got it. Will do so.

**Comment by ppanero** [comment]
@fenekku It was closed by https://github.com/inveniosoftware/invenio-rdm-records/pull/12 right?

**Comment by fenekku** [comment]
@ppanero that's right :+1:

**Comment by ppanero** [comment]
Closing then... :rocket:
