### ISSUE TITLE
Optimize form fields

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#120]
As noticed in #114 , editing form input is noticeably slow. This can be countered by using Formik's `FastField` instead of the regular `Field` for Fields that don't have dependencies.

We can wait to do this until most fields are created.

**Comment by lnielsen** [comment]
Info from @ntarocco - take care of the following cases: 1) User enters a title, and leaves the cursor in the field. 2) User then clicks "Save draft".  Because the FastField is only updating internal data on blur, this means that the latest changes won't make it into the data being saved. Thus, for the fields where we add it, we should be sure to check if above works.

**Comment by ntarocco** [comment]
> Info from @ntarocco - take care of the following cases: 1) User enters a title, and leaves the cursor in the field. 2) User then clicks "Save draft". Because the FastField is only updating internal data on blur, this means that the latest changes won't make it into the data being saved. Thus, for the fields where we add it, we should be sure to check if above works.

See [this issue](https://github.com/formium/formik/issues/671) and in particular [this comment](https://github.com/formium/formik/issues/671#issuecomment-396089967)

**Comment by zzacharo** [comment]
> > Info from @ntarocco - take care of the following cases: 1) User enters a title, and leaves the cursor in the field. 2) User then clicks "Save draft". Because the FastField is only updating internal data on blur, this means that the latest changes won't make it into the data being saved. Thus, for the fields where we add it, we should be sure to check if above works.
> 
> See [this issue](https://github.com/formium/formik/issues/671) and in particular [this comment](https://github.com/formium/formik/issues/671#issuecomment-396089967)

[Here](https://github.com/formium/formik/issues/671#issuecomment-424795894) it seems that there was an update in the `FastField` so the blur problem might have been fixed! (To be checked!)

Also, see this [comment](https://github.com/formium/formik/issues/671#issuecomment-558752390) for a nice list of things to check about slow performance.

**Comment by fenekku** [comment]
closed via https://github.com/inveniosoftware/react-invenio-deposit/pull/272
