### ISSUE TITLE
Ability to provide custom text in the publication confirmation modal

### ISSUE THREAD

**Issue by max-moser** [inveniosoftware/invenio-app-rdm#1204]
## Status Quo

Currently, the deposit form gives warnings to the user that they can't change the set of uploaded files after publishing the record anymore:

![image](https://user-images.githubusercontent.com/6437519/152130669-b8db2276-868b-4580-8fad-c20557d24f37.png)

![image](https://user-images.githubusercontent.com/6437519/152130627-e3644ece-d260-43d3-9ad8-b6e61101e30f.png)

However, these warnings are very brief and could be missed too easily.
They should be reworded to drive the fact home that the users aren't able to change the set of files after publication anymore, along with a very short description as to why; similar to Zenodo.

Bonus points if we could customize the warning text, to reference our own sandbox system (also similar to Zenodo).

## Comparison: Zenodo

On Zenodo, the warnings related to not being able to change the files after publication are more elaborate:

![image](https://user-images.githubusercontent.com/6437519/152130710-89a70f32-caf4-4473-89d0-d980a783f1a9.png)

![image](https://user-images.githubusercontent.com/6437519/152130742-85b0e536-9ced-42ac-a94d-067e1b5205b2.png)

**Comment by lnielsen** [comment]
Agree:

1. Instances should be able to provide their own text.
2. Should take into account publishing a new file and just editing of a record (where the files are already locked)

**Comment by lnielsen** [comment]
From #1094 

It should be possible to provide also e.g. deposit agreement text in the publish dialog.

> We will be using the authentication page to provide some terms and conditions, but librarians at our institution also want to be able to put our deposit agreement in the publication pop-up confirmation modal.

> A simple config that is injected in the confirmation modal would do.
