### ISSUE TITLE
dashboard: inject hardcoded urls into OverridableContext from configuration

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#1211]

**Comment by ntarocco** [comment]
* Can you please add a description of what should be done here?
* is this a duplication of https://github.com/inveniosoftware/react-invenio-deposit/issues/443?

**Comment by zzacharo** [comment]
Can be closed as duplicated of https://github.com/inveniosoftware/react-invenio-deposit/issues/443
