### ISSUE TITLE
Landing page: Subjects should be linked to a search-results page

### ISSUE THREAD

**Issue by jennur** [inveniosoftware/invenio-app-rdm#1226]
Subjects should be linked to a search results page of the respective subject.

Something along the lines of `q=metadata.subjects.subject:<subject>`

<img width="336" alt="Screenshot 2022-02-09 at 09 37 17" src="https://user-images.githubusercontent.com/21052053/153157723-c55326af-96de-4991-855c-b8a58bba5e1e.png">

**Comment by lnielsen** [comment]
https://github.com/inveniosoftware/invenio-app-rdm/pull/986
