### ISSUE TITLE
Mark required fields in deposit form

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#123]

**Comment by fenekku** [comment]
:warning: Fields marked "HTML required" get frontend validation which doesn't look good and interferes with functionality (to doublecheck if they are the true culprit...). For a taste of this, try adding a new title and clicking the x of the first or second one (problematic some of the times...), it makes the HTML check appear and doesn't remove the title (multiple tries make it remove the title...).

**Comment by zzacharo** [comment]
@fenekku is your comment still valid? Otherwise, I think we can close this issue :)

**Comment by fenekku** [comment]
Nope not valid anymore (see past discord message). We can close :) .
