### ISSUE TITLE
UI: Restricting access shows unhelpful message

### ISSUE THREAD

**Issue by apirogov** [inveniosoftware/invenio-app-rdm#1236]
## Describe the bug

When editing a draft, when you set the visibility to "restricted", it says:

`The record can only be accessed by users specified in the permissions.`

Nowhere else does the term "permissions" or "record permissions" on the page come up, so its unclear what exactly this means.
I see no field where you could specify users or something like this.

So either the field is missing (is it something that will come?) or the text message is useless as is.

**Comment by fenekku** [comment]
Yes it is for something that will come. The UI for this will be worked on in the next sprint.

**Comment by lnielsen** [comment]
I'm closing this issue as it will be dealt with as part of the management of permissions for individual records.
