### ISSUE TITLE
Header: bad alignment of my dashboard, requests, plus and login button

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#1253]
Package version (if known): <version>

## Describe the bug

The main InvenioRDM header is currently misaligned after the "My dashboard" link was introduced.

## Steps to Reproduce

* Open Mac Safari (it is happening only on Safari)
* Load any page in InvenioRDM and that part of the header is not right aligned correctly. 

## Expected behavior

![Screenshot 2022-02-14 at 16 18 40](https://user-images.githubusercontent.com/1698163/153891902-a4339476-84e3-4a01-9aac-15d995b40eec.png)

**Comment by Pineirin** [comment]
This is a Safari related issue.

**Comment by jrcastro2** [comment]
closed by https://github.com/inveniosoftware/invenio-app-rdm/pull/1290

**Comment by lnielsen** [comment]
I'm still seeing this issue on latest master:

![Screenshot 2022-02-28 at 23 45 08](https://user-images.githubusercontent.com/1698163/156071075-d9a4097b-1a2f-4d0a-bb93-c1663f9a564f.png)

**Comment by lnielsen** [comment]
Edge has the same issue: 

![Screenshot 2022-02-28 at 23 48 47](https://user-images.githubusercontent.com/1698163/156071328-e98b113a-74ad-41ed-acd9-11064a853b56.png)

**Comment by lnielsen** [comment]
Note, I've found that there's difference on logged in/out:

![Screenshot 2022-03-01 at 00 29 37](https://user-images.githubusercontent.com/1698163/156076290-ce00cd9b-5ae1-489a-b97e-796c7a3973e3.png)

Please check other pages as well for alignment issues.
