### ISSUE TITLE
webpack: add "@templates" alias via config

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-app-rdm#126]
Now that it's possible to add aliases via the `ASSETS_WEBPACK_ALIASES` config (see https://github.com/inveniosoftware/invenio-assets/pull/123), the `@templates` alias used for search templates will need to be added via the default InvenioRDM config, like so:

```python
ASSETS_WEBPACK_ALIASES = {
    '@templates': "templates",
    ...
}
```

**Comment by lnielsen** [comment]
We probably don't need the templates alias now that we can use React-Overridable.
