### ISSUE TITLE
theme: review custom styling

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#1265]
There is a general habit of creating custom css classes across the rdm ecosystem to fix styling. We should gather information and stick to SUI as much as possible or as a last resort implement new features in an overridable and semantic way.

This issue can be used as a placeholder for documenting what needs to be done to harmonize the styling across invenio modules.

**Comment by ntarocco** [comment]
@kpsherva can we close this one?
