### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/invenio-app-rdm#1299]
Address comments in the PRs below:
- [ ] Use variable for button colors, see COMMENT here: https://github.com/inveniosoftware/invenio-app-rdm/pull/1260#discussion_r812767583
- [ ] Use generic error cmp, see COMMENT here: https://github.com/inveniosoftware/invenio-app-rdm/pull/1260#discussion_r812768486 (create it if not yet there)

**Comment by ntarocco** [comment]
@jrcastro2 can we close this?

**Comment by jrcastro2** [comment]
I don't think so, the links are pointing to comments in a PR that still need to be addressed

**Comment by ppanero** [comment]
PRs seem merged, can we close?

**Comment by jrcastro2** [comment]
> PRs seem merged, can we close?

Not yet, the links point to comments, but we can create 2 issues isntead; one for implementing a generic error cmp to display the messages and another to review the usage of the colors.

**Comment by ppanero** [comment]
I would say so, is hard to grasp what this issue means otherwise, I'll make issues out of them you can add content if I miss anything

**Comment by ppanero** [comment]
https://github.com/inveniosoftware/invenio-app-rdm/issues/1616 , https://github.com/inveniosoftware/invenio-app-rdm/issues/1614 and https://github.com/inveniosoftware/invenio-app-rdm/issues/1615
