### ISSUE TITLE
Deposit: Discard changes leads to 404

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#1309]
## Steps to Reproduce

1. Create and publish new upload: https://127.0.0.1:5000/uploads/new 
2. On the record landing page: Click "Edit" 
3. On the deposit form: Click Dicard changes4. 
4. Boom: 4045. 

The behaviour is the same with the "Delete' button without publishing the upload first.

## Expected behavior

The user is sent back to https://127.0.0.1:5000/uploads

**Comment by ntarocco** [comment]
Fixed by https://github.com/inveniosoftware/react-invenio-deposit/pull/434
