### ISSUE TITLE
Deposit: Creator search should not allow creating an entry if it's already created

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#1313]
1. Search for a user that returns no results.
2. Click "create a new entry" 
3. Manually add data for the author, save and then try to search again.

![Screenshot 2022-03-01 at 00 40 35](https://user-images.githubusercontent.com/1698163/156077363-00f98b68-60b8-4311-a791-62c6c35366b6.png)

### Expected behaviour

If the full form with all fields are already displayed, then the text: "couldn't find ...." since it doesn't makes sense.

**Comment by slint** [comment]
Addressed in #1348. The "new entry" block appears only when `search_only` is set in config, and not after it has been clicked the first time
