### ISSUE TITLE
update existing fixtures/vocabularies

### ISSUE THREAD

**Issue by mb-wali** [inveniosoftware/invenio-app-rdm#1334]
## Is your feature request related to a problem? Please describe.
We are trying to add the German language of [vocabularies](https://github.com/inveniosoftware/invenio-rdm-records/tree/master/invenio_rdm_records/fixtures/data) - in order to populate the new language strings we need some kind of CLI command to update the existing vocabularies into the database and ES.

## Describe the solution you'd like
We have a CLI command `invenio rdm-records fixtures` which only adds the vocabularies if not present, and does NOT update the existing ones.
should have a similar Command that does the updates of existing fixtures/vocabularies and adds new string e.g. translated strings.

## Additional context
There is this PR - that could be used to test while creating the CLI command: inveniosoftware/invenio-rdm-records#889

**Comment by lnielsen** [comment]
This is tracked on the product board as https://github.com/inveniosoftware/product-rdm/issues/48
