### ISSUE TITLE
Strange behaviour with "subject_nested" facet

### ISSUE THREAD

**Issue by BalazsBago** [inveniosoftware/invenio-app-rdm#1335]
Package version (if known): Invenio-app-rdm 7.0.0

## Describe the bug
The search facet UI for the nested subject contains not only the subject scheme related items, but it contains items from other subject schemes as well.

## Steps to Reproduce
1. Create two subject vocabularies
2. Extend facets in the configuration file with "nested_subject"
3. Add a record with using at least one subject from all custom defined subject vocabularies (1. step)
4. See the error on the search screen

## Expected behaviour
See only the subject scheme related subjects under a subject.

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/36382735/156191839-c1f69dfd-d9cc-413b-81c1-0cf0badc3762.png)

**Comment by fenekku** [comment]
Thanks for reporting. This is a known issue: https://github.com/inveniosoftware/invenio-rdm-records/issues/798 . Feel free to :+1:  that issue so we are encouraged to work on it. Closing as duplicate.
