### ISSUE TITLE
Complex subject definition with nested facet

### ISSUE THREAD

**Issue by BalazsBago** [inveniosoftware/invenio-app-rdm#1339]
It would be nice to define complex subject scheme where the subjects in the scheme can have relation to other subjects within the scheme. Based on a complex subject scheme it would be possible to create a nested facet similar to the facet of the resource type. 

E.g.:
We would like to create a subject scheme for an ontology. The representation of the ontology is a directed acyclic graph. The nodes in this ontology representation have links / references to their parent nodes. 
Other example could be the [FOS](https://www.qnrf.org/en-us/FOS) subject scheme. Here it would be nice to see a nested search facet like:

- natural sciences
  - mathematics
  - ...
- engineering and technology 
  - civil engineering
  - ...

I think a "parents" attribute with a list of the ID-s of the subjects in the vocabulary of the subject scheme could be a good solution to define the relation between the subjects.
E.g.:
 `id: "https://example.com/my/scheme/1"
  scheme: MYSCHEME
  subject: "My term 1"
- id: "https://example.com/my/scheme/2"
  scheme: MYSCHEME
  subject: "My term 2"
- id: "https://example.com/my/scheme/3"
  scheme: MYSCHEME
  subject: "My specialized term from 1 and 2"
  parents: 
    - "https://example.com/my/scheme/1"
    - "https://example.com/my/scheme/2"
`

**Comment by lnielsen** [comment]
Thanks for the suggestion.

We have a ``subject_nested`` facet (not enabled by default):
- https://inveniordm.docs.cern.ch/customize/search/
- [subject_nested](https://github.com/inveniosoftware/invenio-rdm-records/blob/aaf8df982e9099b12b38d3374519669c9ca24f68/invenio_rdm_records/services/facets.py#L55)

As far as I remember @fenekku is using that in [invenio-subjects-mesh](https://github.com/galterlibrary/invenio-subjects-mesh) to render a nested facet.

**Comment by BalazsBago** [comment]
> Thanks for the suggestion.
> 
> We have a `subject_nested` facet (not enabled by default):
> 
>     * https://inveniordm.docs.cern.ch/customize/search/
> 
>     * [subject_nested](https://github.com/inveniosoftware/invenio-rdm-records/blob/aaf8df982e9099b12b38d3374519669c9ca24f68/invenio_rdm_records/services/facets.py#L55)
> 
> 
> As far as I remember @fenekku is using that in [invenio-subjects-mesh](https://github.com/galterlibrary/invenio-subjects-mesh) to render a nested facet.

Probably I am wrong, but it looks like that the current nested solutions has only one level of nested subjects.

E.g.:
subjects:
 - A scheme:
    - item a1 
    - item a2
 - B scheme:
    - item b1
    - item b2

But I would like to see a search facet with more levels.

E.g.:
subjects:
 - A scheme:
    - item a1 
    - item a2
 - B scheme:
    - item b1
    - item b2
 - C scheme:
   - C1 ("subcategory" within C scheme):
     - item c1
     - item c2
   -  C2 ("subcategory" within C scheme):
     - item c3
     - item c1 (this is the same item from C1, to support items with multiple "category") 

I hope I made my feature request more clear.

**Comment by lnielsen** [comment]
From a UX perspective I don't think nested facets with more than two levels makes sense. We already have user feedback on that any kind of nesting makes the facets harder to use. Perhaps an advanced search page or dedicated search interface would be a better solution.

I'm closing the issue for now as I've linked it in as a use case to a larger issue on advanced search and search performance so we have it available when scoping and defining the work for the task.
