### ISSUE TITLE
Embargo and Metadata-only fields are not properly connected

### ISSUE THREAD

**Issue by chriz-uniba** [inveniosoftware/invenio-app-rdm#1354]
Package version (if known): https://inveniordm.web.cern.ch/ (2022-03-07) --- v8 (but also in v7)

## Describe the bug

When creating a metadata-only records-draft and saving it, then removing the 'metadata-only record' tag and adding a file, I'm not able to select the proper embargo for files. That is only possible after saving the draft and then seeing the proper embargo fields again.

## Steps to Reproduce
1. Go to https://inveniordm.web.cern.ch/uploads
2. Create a metadata-only record and save the draft.
3. Remove the 'metadata-only record' tag and upload a file.
4. Try to set the embargo for the file.
5. See problem with the embargo field: "The record has no files."
--- after saving the draft the proper embargo fields appear.

## Expected behavior

When the 'metadata-only record' is toggled the 'embargo possibilities' need to be toggled as well.

## Screenshots (if applicable)
Record has a file, but embargo says, there are no files:
![image](https://user-images.githubusercontent.com/74763324/157006429-28abe847-46b7-4cb5-90b8-78bcbdcfad8e.png)

**Comment by fenekku** [comment]
@chriz-uniba This seems solved in v9.1, so I am closing. At NU we are triaging some tickets in preparation for migration + production and we were keeping our eyes on this one. Feel free to re-open or open another one if the problem persists on your end.

(I've also noticed in your screenshot that the record's visibility was marked public and not restricted. Only restricted records or files can have an embargo. I've tested with restricted record and restricted files and both work in v9.1 following the steps you've outlined).

**Comment by chriz-uniba** [comment]
Thanks a lot - tested and works! :)

P.S.: The screenshot shows the issue --- it says, that there are no files, so I wasn't able to restrict the uploaded and available files and therefore I couldn't set the embargo. Seems to work perfect now. :)
