### ISSUE TITLE
prerelease option breaks install in pyyaml

### ISSUE THREAD

**Issue by tmorrell** [inveniosoftware/invenio-app-rdm#1359]
Package version (if known): v8

## Describe the bug
I'm unable to lock packages and Install InvenioRDM because of the `allow_prereleases = true` option. Pyyaml has known issue with cython 3 https://github.com/yaml/pyyaml/issues/601, which results in a `AttributeError: cython_sources` during package locking. 

## Steps to Reproduce
1. `invenio-cli init`
2. `invenio-cli install`
3. Locking fails with `AttributeError: cython_sources`

## Expected behavior
Packages lock and InvenioRDM install

## Additional context
I'm running python 3.9 on a M1 mac installed via homebrew.

**Comment by fenekku** [comment]
Just mentioning to narrow possibilities: on linux (ubuntu) with python 3.8 things are ok. So 3.9 / m1 mac are more probable cause.

**Comment by tmorrell** [comment]
My best guess is this issue is related to the M1 and homebrew python. I've switched to the 3.9 universal2 python.org installer and package locking is fine.
