### ISSUE TITLE
deposit page should not rely on INSTANCE_SEARCH_THEME_FILE

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#140]
Now that the theming is using only one library (semantic) there is no need to split in two:
- INSTANCE_THEME_FILE
- INSTANCE_SEARCH_THEME_FILE

Relying only on INSTANCE_THEME_FILE should be enough. The search page does not rely on INSTANCE_SEARCH_THEME_FILE anymore, however deposit page does.

The corresponding file has been removed from the Cookiecutter, but there is still a default in `invenio-app-rdm`

Action points:
- Remove from `invenio-app-rdm`
- Remove dependencies on INSTANCE_SEARCH_THEME_FILE

Discussion point:
- How does this affect customizations?

**Comment by fenekku** [comment]
I've done this to address this issue: https://github.com/inveniosoftware/invenio-app-rdm/pull/148/files?file-filters%5B%5D=.html&file-filters%5B%5D=dotfile#diff-fc6f54a9979ee2e6b068636f168a4bc4R17 (if this is good enough for May, we can put the rest of the tasks to next release)

**Comment by ppanero** [comment]
Sounds good to me. I haven't tested the deposit page, if it works... Go ahead an move the issue to June 🚀

**Comment by zzacharo** [comment]
@fenekku can you double check this issue because I think I already removed the dependency on the `INSTANCE_SEARCH_THEME_FILE`.

**Comment by fenekku** [comment]
This has been removed from invenio-app-rdm. We can close this issue now. We will revisit customization in this issue: #132
