### ISSUE TITLE
Getting a DOI minted on the deposit page can be difficult

### ISSUE THREAD

**Issue by max-moser** [inveniosoftware/invenio-app-rdm#1407]
Package version:
invenio-app-rdm 8.0.0
invenio-rdm-records 0.34.7

## Describe the bug
The workflow/UX for getting a DOI minted for a draft is somewhat hard; it is easy to get stuck with validation errors like `doi: missing doi for required field` and `doi: a pid already exists for type doi`

NOTE: If the draft gets stuck on the DOI validation, it should usually be fixable by clicking "No" on the "Do you already have a DOI for this upload?" input, saving the draft, and clicking "Get a DOI now!" afterwards.
Thanks @ppanero for this procedure

### Case 0 - Happy Path

1. Fill out the required metadata
  ** Fill out resource type, title, publication date, creators, publisher
  ** Tick the checkbox for "Metadata-only record"
  ** Tick "No" on the DOI question
2. Save draft
3. Click "Get DOI now!"
  ** For some reason, the UI complains about "Please fill out this field" for Dates, Alternate Identifiers, and/or Related works (even though no values are given for any of these fields, as is default)... This can seemingly be ignored though

### Case A

Same procedure as Case 0, but skipping step 2.
Now, a validation error is reported: `doi: a pid already exists for type doi`.
The "metadata-only record" checkbox is unticked.
Also, it will complain again about the seemingly required list fields (dates, alternate identifiers, related works).

This case is comparatively tricky to get out of:

1. Click "no" on the DOI question
2. Tick "metadata-only record" checkbox
3. Save the draft
  ** Now, a validation error is reported: `doi: missing doi for required field`.
  ** Additionally, another validation error is reported: `title: missing data for required field`, even though the title has some set value.
4. Change the value of the title
5. Click "yes" on the DOI question
6. Save draft
7. Click "no" on the DOI question
8. Save draft
9. Click "get DOI now"
  ** Again, asks to fill out the "required" list fields

NOTE: If steps 5 - 7 aren't followed, the system will complain about the DOI:
* Save draft => `doi: missing doi for required field`
* Get a DOI now => `doi: a pid already exists for type doi`

## Expected behavior

I might click the `Get DOI now` button at any point between entering the record's metadata and uploading files.
I expect a DOI to be reserved and assigned to the draft in any case (even if not all metadata is filled out with valid values yet).
Also, assigning a DOI should interfere as little as possible with the process of creating the record (unsaved metadata fields should not be lost, and file uploads should not be cancelled – I didn't test if this is an actual issue though).

## Notes

Further testing should be done for the interaction with DOI minting and file uploads:
Does DOI minting interrupt file uploads?
What is the general behavior for the DOI minting if it's not a `metadata-only` record as in the cases tested here?

Also, what happens when there are unsaved metadata changes and the "get DOI now" field is clicked?

**Comment by ppanero** [comment]
duplicate/related of https://github.com/inveniosoftware/invenio-rdm-records/issues/856

**Comment by fenekku** [comment]
@max-moser We also had the main problem outlined in the past and on v9.1 it is solved. I am closing (we are trying to keep track of the issues that are still relevant for us before we go to migration and production). Feel free to open another one to capture other aspects.

**Comment by max-moser** [comment]
@fenekku yeah, i noticed during the migration to v9 that after throwing away our overrides and using the latest versions, this issue disappeared almost magically :partying_face: 
i just forgot to close the issue...
