### ISSUE TITLE
semantic-ui: flash message on login should be edge to edge

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#143]
![Screenshot 2020-05-28 at 15 52 06](https://user-images.githubusercontent.com/1698163/83150254-56b29100-a0fb-11ea-96c9-24f1bd58ca89.png)

The alert should be edge to edge with text centered.

**Comment by zzacharo** [comment]
The message should be also dismissable. The bundle `webpack['theme.js']` includes the js code for dismissing flash messages, see https://github.com/inveniosoftware/invenio-theme/blob/2e8cf8bd6399ff36cab297fa726fd61d86440ad9/invenio_theme/assets/semantic-ui/js/invenio_theme/theme.js#L17. Verify if the bundle is there and if not add it!

**Comment by lnielsen** [comment]
This is still an issue.
