### ISSUE TITLE
semantic-ui: frontpage styling issues

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#145]
Small browser window issues:

- Numbers are not centered
 - Text too small to read in boxes below numbers

![Screenshot 2020-05-28 at 16 01 02](https://user-images.githubusercontent.com/1698163/83151188-8a41eb00-a0fc-11ea-87ec-a180ada064a6.png)

**Comment by ppanero** [comment]
Closed by #164
