### ISSUE TITLE
deposit form: community selection modal loader missing

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-rdm#1483]
Package version (if known): <version>

## Describe the bug
The modal visible in the screenshot below does not show a loading state while performing a search for available communities. In low network performance the request takes more time and it appears like there were no communities available to be selected

## Expected behavior

Modal is in loading state while fetching available communities

## Screenshots (if applicable)

![Screenshot 2022-04-26 at 15 13 30](https://user-images.githubusercontent.com/38131488/165307858-18228984-23cd-47c3-aa7e-6cd51774fe57.png)

**Comment by zzacharo** [comment]
Requires the styling change from https://github.com/inveniosoftware/react-invenio-deposit/pull/477

**Comment by zzacharo** [comment]
Maybe related issue https://github.com/Semantic-Org/Semantic-UI-React/issues/3133
