### ISSUE TITLE
refactor: user uploads colors hardcoded - should be overridable/easily added

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-rdm#1503]
on another topic: those colors are not easily overridable or extendable in the current implementation, they are hardcoded

_Originally posted by @kpsherva in https://github.com/inveniosoftware/invenio-app-rdm/pull/1497#discussion_r862775733_

**Comment by jennur** [comment]
Addresses https://github.com/inveniosoftware/invenio-app-rdm/issues/1615
