### ISSUE TITLE
Banner `Please login...` is displayed twice

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-rdm#1548]
1. Install a new `my-site`
2. click on My Dashboard

<img width="844" alt="Screenshot 2022-05-11 at 19 40 07" src="https://user-images.githubusercontent.com/2089455/167913119-dc094124-2b01-4a20-9da6-a0432ea4e1e3.png">

**Comment by ppanero** [comment]
Couldn't reproduce..

![Screenshot 2022-05-12 at 11 39 48](https://user-images.githubusercontent.com/6756943/168041412-99d17d3a-b8b2-4034-853c-9138caed83e7.png)
