### ISSUE TITLE
DOI: icon error

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-rdm#1561]
Enable DOI in your config.

After creating a new instance with the demo data, the badge is not displaying correctly on the right panel, Details -> DOI.

<img width="1357" alt="Screenshot 2022-05-12 at 20 08 53" src="https://user-images.githubusercontent.com/2089455/168141532-8feec627-9962-4e86-a727-ba32ab7e6c6e.png">

**Comment by jennur** [comment]
I'm not able to reproduce the issue, the badge is showing up fine in my instance?
![Screenshot 2022-05-13 at 13 36 50](https://user-images.githubusercontent.com/21052053/168275433-a42291dd-2cf3-43c5-99e7-0c67f0f747fb.png)
