### ISSUE TITLE
custom award: no need for accordion, obfuscating required fields

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-rdm#1567]
## Describe the bug

The custom award widget should show all fields from the beginning instead of requiring the user to click the custom award information link to show the fields.

It should be made clear that the fields are optional.

## Screenshots (if applicable)

![Screenshot 2022-05-16 at 15 44 27](https://user-images.githubusercontent.com/1698163/168607025-0fa65786-cfa5-4ec5-ace6-fd89dd2d22e2.png)
n of what the bug is.

**Comment by jennur** [comment]
Getting solved in https://github.com/inveniosoftware/invenio-app-rdm/issues/1578
