### ISSUE TITLE
Landing page: accordion toggle icons have inverted behaviour

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#1577]
Package version (if known): <version>

## Describe the bug

The carret arrow left and down icon on the preview and files accordions (see screenshots) have been inverted.

## Expected behavior

- An open accordion should have a ``carret down`` icon.
- A closed accordion should have a ``carret left`` icon.  

## Screenshots (if applicable)

![Screenshot 2022-05-16 at 15 26 07](https://user-images.githubusercontent.com/1698163/168603344-65f7bc82-e2d5-4ce1-96c5-3ec0b2e43384.png)
![Screenshot 2022-05-16 at 15 26 34](https://user-images.githubusercontent.com/1698163/168603348-47c166d8-a685-4835-9b24-0b3b2cf90193.png)

**Comment by kpsherva** [comment]
this is a regression issue, possible cause: https://github.com/inveniosoftware/invenio-app-rdm/commit/24527a1175e48a86cf3d936e626ea677fe98e8f7
