### ISSUE TITLE
release: october release wrap-up

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#16]
# October

- [ ] Invenio-Access:
    - [ ] Pending PR on explicit-permissions
- [ ] Invenio-Records-Permissions:
    - [x] **Merge Policy config PR** (G)
    - [x] **Release  v1.0.0a3** (G)
    - [x] Enabling sharing permissions PR (P to review, G afterwards) *moved to Nov board*
    - [x] Metadata to deal with explicit permissions (Check RFC) *moved to Nov board*
- [ ] Invenio-PIDstore:
    - [x] Extract rand string into independent base32-identifier package (G)
    - [x] Use independent package in Invenio-PIDstore (BLOCKED until package released but PR there)
    - [ ] Release Invenio-PIDstore (G: BLOCKED by above)
- [ ] Invenio-RDM-Records:
    - [x] **Integrate Policy config from Invenio-Records-Permissions** (G)
    - [x] **Merge non-issue fields PR** https://github.com/inveniosoftware/invenio-rdm-records/pull/21 (P+G)
    - [x] **Release v1.0.0a2** (G)
    - [ ] Integrate new PID from random strings. (BLOCKED until base32-identifier package is released)
    - [ ] Release (G)
- [ ] Invenio-App-RDM:
    - [x] **Integrate Invenio-RDM-Records release** https://github.com/inveniosoftware/invenio-app-rdm/pull/17(P)
    - [x] **Merge PR to remove config**  https://github.com/inveniosoftware/invenio-app-rdm/pull/14 (P)
    - [x] **Release  v1.0.0a2** (P)
    - [x] **Create demo CLI to populate DB with demo data records** (G)
    - [x] **Release  v1.0.0a3** (G)
- [ ] Cookiecutter-invenio-rdm:
    - [x] **Bump versions of the Invenio-App-RDM** https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/6 (P)
    - [x] **Remove setup.py file** https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/6 (P)
    - [ ] **Remove scripts folder**
    - [x] **Add static folder for logo** https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/6 (P)
    - [ ] **Release**
- [ ] Invenio-CLI:
    - [x] **Integrate release of Cookiecutter-invenio-rdm** https://github.com/inveniosoftware/invenio-cli/pull/23 (P)
    - [x] Fix foreground containers bug https://github.com/inveniosoftware/invenio-cli/pull/23 (P)
    - [x] **Release**
- [x] Docs:
    - [x] **Document changing logo customization** https://github.com/inveniosoftware/invenio-app-rdm/wiki#customization

**Comment by fenekku** [comment]
Done.
