### ISSUE TITLE
theme.less: remove .btn-primary in theme.less

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#160]
In the `theme.less` file, there are still kept bootstrap classes e.g `.btn-*`. We should review if they are still used in the semantic UI context and if yes, refactor them to use the proper SUI classes. Otherwise, we can remove them.

**Comment by lnielsen** [comment]
Update.

Remove ``.btn-primary`` in ``theme.less`` as it is not used anywhere.
