### ISSUE TITLE
Unable to change the colour of the search-buttons

### ISSUE THREAD

**Issue by chriz-uniba** [inveniosoftware/invenio-app-rdm#1642]
Package version (if known): version-v9.0.0.rc1 (there where also issues in v8)

## Describe the bug

Somehow, it looks like I'm not able to change the colour of the search-buttons.

## Steps to Reproduce

Based on this line: https://github.com/inveniosoftware/invenio-app-rdm/blob/716b768447611fd7567133fb7349d91966c35d04/invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.variables#L26
I tried various combinations.

1.  Add the following to `my-site/assets/less/site/globals/site.variables`

    Version 1: `@searchButtonColor: #97BF0D;`
    Version 2: `@searchButtonColor: #97BF0D !important;`
    Version 3: `@secondaryColor: #97BF0D;`
    Version 4: `@secondaryColor: #97BF0D !important;`

2. Do not see any changes of the search-buttons:

    For example:
    ![image](https://user-images.githubusercontent.com/74763324/169329071-3a14426c-ca15-4f28-9184-14cd27423704.png)

## Expected behavior

The button should have this green
![image](https://user-images.githubusercontent.com/74763324/169329298-195c4d0d-900b-4149-b794-1c9747727fb6.png)

## Additional context

- in v8 the colour changed but not to the colour that we expected:
  ![image](https://user-images.githubusercontent.com/74763324/169329814-e63dc19a-f0e1-4a99-98d1-88f21901f81c.png)
- in v7 everything did work as expected
- other changes like changing the `primaryColor`, `brandColor`, `navbarBackgroundColor` do work

**Comment by kpsherva** [comment]
fix provided in v9.0.1

**Comment by Herrner** [comment]
@chriz-uniba So did you manage to change the color in the end? And how? I still can't set `@searchButtonColor` no matter what I try.

**Comment by chriz-uniba** [comment]
@Herrner, we have a nasty nasty hack which was created on v9.0.0.rc1 or v9.0.0 and is not yet cleaned up:

Current setup:

invenio-app-rdm 9.0.3

site.variables
```
@unibaGreen0: #97BF0D;
@secondaryColor: @unibaGreen0;
@searchButtonColor: @secondaryColor !important;
```

site.overrides
```
.ui.search.button {
  background-color: @secondaryColor !important;
}
```

If I remember correct this worked even before the fix in v9.0.1 - but I'm not sure about that.
I think the ugly `site.overrides` part did the trick, but since we knew that it was a bug, we stopped there and where happy that our button was green. --- Or we waited for the changes in v9.0.1 and saw that it worked with the last tested version and didn't clean up so far...

![image](https://user-images.githubusercontent.com/74763324/176615074-d6c168d9-2c2f-4d96-9285-c9e6450b405f.png)

We will need to come back to that in the next round of upgrades (likely v9.1).

**Comment by chriz-uniba** [comment]
Also related: https://discord.com/channels/692989811736182844/839598022760857640/980727321986232411

**Comment by Herrner** [comment]
Your hack is actually less ugly than mine (overwriting the style inline, including `!important`), so I will probably hack something similar and wait until changing `@searchButtonColor` actually does what it is probably supposed to do. I think there are too many `!important` statements in the css foodchain anyways...

**Comment by chriz-uniba** [comment]
@Herrner in v9.1 I'm able to set the search button colour as follows:

in `site.variables`
```
@unibaGreen0: #97BF0D;
@searchButtonColor: @unibaGreen0;
```
