### ISSUE TITLE
Error page when creating a user with an already existing username.

### ISSUE THREAD

**Issue by Pineirin** [inveniosoftware/invenio-app-rdm#1661]
When you try to create a user with an already existing username, you will go to a low level error page. The sign up form should warn you that there is a user already with that username and that you should pick a different one, as it does with the email.
![Screenshot from 2022-05-24 16-34-43](https://user-images.githubusercontent.com/25476209/170064718-41274aaf-89e8-4327-a743-bc02572f9add.png)

**Comment by rekt-hard** [comment]
![image](https://user-images.githubusercontent.com/72449192/171143661-6adcbecc-4d90-4500-8549-753bec85118b.png)

In the current demo instance, the following response can be observed.
Looks like it is solved
