### ISSUE TITLE
Community Image Overflow

### ISSUE THREAD

**Issue by rekt-hard** [inveniosoftware/invenio-app-rdm#1681]
Package version (if known): v9

## Describe the bug
Community image overflowing in header.

## Steps to Reproduce
1. Register user
2. Login
3. Create community and upload narrow image (height:width relation ~4:1)
4. Create new draft and select previously created community
5. Click on "Save draft"

## Screenshots (if applicable)
![Screenshot from 2022-05-31 15-24-53](https://user-images.githubusercontent.com/72449192/171184160-523185cb-a009-4f9d-8e9a-3edafc93ae1f.png)

**Comment by NRodriguezcuellar** [comment]
i linked my PR which should fix this problem too :sweat_smile:, as part of changes to several places using community logos.

**Comment by rekt-hard** [comment]
Then let's go with the changes of your PR @NRodriguezcuellar. I will close this issue, when your PR is merged
