### ISSUE TITLE
v6 containerized applicaton failes to build

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/invenio-app-rdm#1683]
Package version (if known): v6

## Describe the bug
Containerized applicaton fails to build in v6

## Steps to Reproduce
1. Install v6 `invenio-cli init rdm -c v6.0`
2. cd to the folder
3. Execute `invenio-cli containers start --lock --build --setup`

## Expected behavior
v6 correctly builded and containers running.

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/15194802/171218921-861a955d-1588-4921-8bbc-9fe13b1ecf2c.png)

**Comment by ppanero** [comment]
@jrcastro2 can close?

**Comment by jrcastro2** [comment]
> @jrcastro2 can close?

Unfortunately no, just tested now and still happening and version 6 is still alive till end of this year ([RDM EOL](https://inveniordm.docs.cern.ch/releases/maintenance-policy/#end-of-life-dates))

**Comment by ppanero** [comment]
closing, EOL
