### ISSUE TITLE
deposit: Loading state with grey outter div rotating

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/invenio-app-rdm#1703]
Package version (if known): [v9.0.2](https://github.com/inveniosoftware/invenio-app-rdm/commit/4b8ca95f8f5f8efecf3ad97fea77f02dfc8ddff6)

## Describe the bug
Bug on loading state of any action in the deposit form

## Steps to Reproduce
1. Go to new upload
2. Click on 'Save draft'
4. See loading state with outter div rotating

## Expected behavior
See a normal loading state

## Additional context

https://user-images.githubusercontent.com/15194802/172342422-ebd49af8-39b2-4dad-8808-efa1c430cbe6.mp4

**Comment by alejandromumo** [comment]
Forcing consistency: updated deposit form control buttons to use `semantic-ui-react` button `loading` property.
