### ISSUE TITLE
members: action dropdowns changing size

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-rdm#1714]
- [x] On the action the dropdown changes size to leave space for the green icon. The size  of the dropdown should not change depending on the action. Test the behaviour also with error returned

![Screenshot 2022-06-08 at 17 20 01](https://user-images.githubusercontent.com/38131488/172659327-120b7219-1e7f-4b73-bc52-1efc54726d00.png)
![Screenshot 2022-06-08 at 17 20 13](https://user-images.githubusercontent.com/38131488/172659330-3b6e196e-4fa0-4363-904a-5cf3c754de54.png)

- [x] dropdown icon is placed misaligned with the dropdown (too big right padding?)

**Comment by alejandromumo** [comment]
Result: 

![Screenshot at Jun 15 11-07-39](https://user-images.githubusercontent.com/21204744/173789844-16c96a04-beb1-408a-b235-53f351664d70.png)

The error popup does not disappear, to be fixed in a new issue

**Comment by kpsherva** [comment]
is it also implemented on the role dropdown and invitations tab?
