### ISSUE TITLE
record details: file preview broken on jupyter notebooks

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-rdm#1751]
![unknown](https://user-images.githubusercontent.com/38131488/173876492-0ba8192a-c147-48b4-b6d5-8ecfe940fcee.png)

**Comment by alejandromumo** [comment]
I got this error instead

![Screenshot at Jun 17 10-35-58](https://user-images.githubusercontent.com/21204744/174260691-3d2f35b0-6284-429d-8f30-27b755bd3652.png)

**Comment by ntarocco** [comment]
It looks like that the templates are searched here ([code](https://github.com/jupyter/nbconvert/blob/main/nbconvert/exporters/templateexporter.py#L243)):
```python
from nbconvert import HTMLExporter
html_exporter = HTMLExporter()
html_exporter.template_paths

['/usr/local/share/jupyter/nbconvert/templates/lab',
 '/usr/local/share/jupyter/nbconvert/templates/base',
 '/.local/share/jupyter',
 '/.local/share/jupyter/nbconvert/templates',
 '/.local/share/jupyter/nbconvert/templates/compatibility',
 '/usr/local/share/jupyter',
 '/usr/local/share/jupyter/nbconvert/templates',
 '/usr/local/share/jupyter/nbconvert/templates/compatibility',
 '/usr/share/jupyter',
 '/usr/share/jupyter/nbconvert/templates',
 '/usr/share/jupyter/nbconvert/templates/compatibility',
 '/usr/local/share/jupyter/nbconvert/templates']


html_exporter.environment.get_template('basic')
TemplateNotFound error
```

And the `basic` is there:
```shell
ls -al /usr/local/share/jupyter/nbconvert/templates
...
drwxr-xr-x.  2 root root  121 Jun  1 18:05 base
drwxr-xr-x.  2 root root   44 Jun  1 18:05 basic
drwxr-xr-x.  3 root root   78 Jun  1 18:05 classic
...
```

Not clear why the template engine in not finding them. A `breakpoint` probably [here](https://github.com/jupyter/nbconvert/blob/main/nbconvert/exporters/templateexporter.py#L365) should help.
