### ISSUE TITLE
Community names with large words break the layout on mobile

### ISSUE THREAD

**Issue by alejandromumo** [inveniosoftware/invenio-app-rdm#1770]
When a community has a title with large words, the whole page layout breaks in mobile. See:

![Screenshot at Jun 30 10-40-19](https://user-images.githubusercontent.com/21204744/176633295-c49f6f3b-ad83-482b-8912-c81595913154.png)

**Comment by kpsherva** [comment]
after testing, found more issues:

![Image](https://user-images.githubusercontent.com/38131488/195841047-1e3652c9-53e7-4f26-84c1-3d8963a511e7.png)
![Image](https://user-images.githubusercontent.com/38131488/195841046-b8bf3e57-de1a-47fc-ae42-3d67c47d6571.png)
