### ISSUE TITLE
users: add global config variable to set default profile visibility to "False"

### ISSUE THREAD

**Issue by alejandromumo** [inveniosoftware/invenio-app-rdm#1779]
Add a global configuration variable to set the user's profile visibility to `False` (restricted) by default. It is currently being set to `restricted` but it is not based on a configuration variable. Adding this variable allows the default visibility to be configured by instance.

Additionally, this feature should be documented and explained so that users can understand why it is set to `False` by default and how to override it if they want to. 

- [ ] Analyse where this variable must be taken into account.
- [ ] Analyse possible implications / consequences of adding this configuration.
- [ ] Analyse where this variable should be set and how it can be overridden by instance.
- [ ] If viable, implement the configuration variable.
- [ ] Add tests.
- [ ] Add documentation.

**Comment by lnielsen** [comment]
It already defaults to false, right? So this is about having a config that allows to override it as well as adding the documentation?

**Comment by Samk13** [comment]
Would it be possible if we can have both [user and email]() visibility values  in `invenio.cfg`  for easier change

**Comment by alejandromumo** [comment]
> Is it for only user visibility or both [user and email](https://github.com/inveniosoftware/invenio-accounts/blob/master/invenio_accounts/models.py#L144-L145), it would be convenient if we can alter the value from within the `invenio.cfg` no?

I agree that we could have two separate configs so instance admins have more granular control on these permissions. On the otehr hand, since this is just about defaulting perhaps it is not necessary. I think it needs to be analysed based on what makes sense for the users and how this impact code's maintainability / readability. 

I am first checking how this can be done and then I will dump that information in this issue to be implemented later on, as the 9.1 dev cycle is almost finished.

I got caught up with other tasks and will be soon moving back to this one again.

**Comment by fenekku** [comment]
We want this as well. 

The use case: our users want to add members to their communities right away. Having them go first into their profile to change their visibility is .... not going to happen. Given that the instance is tied to an institutional login, privacy concerns are more or less moot. Having that configuration variables control default visibility and default email separately would be nice (we may want to hide the email by default but keep users visible in the member autocomplete).

**Comment by RosaLo** [comment]
@fenekku : we want this as well and also see the same use case -  this happened live during demo-session , once community is created,  the community manager wants to add users but is not able to find the users since the users have their profile set to hidden by default. So the community manager will not be able to add users to the community unless s/he communicate somehow to users that they must change profile to visible. So for setting up an institutional repository, being able to change the default value from hidden to visible is a wanted feature.
