### ISSUE TITLE
communities: page has few issues 

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#179]
The communities page has a few glitches:

![image](https://user-images.githubusercontent.com/1932651/83568191-60b40580-a4e8-11ea-90e1-3b8a591222a2.png)

- [x] The header should be the same height as in the other pages The header is like this:
<img width="1438" alt="Screenshot 2020-06-02 at 18 13 31" src="https://user-images.githubusercontent.com/22594783/83543552-dd50df00-a4fc-11ea-9ef1-bf1c18af67e4.png">

and should be like:
<img width="1676" alt="Screenshot 2020-06-02 at 18 13 56" src="https://user-images.githubusercontent.com/22594783/83543575-e641b080-a4fc-11ea-8f68-067676345b1a.png">

- [x] ~~There is an issue with the search about fetching results (looks like an index issue, but the index does exist...)~~ was an invenio-oauthclient issue and it is fixed now. 

- [x] The footer should be like:

![image](https://user-images.githubusercontent.com/1932651/83568358-948f2b00-a4e8-11ea-87e9-f670952e7956.png)

- [ ] When you are in a communities detail page and you click the search in the header, then you are staying in the same page instead of navigating to the search page.

**Comment by fenekku** [comment]
Since communities is dropped for now. We can remove this.
