### ISSUE TITLE
Hidden email in profile doesn't hide email from /api/users

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#1808]
Package version (if known): 9.1.2

## Describe the bug
Even though a user marked their email as hidden in their profile (and saved preferences), their email is still visible in the autocomplete for another user trying to invite them.

## Steps to Reproduce
1. As one user mark your profile as public and your email as hidden 
2. As another user try to invite the first user to a community
3. See their email in the autocomplete

## Expected behavior
The email shouldn't be show on the auto-complete.

## Screenshots (if applicable)

![hidden_email_shows_up](https://user-images.githubusercontent.com/1932651/178761922-df1230c7-3676-4345-93de-f9b95f8f2f2a.png)

**Comment by kpsherva** [comment]
Hello!
Thanks for reporting it.
I remember testing it in the past, and the email was not visible (in fact the field was totally removed from the resource). Are you sure the user was re-indexed after saving the preferences?

**Comment by fenekku** [comment]
Ah, how would I know if the user was re-indexed? Is this a task done on a longer schedule, so I wouldn't see the changes immediately (or within a couple minutes) but rather the day after?

**Comment by kpsherva** [comment]
You would see it after few seconds, also there is a log in your console showing the indexing celery task has been completed

**Comment by fenekku** [comment]
Thanks, after an upgrade to 9.1.2, the email visibility seems to be updated appropriately in a way: the error is now that the UI displays "null" for the email when it's hidden:

![1808_original_no_email](https://user-images.githubusercontent.com/1932651/179545135-a4f963b4-6d93-4424-8a6a-1975dda82043.png)

**Comment by fenekku** [comment]
Closing this in favour of real reason for the problem: https://github.com/inveniosoftware/invenio-communities/issues/789
