### ISSUE TITLE
Details page accordions don't re-open properly

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#1835]
Package version (if known): 9.1 (locally and on demo site)

## Describe the bug
After closing a file accordion on a record's details page and clicking to re-open it, it doesn't re-open properly:

### Initially (open)

![image](https://user-images.githubusercontent.com/1932651/184404313-280fbb4f-318e-4bd4-b37a-3f4401dcaab9.png)

### After closing/minimizing the accordion and trying to re-open it 

![files_accordions](https://user-images.githubusercontent.com/1932651/184403922-4795e8db-2fa5-4986-8ddc-d6694ac4b7e6.png)

## Steps to Reproduce
1. Upload a record with files
3. Click on the files accordion - the image is minimized
4. Click on the files accordion again
5. See error

## Expected behavior
The accordion would open and close correctly.

**Comment by fenekku** [comment]
And a video: 

https://user-images.githubusercontent.com/8138663/189943120-0a8cb9b8-258c-4a85-b7fb-bd8501cc7e61.mov

**Comment by rekt-hard** [comment]
This seems to be an issue with Firefox, as it is working properly with Chrome.
See also the [demo page](https://semantic-ui.com/modules/accordion.html) and https://github.com/Semantic-Org/Semantic-UI/issues/7087

**Comment by fenekku** [comment]
As of v11 (even on firefox), this seems to have been resolved.
