### ISSUE TITLE
settings: applications missing styling

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#186]
Applications page is missing styling (buttons and spacing) 

![image](https://user-images.githubusercontent.com/1932651/83570704-20ef1d00-a4ec-11ea-933b-f585f8cb4826.png)

The security page looks great in contrast:

![security_page](https://user-images.githubusercontent.com/1932651/83571017-a1ae1900-a4ec-11ea-9667-2b73332f2ae4.png)

**Comment by alexsdutton** [comment]
I'm going to have a look at this now :-)
