### ISSUE TITLE
ROR autocomplete lack of country results in incorrect selection

### ISSUE THREAD

**Issue by tmorrell** [inveniosoftware/invenio-app-rdm#1868]
Package version (if known): v9.1

## Describe the bug
Since the Affiliation and Funder ROR autocomplete lacks country information, funders with common names like "National Institute of Health" can't be distinguished.

## Steps to Reproduce
1. Go to Funding, Add custom
2. Search National Institute of Health
3. See there are two identical options:
![Screen Shot 2022-09-08 at 3 14 30 PM](https://user-images.githubusercontent.com/10798874/189237308-e5a25014-ded3-41e3-bac2-30eaf001ffda.png)
4. If you select the first one, you've picked the National Institute of Health in Pakistan

1. Go to Add creator, Affiliation
2. Search National Institute of Health
3. The first option seems to be correct
![Screen Shot 2022-09-08 at 3 34 03 PM](https://user-images.githubusercontent.com/10798874/189237812-058f12b5-282d-4755-a923-3e3feebbe095.png)
4. But it's the NIH in Pakistan again

## Expected behavior
ROR autocompletes include the country, to distinguish RORs with the same name.

**Comment by ntarocco** [comment]
Related issue: in the record landing page, we don't display the ROR id and country (basically, more info) for funders, in the Funders tab in the bottom of the landing page.
