### ISSUE TITLE
v10-upgrade: notes to be added to the recipe

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#1876]
- [x] User need to create the `my-site/assets/templates/custom_fields` folder (folder was already created in the cookiecutter)
- [x] If the custom fields contain required fields, demo records will fail. Therefore the setup has to be done as `invenio-cli services setup --no-demo-records`. They might still fail in the landing page UI, unless the default is changed.
- [x] document how to populate the mappings for custom fields in an existing instance e.g create a debug pod with the new code and run the `invenio [rdm-records, communities] custom-fields init`
- [x] mention in the release doc update the helm charts changes, big warning do not use in prod
- [x] upgrade from ES 6 and ES 7

### Known limitations

- [x] With InvenioRDM v10, communities custom fields are not displayed in the community profile page, but they are searchable. This feature will be implemented in one of the following InvenioRDM releases.

### OpenSearch

- change `Pipfile` and replace `elasticsearch7` with `opensearch1`
- replace all occurrences in Docker compose (fixme, document all changes in cookiecutter)
- pipenv run pip uninstall -y elasticsearch-dsl elasticsearch`
- pipenv install
- reindex everything (fixme, put cmd here)

### Breaking changes

- [x] the var `SEARCH_ELASTIC_HOSTS` has been change to `SEARCH_HOSTS`    
- [x] remove SuperUser from invenio-records-permissions
- [x] AdminUser has been removed, affecting can_delete and oaiserver in rdm-records

**Comment by ppanero** [comment]
Community fields are always shown in settings page but only in the creation when "required"

**Comment by ppanero** [comment]
>  If the custom fields contain required fields, demo records will fail. Therefore the setup has to be done as invenio-cli services setup --no-demo-records. They might still fail in the landing page UI, unless the default is changed.

- Landing page does not fail when required cf are not present (e.g. old records)
- Doing a invenio-cli services setup (without the --no-demo-data) fails. As predicted. But is already documented:

**Comment by ppanero** [comment]
>  document how to populate the mappings for custom fields in an existing instance e.g create a debug pod with the new code and run the invenio [rdm-records, communities] custom-fields init

https://inveniordm.docs.cern.ch/customize/custom_fields/records/#initialize
