### ISSUE TITLE
Communities creation broken?

### ISSUE THREAD

**Issue by tmorrell** [inveniosoftware/invenio-app-rdm#1885]
Package version (if known): v9.1

## Describe the bug
The communities creation UI is broken by a new javascript dependency. When a user types in the identifier field, their text disappears and the url is displayed at `/communities/[object Object]`

## Steps to Reproduce
1. Go to /communities/new
2. Type in the identifier field
3. Your text has vanished, and a community cannot be created.

## Expected behavior
Users should be able to create communities

## Screenshots (if applicable)
![Screen Shot 2022-09-19 at 1 49 43 PM](https://user-images.githubusercontent.com/10798874/191114162-2e388713-5eb1-460f-b255-5cba5bef583f.png)

## Additional context
This error appeared after rebuilding assets, and doesn't currently show up on the InvenioRDM demo site. The possible culprit npm packages are:

browserslist-4.21.3.tgz -> browserslist-4.21.4.tgz
caniuse-lite-1.0.30001399.tgz -> caniuse-lite-1.0.30001402.tgz
electron-to-chromium-1.4.250.tgz -> electron-to-chromium-1.4.253.tgz
is-callable-1.2.5.tgz -> is-callable-1.2.6.tgz
react-invenio-forms-0.10.16.tgz -> react-invenio-forms-0.10.19.tgz

**Comment by ppanero** [comment]
It is working on the QA demo site (https://inveniordm-qa.web.cern.ch)
Diff deps from the mentioned ones:
- caniuse-lite-1.0.30001406
- electron-to-chromium-1.4.254

**Comment by tmorrell** [comment]
Huh...I've updated assets and am still seeing the issue. I'll have to do some more debugging

**Comment by tmorrell** [comment]
This was fixed by upgrading invenio-communities to 2.8.9. The underlying issue is using `invenio-cli assets build` to update things like CSS also updates node packages, but doesn't update the underlying python package.
