### ISSUE TITLE
theme: overwrite font to bring back helvetica

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-rdm#1890]
Due to this change https://github.com/inveniosoftware/invenio-theme/commit/229654382b1df6318b0626615c2826448abff095
the fonts were overwritten in app-rdm. We need to specify the helvetica font for rdm theme.

**Comment by jennur** [comment]
Question: Should it be in `invenio-app-rdm` or `invenio-theme`?
