### ISSUE TITLE
Move InvenioRDM modules to use pytest in run-tests.sh

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#191]
As was discovered, `python setup.py test` installs `test_requires` dependencies before running the tests. This is problematic:

- on travis it means that the built dependency test matrix is not respected because test dependencies are installed after the frozen dependencies.
- `python setup.py test` is deprecated in fact: https://setuptools.readthedocs.io/en/latest/setuptools.html#test-build-package-and-run-a-unittest-suite

This affects **all** Invenio modules and other teams should also update their tests. (easier to divide and conquer the problem and have us deal with the inveniordm modules)

- [x] invenio-app-rdm
- [x] invenio-rdm-records
- [x] invenio-records-permissions
- [x] invenio-records-resources
- [x] invenio-drafts-resources
- [x] invenio-cli
- [x] invenio-communities
- [x] flask-resources

**Comment by ppanero** [comment]
This will be done when migration to docker-services-cli is carried out. Is it safe to be closed? @lnielsen @fenekku

**Comment by fenekku** [comment]
Not sure about the relationship with docker-services-cli, but records-permissions and communities have both made the switch to pytest, so it can be closed.
