### ISSUE TITLE
additional_descriptions not showing formatting

### ISSUE THREAD

**Issue by paolap** [inveniosoftware/invenio-app-rdm#1942]
Package version (if known): v10 (but also previous versions)

## Describe the bug
In the deposit form you can add formatting like new lines, lists etc.,  to the additional description text, but these are not rendered in the record landing page.

## Steps to Reproduce
1. Fill in additional description with some formatting
2. publish draft
3. check landing page, it won't show formatting
4. edit record again, formatting is still showing correctly in the deposit form

## Deposit form screenshot
<img width="919" alt="Screen Shot 2022-10-19 at 9 07 49 am" src="https://user-images.githubusercontent.com/4155949/196554879-e0f2d693-f4e2-477c-b419-7e21d78bafcf.png">

## Current behaviour
<img width="958" alt="Screen Shot 2022-10-19 at 9 09 06 am" src="https://user-images.githubusercontent.com/4155949/196554896-02277730-7e26-4703-a42a-0c673bf60081.png">

## Expected behavior
<img width="943" alt="Screen Shot 2022-10-19 at 9 08 19 am" src="https://user-images.githubusercontent.com/4155949/196554886-1bf5eef9-d702-4f90-a413-4e04d7d7498e.png">

## Additional context
The issue is in how the additional descriptions are retrieved in 
../invenio_app_rdm/records/details/description.html

```code
{{ show_add_descriptions(record.ui.additional_descriptions) if record.ui.additional_descriptions }}
```
this seems to pass the `description` string without the html formatting.

Changing this to:

```code
{% if record.ui.additional_descriptions %}
  {% set add_descriptions = metadata.get('additional_descriptions') %}
  {{ show_add_descriptions(add_descriptions) }}
{% endif %}
```
and adapting the macro in ../invenio_app_rdm/records/macros/detail.html,
so the title is showing correctly, produces the expected behaviour

```code
{% macro show_add_descriptions(add_descriptions) %}
  {% for add_description in add_descriptions %}
  <section id="additional-description-{{loop.index}}" class="rel-mt-2" aria-label="{{ _( add_description.type.title_l10n ) }}">
    <h2>{{add_description.type.title.en }} <span class="text-muted language">{{ '(' + add_description.lang.title.en + ')' if add_description.lang }}</span></h2>
    <p>{{ add_description.description | sanitize_html() | safe}}</p>
  </section>
  {% endfor %}
{% endmacro %}
```

**Comment by ajj11685** [comment]
Even with the fix it doesn't display tables correctly (either by using the rich text box or via the API)

**Comment by max-moser** [comment]
> Even with the fix it doesn't display tables correctly (either by using the rich text box or via the API)

This is likely due to the elements being stripped out by the [`bleach`](https://pypi.org/project/bleach/) HTML sanitizing library.
Allowing a few extra tags in that configuration could enable them to be rendered... Although I think it's unlikely that some formatting (e.g. embedded images) are going to work either way.
As for the tables, I think they just happened to be axed with the other options in order to keep the formatting as simple as possible.

@paolap Thanks a lot for your code snippets, I'll try to turn them into a PR that makes the *additional descriptions* more consistent with the primary *description* field.

**Comment by max-moser** [comment]
And here's a second PR that fixes the user-provided formatting being stripped from the output: https://github.com/inveniosoftware/invenio-rdm-records/pull/1126
