### ISSUE TITLE
Disable Publish button when publishing

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#196]
When clicking on publish and then ok in the modal, we get back to the deposit page for a brief moment while it does the Ajax call and the publish button is clickable then. This is a weird user experience.

**Comment by Glignos** [comment]
<img width="411" alt="Screenshot 2020-10-15 at 10 32 57" src="https://user-images.githubusercontent.com/16304052/96097926-d508a780-0ed1-11eb-816b-ca89a479537a.png">
Was fixed [here](https://github.com/inveniosoftware/react-invenio-deposit/blob/082a53ffea85dac5981fbacb5959183b81875968/src/lib/actionButtons/PublishButton/PublishButton.js#L53)

**Comment by Glignos** [comment]
Was fixed [here](https://github.com/inveniosoftware/react-invenio-deposit/blob/082a53ffea85dac5981fbacb5959183b81875968/src/lib/actionButtons/PublishButton/PublishButton.js#L53)
