### ISSUE TITLE
Deposit form: Inconsistent CKEditor features available in description field

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#1968]
## Describe the bug
The CKEditor fields are not consistent for description/additional description fields. See screenshot.

## Expected behavior

Same CKEditor buttons are available in both editor windows.

## Screenshots (if applicable)

<img width="885" alt="Screenshot 2022-11-04 at 13 58 56" src="https://user-images.githubusercontent.com/1698163/202235819-8d1a8181-827c-400d-96d2-c6199c48a5eb.png">

**Comment by max-moser** [comment]
Related to https://github.com/inveniosoftware/invenio-app-rdm/issues/1942, this should be fixed since the related PRs have been merged.
