### ISSUE TITLE
Don't display download stats of metadata-only records

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#197]
(I am simply transcribing the feedback received when presenting the May release)

This feedback was coming from the worry of an attendee that a record without attached files would not convey its usefulness well. People would see 0 downloads and assume it's not worthwhile, while it may actually be a case where the files were not deposited but the depositor is amenable to sharing them on a case by case basis (just don't want to upload the files in InvenioRDM).

I don't know if there are alternatives to hiding the stats, but it is the feedback that was given by the attendee.

**Comment by lnielsen** [comment]
Tracked in https://github.com/inveniosoftware/product-rdm/issues/13
