### ISSUE TITLE
`View all versions` does not filter properly

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-rdm#1974]
## Describe the bug

`View all versions` facet of the records search does not return expected results

## Screenshots (if applicable)
![Screenshot 2022-11-22 at 10 10 29](https://user-images.githubusercontent.com/38131488/203273257-2700af7e-8372-436f-a3a3-629deb98eb96.png)

**Comment by alejandromumo** [comment]
Previous issue was the toggle not having any type of effect on the search. 

The issues does not persist anymore.
