### ISSUE TITLE
Upgrade containerised instance 

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/invenio-app-rdm#1983]
At the moment there is no "easy way" to run an upgrade in containeraised instance. 
We would need to hook into the different containers and update the dependencies and also run the alembic upgrades and/or upgrade scripts if any.

**Comment by kpsherva** [comment]
misunderstanding in a scope of the task. Initially considered as containers failing due to missing DB table, however the issue was created for upgrading between versions, which is not needed, since the developer can run the upgrade  recipe inside the container
