### ISSUE TITLE
Fix ADMIN_EMAIL_RECIPIENT not picked up

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#2002]
This config variable is located in app-rdm
- Should it be here? If the implementation is zenodo specific (it is used for file integrity checks), then it should be moved to zenodo-rdm/site folder.
- If not, it should be renamed to `APP_RDM_...` so it can be picked up (also overwritable). 
- Extra: should it default to `MAIL_DEFAULT_SENDER` if not present?
- Tests: currently the task is being tested using `app.config[]=`, so the task is properly tested but the config loading won't be tested.

**Comment by ppanero** [comment]
@alejandromumo could you shed some light on the first point? just to know how to proceed

**Comment by alejandromumo** [comment]
> Should it be here? If the implementation is zenodo specific (it is used for file integrity checks), then it should be moved to zenodo-rdm/site folder.

It is used for file integrity checks which are part of app-rdm now. 

> If not, it should be renamed to APP_RDM_... so it can be picked up (also overwritable).

Agree with the naming convention.

> Extra: should it default to MAIL_DEFAULT_SENDER if not present?

I think flask-mail does this by default. However we can / should check

> Tests: currently the task is being tested using app.config[]=, so the task is properly tested but the config loading won't be tested.

I agree that we should also test that the config is loaded. We can test wether the e-mail was sent by loaded config or the default one.
