### ISSUE TITLE
deposit: removing first date element no longer possible

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-rdm#2028]
1. Go to the deposit page.
2. Scroll down to Dates field
3. click the "X" button - no action is visible in the interface, no error raised, no feedback to the user
![Screenshot 2023-01-19 at 18 07 05](https://user-images.githubusercontent.com/38131488/213512937-4893a6c0-d51c-4d24-89a5-6f3bd3c9c75e.png)

Expected:
The button should be either disabled (if minimum one date is required - to be verified) or it should remove the first array element after clicking

**Comment by ppanero** [comment]
Cannot reproduce, in the video bellow there is what I tried. Did I understand it correctly?

https://user-images.githubusercontent.com/6756943/213721473-73b746d9-6333-4dcd-94dc-312a39ffe19d.mov

**Comment by ppanero** [comment]
This error is introduced in:
- invenio-app-rdm==11.0.0.dev6

The issue comes from the overridable date.

**Comment by ppanero** [comment]
> The button should be either disabled (if minimum one date is required - to be verified) or it should remove the first array element after clicking

Is "back to how it was before - not showing an item unless the user clicks add" an option?
I can see we have both cases:
- not shown: titles, funding, creators, contributors
- shown: alternative identifiers, related works 
while I do understand funding, creators, contributors to not be shown by default because it is a modal. Then should we also make titles shown by default? or actually "hide" the identifiers/works and dates too? (this would also minimize the deposit form lenght. And having the "+ Add" button makes it quite clear to me.

The draft PR is hiding the dates field by default.

**Comment by kpsherva** [comment]
I think we should make it work the same way as it was before introducing the regression.
I agree there is a lack of consistency between the fields you've listed, however I am hesitating to try to remove the inconsistency, because maybe it was on purpose?
I remember the first element of dates array being shown by default (and empty) but it was possible to remove by clicking "x". I think we want to revert to that.

**Comment by jrcastro2** [comment]
The `showEmptyValue` is enforcing that an empty value is always present. See code [here](https://github.com/inveniosoftware/react-invenio-forms/blob/d66bbf037ad100fdbf6e71d21c622d36a7b6396a/src/lib/forms/ArrayField.js#L46-L48) where it is always enforcing it.

When I first implemented it ,I had in mind that it has to be required, however I understand now that we should be able to remove the empty value. 

Maybe it's worth to differentiate between `showEmptyValue` that will just prefill the field with an empty object and another attribute (maybe called `required`) that will not allow to delete the value, to be used when the field is mandataroy. 

 I think that  setting the value to `false`, it will just remove the empty value, the fix probably has to be done in https://github.com/inveniosoftware/react-invenio-forms/blob/d66bbf037ad100fdbf6e71d21c622d36a7b6396a/src/lib/forms/ArrayField.js

**Comment by ppanero** [comment]
@jrcastro2 Thanks! That matches the behavior I've seen. I've bootstrapped again app-rdm 11.0.0.dev5 and the date field is not present. So the PR, fixes the regression (**hide the field by default**). Then the question is @kpsherva: Should we implement the difference between `showEmptyValue` and `required` that Javier mentioned?
