### ISSUE TITLE
UI, landing page: remove record from a community

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#2049]
Design UI/UX for removing a record from a community (confirm action modal?), taking into account possible multiple communities in the design (e.g. removing 3 communities at a time).

The current Zenodo implementation is:

![](https://user-images.githubusercontent.com/1814661/180170937-0bdbbc5a-d0d1-4480-aeec-36c928821ecf.png)

The backend support for this action is implemented by https://github.com/inveniosoftware/invenio-rdm-records/issues/1163

**Comment by jennur** [comment]
# Layout suggestions

## Community management modal (removal)
![community-management_version-1_closed](https://user-images.githubusercontent.com/21052053/215427090-951a9895-49cd-43cc-bafa-627a44ad2ece.png)

![community-management_version-1_open](https://user-images.githubusercontent.com/21052053/215427106-17e408ae-353e-4692-8b78-7e82057f4aec.png)

![community-management_version-1_open-popup](https://user-images.githubusercontent.com/21052053/215427103-be659f0c-f351-4a90-98e9-9e34adf6a7f0.png)


## Community management in sidebar (removal + approval https://github.com/inveniosoftware/invenio-communities/issues/873)
![community-management_version-2](https://user-images.githubusercontent.com/21052053/215427643-cee48b88-4b03-4d9e-a801-43259616761c.png)

**Comment by jennur** [comment]
## Comments (discussed irl)

- Test with cancel-action as well
    - Colored buttons preferred (if we keep buttons)
- Too many buttons for the actions-section (if we keep the modal)
    - Maybe the button can be in header 
        - Need to align on multiple communities layout (do we keep the header?)
- Include "add community" in both layout suggestions

**Comment by jennur** [comment]
## Updated buttons layout
![community-management_buttons](https://user-images.githubusercontent.com/21052053/215519056-cbaadfeb-145f-4ac7-b949-0e48997f7765.png)


## Updated dropdown layout
![community-management_dropdown](https://user-images.githubusercontent.com/21052053/215518034-cbd0949c-d6f7-4ad9-ac0d-a105c6443f0d.png)
