### ISSUE TITLE
Installation error wile deploying may-rdm

### ISSUE THREAD

**Issue by cfgamboa** [inveniosoftware/invenio-app-rdm#205]
Hi
While executing  invenio-cli containerize --pre as a part of the may release installation I got different errors shown in the file attached
[may-rdm-release.txt](https://github.com/inveniosoftware/invenio-app-rdm/files/4814192/may-rdm-release.txt)

**Comment by ppanero** [comment]
This has been fixed. It was the problem with `less-loader` release. For now the solution has been to pin the dependency. A new issue was opened by @zzacharo to investigate further in next releases.
