### ISSUE TITLE
Landing page: record in multiple communities

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-rdm#2061]
## Mockup changes

- The tabs are removed
- The communities list in the sidebar remains, but have a management-dropdown for submitting (request) to a community and pending submissions.

### Sidebar segment with dropdown
<img width="261" alt="Screenshot 2023-02-22 at 10 23 30" src="https://user-images.githubusercontent.com/21052053/220577748-3e02f3bb-d87f-4d66-b0b0-ba483be8490a.png">

### Request communities modal (same as in the deposit form - reuse)
<img width="592" alt="Screenshot 2023-02-22 at 10 23 41" src="https://user-images.githubusercontent.com/21052053/220578117-8986231a-87ea-4c9e-aa61-fe9a55f0b2f7.png">

### Pending submissions
<img width="633" alt="Screenshot 2023-02-22 at 10 23 55" src="https://user-images.githubusercontent.com/21052053/220578224-1a22a31e-9ac0-45dd-b8f5-cbbedcf76f1d.png">

### Full communities list
<img width="664" alt="Screenshot 2023-02-22 at 10 23 59" src="https://user-images.githubusercontent.com/21052053/220578489-ebbe6163-4865-43e0-ab60-9cb667b60ca8.png">

**Comment by jennur** [comment]
## Mockup changes

- The tabs are removed
- The communities list in the sidebar remains, but have a management-dropdown for submitting (request) to a community and pending submissions.

### Sidebar segment with dropdown
<img width="261" alt="Screenshot 2023-02-22 at 10 23 30" src="https://user-images.githubusercontent.com/21052053/220577748-3e02f3bb-d87f-4d66-b0b0-ba483be8490a.png">

### Request communities modal (same as in the deposit form - reuse)
<img width="592" alt="Screenshot 2023-02-22 at 10 23 41" src="https://user-images.githubusercontent.com/21052053/220578117-8986231a-87ea-4c9e-aa61-fe9a55f0b2f7.png">

### Pending submissions
<img width="633" alt="Screenshot 2023-02-22 at 10 23 55" src="https://user-images.githubusercontent.com/21052053/220578224-1a22a31e-9ac0-45dd-b8f5-cbbedcf76f1d.png">

### Full communities list
<img width="664" alt="Screenshot 2023-02-22 at 10 23 59" src="https://user-images.githubusercontent.com/21052053/220578489-ebbe6163-4865-43e0-ab60-9cb667b60ca8.png">
