### ISSUE TITLE
Add `User.preferences.locale` (and optionally `.timezone`)

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-app-rdm#2069]
- Make sure to integrate well with [the relevant I18N code](https://github.com/inveniosoftware/invenio-i18n/blob/be68607e702cb34638f6dd07fda3acab365fe644/invenio_i18n/selectors.py#L54)
- See if we could extend the schema in `invenio-accounts` directly, since I18N is globally used throughout Invenio, and is not an RDM-specific feature.
- For UI we should add a dropdown for selecting the locale/language in the user profile settings page
- Related to localizing [notifications](https://github.com/inveniosoftware/invenio-app-rdm/issues/2065) (via picking the appropriate template depending on the user's locale)

--- 

If time permits and the task looks simple enough we should also have a look into also adding a `User.preferences.timezone` field and update [the timezone selector in `invenio-i18n`](https://github.com/inveniosoftware/invenio-i18n/blob/be68607e702cb34638f6dd07fda3acab365fe644/invenio_i18n/selectors.py#L74-L76) to use it. The points from above apply to this field as well.

**Comment by TLGINO** [comment]
Please ignore failing tests for now :)
(Will fix once I figure out which module needs to be merged first, as there's lots of co-dependency)

**Comment by TLGINO** [comment]
Resume of discussion regarding locales / default locales:

BABEL_DEFAULT_LOCALE dictates the default Locale for the application.
If the locale is not in the list of supported languages, an error will be raised.
'en' is the default value for BABEL_DEFAULT_LOCALE and is synonymous of 'en_US'.
