### ISSUE TITLE
repo: investigate technologies for central repository for RDM documentation

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#21]
Move Wiki instruction to central RDM documentation repository.

- [x] Find technology for it (mkdocs, docosaurus, jekyll, etc.)

- [x]  Move current Wiki.

**Comment by fenekku** [comment]
Documentation is now here: https://github.com/inveniosoftware/docs-invenio-rdm
and rendered here: inveniordm.docs.cern.ch/

Deactivation of this wiki is left but is not a big deal.
