### ISSUE TITLE
"Additional details" section renders an empty table

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-rdm#2177]
- [ ] Renders empty table (no content)
- [ ] Additional details has two horizontal lines

![](https://codimd.web.cern.ch/uploads/upload_b02b56a2c9fb5034803c7b6cf0c2e65a.png)

**Comment by tmorrell** [comment]
I have not been able to reproduce this behavior on v12dev2. Additional details and the box/line doesn't show up when no metadata is present. This section has also been reformatted, so every indication is this has been fixed already.
