### ISSUE TITLE
[EPIC] Publish new version record

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#219]
- Refactor PID management to facilitate working with them from a service/resource_unit point of view
- Implement record versioning
- ...

*Notes*
- Metadata only changes do not change version but revision? --> we check, if files are the same we only allow revision (sort of both user and client)
    - Fail, users do not understand "revision"
    - Lose changes
- Previous version updates not allowed, always start from latest

**Comment by fenekku** [comment]
Closed via https://github.com/inveniosoftware/invenio-drafts-resources/pull/13

**Comment by ppanero** [comment]
@fenekku this epic is meant for next month (tho it was started in July). I need to put more details but is mainly for the PIDstore wrapper + versioning

**Comment by fenekku** [comment]
Thought so too. I've placed it in August yesterday and we can add details to it.
