### ISSUE TITLE
community-about: tab misbehaves when clicked

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#2217]
Package version (if known): latest

## Describe the bug
In a community details page, clicking on the about tab, redirects to search tab.

## Expected behavior
Display the about page
## Screenshots (if applicable)
![Screenshot 2023-05-12 at 14 51 46](https://github.com/inveniosoftware/invenio-app-rdm/assets/22594783/0de4dd1a-c0de-4429-9424-9c39b4f134b4)

## Additional context

Found https://zenodo-rdm-qa.web.cern.ch/communities/covid-19?q=&l=list&p=1&s=10&sort=newest

**Comment by psaiz** [comment]
I've done a new installation from master on my localhost. The `about` seems to be working as expected. @zzacharo mentioned that this could be due to some other plugin. Let's see if we can reproduce it...

**Comment by psaiz** [comment]
The github version looks very similar. There is one interesting thing in the site/zenodo_rdm/config.py:

```
psaiz@mac-psaiz zenodo-rdm % cat  site/zenodo_rdm/config.py |grep -C 3 about
}

REDIRECTOR_RULES = {
    "redirect_communities_about_legacy": {
        "source": "/communities/about/<id>/",
        "target": communities_detail_view_function,
    },
    "redirect_communities_search_legacy": {
        "source": "/collection/<type>",
        "target": search_view_function,
    },
    "redirect_collections_about": {
        "source": "/collection/user-<id>",
        "target": communities_detail_view_function,
    },
--
```
The target looks suspicious. Let me check in the standard invenio

**Comment by psaiz** [comment]
https://github.com/zenodo/zenodo-rdm/pull/383
