### ISSUE TITLE
The setting of upload files size limit doesn't work

### ISSUE THREAD

**Issue by Autumn-Roy** [inveniosoftware/invenio-app-rdm#2219]
Package version (if known): <version>
9.1.0

## Describe the bug
It doesn't work when setting the limit of upload files.

## Steps to Reproduce
1.Check the limit of upload file is 10G. which is default, it is shown when I setup the Invenio-RDM
2.Follow the docs, https://inveniordm.docs.cern.ch/customize/upload_limits/ , add two parameter in invenio.cfg
FILES_REST_DEFAULT_MAX_FILE_SIZE = "40GiB"
FILES_REST_DEFAULT_QUOTA_SIZE = "40GiB"
3.Rebuild docker and restart containers
`invenio-cli containers build
invenio-cli containers start --no-demo-data`
4.Check the limit of upload file is also 10G.

![image](https://github.com/inveniosoftware/invenio-app-rdm/assets/52824328/42be9b49-f2b8-416a-bef3-1602865c4ac8)

## Expected behavior
The limit of upload files changed to 40G

## Additional context
1.I try to change the parameter in invenio.cfg as follow:
FILES_REST_DEFAULT_MAX_FILE_SIZE = "40GB"
FILES_REST_DEFAULT_QUOTA_SIZE = "40GB"
But it doesn't work anymore.
Is there I miss some setting?

**Comment by tmorrell** [comment]
To adjust the limit in the deposit form, you need to add 

```
APP_RDM_DEPOSIT_FORM_QUOTA = {
    "maxFiles": 100,
    "maxStorage": 40000000000,
}
```

to invenio.cfg. I'll add that to the documentation.

**Comment by Autumn-Roy** [comment]
Thanks, the upload limit was changed successfully.
I have another problem is the uploading will be broken as content too large, even the size of a file is not reach the limits. But this situation only appear in `containers` mode. When I use `local` mode, it disappears.

For example, I have change the `docker/nginx/conf.d/default.conf` as below:
`  location / {
    uwsgi_pass ui_server;
    include uwsgi_params;
    [......]
    # Max upload size (except for files) is set to 100mb as default.
    client_max_body_size 100m;
  }
  ## Most API
  location /api {
    uwsgi_pass api_server;
    include uwsgi_params;
    [......]
    # Max upload size (except for files) is set to 100mb as default.
    client_max_body_size 100m;
  }
  location ~ /api/records/.+/draft/files/.+/content {
    gzip off;
    uwsgi_pass api_server;
    include uwsgi_params;
    [......]
    # Max upload size for files is set to 50GB (configure as needed).
    client_max_body_size 50G;
  }
`
And add the lines to invenio.cfg:
`APP_RDM_DEPOSIT_FORM_QUOTA = {
    "maxFiles": 100,
    "maxStorage": 40000000000,
}`

When I run server with `invenio-cli run`,  I can upload a 10GB filel; But if I run server with `invenio-cli containers start --no-demo-data`, the progress will break at 2% and F12 check the errer,
![image](https://github.com/inveniosoftware/invenio-app-rdm/assets/52824328/8013caee-e63c-4183-9af3-e6bab48aec79)
