### ISSUE TITLE
administration: add user management panel

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-rdm#2232]
The end goal of this task is to have the administration panel for the user management. This task is considered completed when below steps are achieved:

- [x] check on how the invenio-administration module works
- [x] add user list page to the administration panel - find and use the search endpoint (and as a consequence resource, since resource can be used in invenio-administration) which provides all the users so that administrator can see all the users. Things to consider: is the endpoint displaying all the information? Is it hiding any users? do we need special permissions to make all the users information available to the administrator. HINT: superuser != administrator. These are important points and should be discussed with the team before starting the implementation
- [x] implement the list view
- [x] implement the user details view
- [x] add a feature flag `APP_RDM_USER_ADMINISTRATION` which will conditionally display or hide these views in the administration panel (similarly to `COMMUNITIES_ADMINISTRATION_DISABLED`)

IMPORTANT! The scope of this task includes only displaying the available information - do not add any new fields visible in the mockup to the user or any actions (buttons).  These steps will be added later as next iteration.

List view: 
![Screenshot 2023-05-25 at 15 45 29](https://github.com/inveniosoftware/invenio-app-rdm/assets/38131488/7fe520e7-c51c-499c-9b83-3b36c3f46e44)

Details view
![Screenshot 2023-05-25 at 15 46 12](https://github.com/inveniosoftware/invenio-app-rdm/assets/38131488/58a7eaac-fa41-4fdf-947b-09c48f784ee1)

**Comment by psaiz** [comment]
https://github.com/inveniosoftware/invenio-users-resources/pull/82 addresses the first four checkboxes. Let me take a look at the last one before moving the ticket to the next column

**Comment by psaiz** [comment]
Ready for the second round of the review. Note that this is still a draft
