### ISSUE TITLE
New Version Text Above/Below Title

### ISSUE THREAD

**Issue by sharpattack** [inveniosoftware/invenio-app-rdm#2257]
## Is your feature request related to a problem? Please describe.
There is interest in making the "newer version" message more prominent. The banner message may not be enough to point out to users that there is a newer version of the record available. 

## Describe the solution you'd like
In addition to, or instead of, the banner message announcing there is a newer version available, add similar text above or below the title. 

As an example, protocols for systematic reviews (not scoping reviews) are generally registered in Prospero. Below is a link to an example of a record that is not the most current version of the protocol.

https://www.crd.york.ac.uk/prospero/display_record.php?RecordID=17927&VersionID=28868

## Describe alternatives you've considered
None, ideas are welcome!

## Additional context
Our users are uploading their Scoping Review protocols to our instance, and it is quite normal for those protocols to be updated a few times.

## Screenshot
<img width="1584" alt="Screenshot 2023-06-13 at 11 11 26 AM" src="https://github.com/inveniosoftware/invenio-app-rdm/assets/8138663/63af3742-28ae-4c53-8ed9-f5e3d65ec528">

**Comment by fenekku** [comment]
I think @sharpattack PR in our instance is actually better than moving those and more general: 

![image](https://github.com/inveniosoftware/invenio-app-rdm/assets/1932651/6e343438-d869-4d38-ae18-78be9a76038a)

If you are interested / find that people don't identify the new version well, let us know. I will close this for now.
