### ISSUE TITLE
Configure configuration variable to disable user local login forms

### ISSUE THREAD

**Issue by cfgamboa** [inveniosoftware/invenio-app-rdm#227]
The idea is that if user local login  is not needed or supported in the invenioRDM instance it can be disabled (forms) by setting a variable like USER_LOCAL_LOGIN=False
There are related features the are configured using the variables like SECURITY_REGISTRABLE.

So the forms are not longer presented:

It seems that the code needed to implement this change is here:
 (https://github.com/inveniosoftware/invenio-oauthclient/blob/085cf705f616b699e79e29d34576131d332619d8/invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/login_user.html#L21) 
(https://github.com/inveniosoftware/invenio-accounts/blob/4ad610555d10f077f00c2a9e6814218ca32e27cb/invenio_accounts/templates/semantic-ui/invenio_accounts/login_user.html#L2)

Thank you.

Carlos

**Comment by fenekku** [comment]
Unstaling it because at least 2 partners want this.

**Comment by lnielsen** [comment]
Fixed in may iteration
