### ISSUE TITLE
i18n workflow: translation files (.mo) are not being created

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#230]
They are all marked as fuzzy:

> `#, fuzzy` line above the msgid line, and are the result of a merge where a message is deemed slightly changed from the previous version. A message marked as fuzzy is supposed to be looked at by a human to make sure the translation doesn't need updating, after which the human translator removes that flag.

And therefore when the catalog is compiled they are skipped:

```
catalog invenio_app_rdm/translations/tr/LC_MESSAGES/messages.po is marked as fuzzy, skipping
```

Need to find out where is the fuzzy flag being added (transifex?) and fix the workflow (or -f the compilations in travis).

Why?

Somewhere along the way babel changed. From [their docs](http://babel.pocoo.org/en/latest/cmdline.html) it is said:
```
  -f, --use-fuzzy       also include fuzzy translations (default False)
```

**Comment by baldemir** [comment]
On my local I was using -f to make it work. When I checked fuzzy is added to translation files firstly during: `python setup.py extract_messages` So i don't think it's related to Transifex. [here](http://babel.pocoo.org/en/latest/api/messages/catalog.html) it shows default value for fuzzy in Catalog is true. We may want to change it and assign false for fuzzy parameter. Or -f looks like the solution.

**Comment by lnielsen** [comment]
Still an issue.

Tasks:
- Go through all release Invenio modules used in InvenioRDM and ILS

**Comment by rekt-hard** [comment]
when extracting messages via `python setup.py extract_messages`, the header will (always?) contain a `#, fuzzy`  entry
![Screenshot from 2021-11-15 16-33-24](https://user-images.githubusercontent.com/72449192/141809344-d87b2d24-2c3b-4dde-9749-9f46d3639941.png)

when updating catalogs via `python setup.py update_catalog`, the headers of the updated .po files will not contain this fuzzy entry in the header. thus, there is no issue with compiling the catalog with `python setup.py compile_catalog`.

if, for any reason, a fuzzy entry ends up in the header of a .po file for a language, running `python setup.py compile_catalog -f` would ignore the fuzzy entry and compile the catalog successfully.

solution could be to add `use-fuzzy = True` to the `[compile_catalog]` command in `setup.cfg`

**Comment by mb-wali** [comment]
closing since an issue inveniosoftware/invenio-i18n#103 is created to add `use-fuzzy = True` for all the repos.
