### ISSUE TITLE
v12 release notes

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-rdm#2343]
MERGE OTHER ISSUE IN HERE: https://github.com/inveniosoftware/docs-invenio-rdm/issues/536

- check all closed issues/PRs in the board
- features that might contain schema changes
  - access requests: https://github.com/inveniosoftware/invenio-rdm-records/pull/1392
  - safe moderations
  - record and user deletion
- programmatic API breaking changes
  - the RoleNeed now uses the role id instead of name
  - Python 3.8 will be required (because of `invenio-rdm-records`)
- have a look to this: https://github.com/inveniosoftware/invenio-app-rdm/issues/1914

## Documentation

- overridable: document that the JavaScript block must contain `{{ webpack['overridable-registry.js'] }}` as [here](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/javascript.html#L12) (Uni Munster)
- notifications
  - https://github.com/inveniosoftware/invenio-app-rdm/issues/2204
  - https://github.com/inveniosoftware/docs-invenio-rdm/issues/558
- access requests
  - the data model has changed in a few ways (e.g. allowing only a single record owner) – c.f. the PR description of https://github.com/inveniosoftware/invenio-rdm-records/pull/1306#issue-1707170959
- user moderation
  - (EPIC) https://github.com/inveniosoftware/invenio-app-rdm/issues/2290
  - New configs were added:
    - (`invenio-accounts`)` ACCOUNTS_DEFAULT_USERS_VERIFIED` 
    - `invenio-rdm-records` `RDM_SEARCH_SORT_BY_VERIFIED` 
  - New [db migration](https://github.com/inveniosoftware/invenio-accounts/blob/master/invenio_accounts/alembic/037afe10e9ff_add_user_moderation_fields.py) was added to `invenio-accounts`
  - need to update the setup command
    ```bash
     $ invenio roles create administration-moderation
     $ invenio access allow administration-moderation role administration-moderation
     $ invenio roles add <email> administration-moderation
    ```
- record and user deletion
  - record deletion will require a new vocabulary type (`removalreasons`), as outlined in the PR description https://github.com/inveniosoftware/invenio-rdm-records/pull/1386#issue-1823962069
- https://github.com/inveniosoftware/docs-invenio-rdm/issues/532
- previewer
  - [PR](https://github.com/inveniosoftware/invenio-previewer/pull/180) from Dan with new config var 
`PREVIEWER_TXT_MAX_BYTES`.
  - [PR](https://github.com/inveniosoftware/invenio-previewer/pull/179)
- invenio-github:
  - (EPIC) https://github.com/inveniosoftware/invenio-app-rdm/issues/2249 - first documentation provided in the issue
- allow edit of published files (Do we want to document that?) - See [here](https://github.com/inveniosoftware/invenio-rdm-records/commit/a3bb52bfa8b7cc055d2a3a5d0e2ba66cec58190c#diff-638be557f5d538de83a96ebf1b51f30fe0f21f8b5e005ac849b4ca32f3470fa6R525)
- badges (added in February but not documented):
  - https://github.com/zenodo/zenodo-rdm/pull/253
  - https://github.com/inveniosoftware/invenio-app-rdm/pull/2145
  - TL;DR : in the landing page, we added support to render badges in a new box named `External resources`. This depends on a set of conditions to be met (e.g. the record having related identifiers that match a Github release). This is extensible already and is being used in [Zenodo-RDM](https://github.com/zenodo/zenodo-rdm/blob/master/invenio.cfg#L406)
- stats
  - in case someone started to use the new `invenio-stats` already, v4 comes with breaking changes: the default stat indices are monthly and not anymore daily, and the templates/mappings have a new field `updated_timestamp`. A recipe to manually upgrade is here: https://github.com/CERNDocumentServer/cds-rdm/issues/108
- rendering of formulas via [MathJax](https://www.mathjax.org/) on record landing pages:
  - set the config variable `THEME_MATHJAX_CDN` to e.g. `"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"` (cf. [Zenodo](https://github.com/zenodo/zenodo-rdm/blob/88c4b967fac720f6a3bc25b6e586f8bf350ce5a1/site/zenodo_rdm/config.py#L405))
  - requires an additional `default-src` in the CSP header (`APP_DEFAULT_SECURE_HEADERS`) for the domain name (e.g. `cdnjs.cloudflare.com`
- granting access to the record to users/groups: https://github.com/CERNDocumentServer/cds-rdm/issues/109
   - existing endpoint for managing grants `/access/users` renamed to `/access/grants`
   - created new endpoints `/access/users` and `/access/groups` for managing user and groups grants separately
   - changed old implementation of `create_grant` to be able to bulk create multiple grants `bulk_create_grants `

**Comment by kpsherva** [comment]
https://github.com/inveniosoftware/invenio-rdm-records/pull/1433/files#diff-e22bdb78803ca92e6132b3900d02e197ff63b97add0575ef7a5e6dfcc0738768R65

**Comment by ntarocco** [comment]
other releated issue: https://github.com/inveniosoftware/invenio-app-rdm/issues/2343

**Comment by fenekku** [comment]
note to self: went through all of those

Remaining:
- Previewer section
- Github integration section
- Go through the CHANGES.md of all repos

**Comment by fenekku** [comment]
closed via https://github.com/inveniosoftware/docs-invenio-rdm/pull/681
