### ISSUE TITLE
stats: update changed record usage statistics on a schedule

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-app-rdm#2348]
Record usage statistics are currently only updated on reindexing. Reindexing only happens on specific events that usually modify the record, e.g. (edit a record and publish changes, accept in a community, etc.).

We should have a schedule Celery beat task that:

1. queries statistics events to extract which records have received views/downloads
2. schedules a bulk reindexing for these record IDs

See also [old implementation in Zenodo](https://github.com/zenodo/zenodo/blob/407cab4248828da355b1fe76d9c1b56fc30b5efe/zenodo/modules/stats/tasks.py#L42).

**Comment by ntarocco** [comment]
Fixed [here](https://github.com/inveniosoftware/invenio-app-rdm/pull/2367)
