### ISSUE TITLE
global: support for python 3.7

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#24]
This would require:
- Changing base docker file image in `cookiecutter-invenio-rdm`
- Adding support through the modules? or just `invenio-cli`

**Comment by alexsdutton** [comment]
I've just tested installing InvenioRDM via invenio-cli with Python 3.7. The whole terminal session is at https://gist.github.com/alexsdutton/30f20437f6d3832ea6f1b2fa78092e63.

Tested versions summary:

* Python 3.7
* invenio-cli 0.14.2
* invenio-app-rdm 0.10.1
* inveniosoftware/centos8-python:3.7 46f21d656dbe

I've also uploaded the full `Pipfile` and `Pipfile.lock` files and the output of `pip freeze` to the gist, in case that's useful later down the line.

This all seemed to work, and I've clicked around the resulting web interface quite happily.

I'd say this is good to mark resolved :-).

**Comment by fenekku** [comment]
@alexsdutton Were you able to add a record and was Celery humming along? I remember those 2 things having trouble in Python 3.7+ ... Otherwise, that's great!

**Comment by alexsdutton** [comment]
Ooh, those things I didn't check. Give me a mo…

**Comment by alexsdutton** [comment]
I can confirm that `invenio-cli install && invenio-cli demo` successfully inserts the demo records, and that the worker container starts up successfully :tada:

**Comment by ppanero** [comment]
IIRC `invenio-cli demo` does not use celery, it creates (and indexes) directly. Here https://github.com/inveniosoftware/helm-invenio/tree/master/benchmark there are some instructions on how to run a big indexing task (that uses celery). Otherwise any other job that uses celery would do to, just need to check that it is being called.
