### ISSUE TITLE
UI: separate "My uploads" from all user uploads for Moderators

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-rdm#2432]
Due to permissions set for moderators, the uploads page contains all the uploads, which is confusing in case of Moderator being a regular uploader in the same time. 
We should keep "My uploads" dedicated to only user's content even if they are moderators/superusers

**Comment by fenekku** [comment]
Duplicate of https://github.com/inveniosoftware/invenio-app-rdm/issues/1956 probably.

**Comment by ntarocco** [comment]
Fixed
