### ISSUE TITLE
Inconsistence in url encode using the RestAPI. Requests with decoded urls don't work.

### ISSUE THREAD

**Issue by fabiobatalha** [inveniosoftware/invenio-app-rdm#2530]
Package version (if known): [v12.0.0b2.dev51](https://github.com/inveniosoftware/invenio-app-rdm/releases/tag/v12.0.0b2.dev51)

## Describe the bug
I'm trying to retrieve records using a date range filter. I consider this a bug because the request works fine while using the user interface, but it is not working properly while using the REST API.

This is the request made in the user interface: https://127.0.0.1:5000/search?q=metadata.publication_date:[2022-01-01 TO 2022-12-31]

When doing the same request in the RestfulAPI: https://127.0.0.1:5000/api/records?q=metadata.publication_date:[2022-01-01 TO 2022-12-31]

Invenio returns an erreur : 400 - Error trying to decode a non urlencoded string.

## Steps to Reproduce
1. copy and paste the **decoded** urls in the browser
2. replace with the appropriated date range and ip address

## Expected behavior

* User interface works as expected.
* Restful API fails in encoding the URL returning an error 400.

## Screenshots (if applicable)

User Interface Response (Works)

![image](https://github.com/inveniosoftware/invenio-app-rdm/assets/504142/9814d281-4ab4-4a58-bc8c-1cccc2afe848)

RestAPI Response (FAIL)

![image](https://github.com/inveniosoftware/invenio-app-rdm/assets/504142/3be4d5f6-8c67-41f8-ae25-fd463cf6ff9b)

## Additional context

It is possible to notice that the url is encoded while using the user interface meanwhile the API url keeps decoded.

If I enforce an encoded url for the API, it works fine.

https://127.0.0.1:5000/api/records?q=metadata.publication_date%3A%5B2022-01-01%20TO%202022-12-31%5D

**Comment by ntarocco** [comment]
@fabiobatalha this is related how your browser is displaying the query string in the address bar, and how you copy/paste text in the address bar, see for example [here](https://stackoverflow.com/questions/6395856/why-do-firefox-and-certain-other-browsers-alter-the-url-in-the-address-bar-when).

This is not an issue of Invenio/InvenioRDM.

I am closing this issue, please feel free to re-open it needed.
