### ISSUE TITLE
Set quota form bug

### ISSUE THREAD

**Issue by jennur** [inveniosoftware/invenio-app-rdm#2535]
Reported as part of https://github.com/zenodo/rdm-project/issues/500

I have not been able to reproduce the error:

> For some reason, the set quota fails in this condition: 
go to the administration -> users (any user)
now click on draft -> find the draft -> set quota model
submit. It fails complaining about the notes because it loads the widget/component from the user panel, messing with the params of the record panel. If you refresh the page (React reload) and go directly to the record panel, then it works.

**Comment by ntarocco** [comment]
Fixed
