### ISSUE TITLE
styles: add a footer similar to InvenioRDM

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#256]
## Describe the solution you'd like

Create an improved footer for InvenioRDM.

1. Two layers. Bottom layer darkens the main header color.
2. Notice the shadow in between the two footers (see also #334)
3. Create Jinja template blocks according to screenshot below.
4. Notice link vs text color. Very slight difference.
5. Exact content to be defined, but we could start out with some of the links from http://inveniosoftware.org/products/rdm/

![Screenshot 2020-08-24 at 16 23 32](https://user-images.githubusercontent.com/1698163/91056541-67a16e80-e626-11ea-9d56-00f22dbec76c.png)

![Screenshot 2020-08-24 at 16 21 32](https://user-images.githubusercontent.com/1698163/91056319-1ee9b580-e626-11ea-9487-1368075b83ee.png)

The idea is that it should be easy for user to add menu, logos and text in the footer, custom to each instance.

**Comment by fenekku** [comment]
This is a more detailed version of https://github.com/inveniosoftware/invenio-app-rdm/issues/152 . Will close the latter.
