### ISSUE TITLE
styles: mobile version has many layout faults

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#259]
## Describe the bug

If you reduce the browser window size, you'll see many different layout issues on the frontpage (marked with red arrows in the screeenshots).

## Screenshots (if applicable)

![Screenshot 2020-08-25 at 15 56 55](https://user-images.githubusercontent.com/1698163/91183580-ef04e580-e6eb-11ea-8833-fa07c9f17c3f.png)

![Screenshot 2020-08-25 at 15 57 44](https://user-images.githubusercontent.com/1698163/91183587-f1673f80-e6eb-11ea-9117-3fa80019de74.png)

**Comment by fenekku** [comment]
Linking this issue: https://github.com/inveniosoftware/invenio-app-rdm/issues/170

**Comment by jrcastro2** [comment]
Linking this PR: https://github.com/inveniosoftware/invenio-theme/pull/218
