### ISSUE TITLE
Update award text

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/invenio-app-rdm#2602]
Here the discussion with some screenshots: https://mattermost.web.cern.ch/it-dep/pl/o6epsjmbhiya3m4uuzsff6z1fe

**Comment by jrcastro2** [comment]
Use the `/` to higlight both "award/grant"
For the button use only `Add`

**Comment by ntarocco** [comment]
Related issue to fix: https://github.com/inveniosoftware/invenio-app-rdm/issues/2541
