### ISSUE TITLE
Reindexing isn't fully implemented and users/community members indexing doesn't work

### ISSUE THREAD

**Issue by tmorrell** [inveniosoftware/invenio-app-rdm#2608]
Package version (if known): v12

## Describe the bug
The current reindex commands in rdm-records and rdm-communities don't fully reindex requests and request events. In addition the users, groups, and community members  `bulk_index` commands that were added two years ago don't seem to work. I'm also not sure how to re-initialize the usage stats indexes.

## Steps to Reproduce
1. Set up a normal install, including adding users, communities, and submitting some requests
2. Delete indexes
3. Reindex records and communities
4. See that the requests index is blank.
5. Try to manually reindex users with
```
users_service = current_service_registry.get("users")
users_service.rebuild_index(system_identity)
```
7. See that the users index is blank

## Expected behavior
There should be a recipe for re-indexing all content. A script based approach that works is https://github.com/caltechlibrary/caltechauthors/blob/main/scripts/reindex_more_stuff.py, but this isn't ideal. Requests should probably be included in community reindexing and the users/community members indexing is pretty slow.

**Comment by zzacharo** [comment]
Hey @tmorrell, have you tried using this [command](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/cli.py#L61) ?

**Comment by Samk13** [comment]
@zzacharo I added this and other `rdm` commands in the docs as they are not in the reference yet. 
Please let me know if the documentation for this command is accurate and covers everything needed:
https://github.com/inveniosoftware/docs-invenio-rdm/pull/608

**Comment by zzacharo** [comment]
> @zzacharo I added this and other `rdm` commands in the docs as they are not in the reference yet. Please let me know if the documentation for this command is accurate and covers everything needed: [inveniosoftware/docs-invenio-rdm#608](https://github.com/inveniosoftware/docs-invenio-rdm/pull/608)

Thanks for that! I approved it!

**Comment by tmorrell** [comment]
The cli command should solve the requests issue. I need to test it, but I don't think it will solve the users issue.

**Comment by tmorrell** [comment]
This turned out to be a celery issue. I've added more details into the documentation, and this issue can be closed after merging.

**Comment by kpsherva** [comment]
closing as suggested above
