### ISSUE TITLE
Add standard license - doesn't show all licences

### ISSUE THREAD

**Issue by ghost** [inveniosoftware/invenio-app-rdm#2615]
Package version (if known): https://inveniordm.web.cern.ch -- 2024-03-20

## Describe the bug
In the deposit-form, trying to see all standard licences doesn't work.

## Steps to Reproduce
1. Go to deposit form.
2. Click on "Licenses - Add standard"
3. Click on "All"
4. See only the 25 first licences (3dfx Glide License - Apple Public Source License 1.0)

## Expected behavior

See all licences or a pagination to find the rest.

## Screenshots (if applicable)
![image](https://github.com/inveniosoftware/invenio-app-rdm/assets/74763324/8b2be596-2ece-4c4c-95ec-1feba162c3be)
![image](https://github.com/inveniosoftware/invenio-app-rdm/assets/74763324/fbca17d9-7612-4600-adcb-e0895c1f44ea)

**Comment by tmorrell** [comment]
Yup, it's an annoying issue https://github.com/inveniosoftware/invenio-app-rdm/issues/1375 and https://github.com/inveniosoftware/invenio-app-rdm/issues/2284
