### ISSUE TITLE
api/users - cannot get to next page / page 2

### ISSUE THREAD

**Issue by chriz-uniba** [inveniosoftware/invenio-app-rdm#2616]
Package version (if known): https://inveniordm.web.cern.ch/ (2024-03-20)

## Describe the bug

When logged in as a user, going to https://inveniordm.web.cern.ch/api/users you see the first 10 users. 
Going to "next" (page 2) https://inveniordm.web.cern.ch/api/users?facets=%7B%7D&page=2&size=10&sort=newest
does show the same users.

## Expected behavior

Getting page 2 of the users.

## Additional context

Same happens when using curl (using a auth-token).

**Comment by kpsherva** [comment]
this behaviour is implemented on purpose to limit the possibility of retrieving private data by scripting
