### ISSUE TITLE
Record's description breaks the layout when the tag <pre> is used

### ISSUE THREAD

**Issue by alejandromumo** [inveniosoftware/invenio-app-rdm#2635]
Steps to reproduce:

- Create a draft
- In the description field, use the editor to generate a long description (e.g. copy [this one ](https://zenodo.org/records/10911786))
- Save and publish the record
- Layout is broken:

![image](https://github.com/inveniosoftware/invenio-app-rdm/assets/21204744/e268b2de-0469-419b-8851-8056947ec892)

I believe TinyMCE adds the tag, and the [parent div styling](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/description.html#L17) is not sufficient

Adding the style `white-space: pre-wrap` directly to the `pre` tag does the trick, but it's not the fix for the issue.

**Comment by Samk13** [comment]
Would setting `overflow-x: auto;` on the parent div be an acceptable solution?
