### ISSUE TITLE
Licenses Missing in New InvenioRDM v12 Instance Setup

### ISSUE THREAD

**Issue by Samk13** [inveniosoftware/invenio-app-rdm#2658]
Package version (if known): V12.0.0b3.dev12

## Describe the bug
New instances of InvenioRDM v12 are missing license information. This causes submission errors with the message `Invalid value cc-by-4.0.`.

## Steps to Reproduce
1. Initiate a new instance of InvenioRDM v12.
2. Setup a minimal record.
3. Attempt to submit the record.
4. Encounter the error: `Invalid value cc-by-4.0.`

## Expected behavior
Licenses should be included in the setup without errors.

## Screenshots (if applicable)
![image](https://github.com/inveniosoftware/invenio-app-rdm/assets/36583694/34471097-2c8b-4d50-945a-f951bead6c42)
![image](https://github.com/inveniosoftware/invenio-app-rdm/assets/36583694/21afbfd4-5a81-42d4-90af-d28d347dae84)

## Additional context
This issue is related to recent changes [here](https://github.com/inveniosoftware/invenio-rdm-records/pull/1721).

- It seems necessary to either update the cookie cutter repository to include the latest licenses CSV dialect by default, which can be done by replacing [old csv](https://github.com/inveniosoftware/cookiecutter-invenio-rdm/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/app_data/vocabularies/cc_licences.csv) with the [new one](https://github.com/SotosTsepe/invenio-rdm-records/blob/eafd3eed634d5e142810d1fabd20548881a23a7b/invenio_rdm_records/fixtures/data/vocabularies/licenses.csv) as the parsing seems to not be able to pick up the [old dialect](https://github.com/SotosTsepe/invenio-rdm-records/blob/eafd3eed634d5e142810d1fabd20548881a23a7b/invenio_rdm_records/fixtures/vocabularies.py#L74).

- Or we can read a larger sample size to improve detection like here:
```diff
-dialect = csv.Sniffer().sniff(fp.read(1024))
+dialect = csv.Sniffer().sniff( fp.read(4096))
```
Or do both solutions, Input is appreciated!

**Comment by ptamarit** [comment]
The fact that the CSV is not properly parsed by GitHub is not a very good sign neither.
Would it make sense to switch to commas as done in Zenodo? https://github.com/zenodo/zenodo-rdm/pull/832

**Comment by Samk13** [comment]
I would vote to remove the [CSV override](https://github.com/inveniosoftware/cookiecutter-invenio-rdm/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/app_data/vocabularies/cc_licences.csv) in the cookie cutter to default to the original CSV, as its redundant now. 
It seems unnecessary to maintain it in `app_data` when it's already available [here](https://github.com/SotosTsepe/invenio-rdm-records/blob/eafd3eed634d5e142810d1fabd20548881a23a7b/invenio_rdm_records/fixtures/data/vocabularies/licenses.csv)
