### ISSUE TITLE
styles: long email puts user dropdown in header on next line

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#267]
Package version (if known): might have to do with invenio-accounts / invenio-theme

## Describe the bug
A long user email causes the user dropdown to be placed on a separate line when it shouldn't be.

![image](https://user-images.githubusercontent.com/1932651/91725841-e5083a00-eb64-11ea-900b-4c6d97fcbdf6.png)

## Steps to Reproduce
1. Login/create an account with a moderate size email 
2. See error

## Expected behavior
Ellipsis truncation: `a-very-long-username@a-very-long-host-neh.a-long-domain`  -> `a-very-long-username@...` . Up to implementer for size that makes sense. Playing with padding and margin may also allow longer names (I don't think my name is too long :crying_cat_face: ...)

**Comment by cenouralm** [comment]
Followed the steps and obtained the expected behavior.
<img width="963" alt="Captura de ecrã 2020-09-14, às 15 50 23" src="https://user-images.githubusercontent.com/6940589/93094331-12470300-f6a2-11ea-8e52-5351bf7cb097.png">

**Comment by frankois** [comment]
Solved by https://github.com/inveniosoftware/invenio-theme/pull/208
