### ISSUE TITLE
Creators Roles Don't Show in UI

### ISSUE THREAD

**Issue by tmorrell** [inveniosoftware/invenio-app-rdm#2692]
Package version (if known): v9-v12

## Describe the bug
The creator roles don't show up in the UI.

## Steps to Reproduce
1. Create a creator with a role
2. Look at the landing page. The role does not show up anywhere.

## Expected behavior
The roles should be listed. Possibly with numbers like the affiliations.

**Comment by lnielsen** [comment]
I agree the roles for creators should be listed (this is already the case for contributors), and as you suggest possible like affiliations with numbers (at least the way contributor roles are listed wont' work). Perhaps it could be integrated with the affiliations?
