### ISSUE TITLE
secret links: review permissions logic

### ISSUE THREAD

**Issue by anikachurilova** [inveniosoftware/invenio-app-rdm#2694]
- Links tab showing count `1`, when no links present ![Screenshot 2024-06-05 at 13 16 46](https://github.com/inveniosoftware/invenio-app-rdm/assets/61321254/f100c509-685c-46da-8815-9bd25404d5da)

----------------------------------------------------------------------------------------------
**View access level**

Current behavior for share draft:
creates a link to `/uploads/<id>` which is always permission denied (+ redirects to login) because draft can be viewed either in edit or preview mode, we don't have anything to render in the "view" node.

Expected behavior for share draft:
(?) redirects to `/preview` and acts the same way as `preview drafts` permission

Current (and expected) behavior for share published record:
renders landing page `/records/<id>`

**Decided solution:**
- `can view` secret links always points to `/records`, even for drafts. 
- In case there are no drafts, fails with 404.
- UI: gray out the `can view` option in the dropdown for unpublished record. + add explanation why grayed out. Same for the dropdown for creating the link
- Backend: no validation for this on the backend --> let them create it via rest api and then fail with 404

----------------------------------------------------------------------------------------------
**Preview drafts access level**

Current behavior for share draft:
creates a link to `/uploads/<id>` which leads to permission denied error (because this link leads to the edit draft page)

Expected behavior for share draft:
(?) redirects to `/preview=1`. Problem here: after publishing the record, the link will be broken (404) in case there is no draft created

Thoughts: as preview drafts makes sense only when the draft is created, maybe we should consider removing this option from share modal of published record and keep it in the share draft? If yes, then we should do it for user/group grants as well.

Current behavior for share published record:
renders landing page `/records/<id>`

**Decided solution:**
- the link should point to `/record/<id>?preview=1`
- in case there is no draft created -> fail with 404 (current behavior), but add to the error page a nice message and a button "Go to record" that leads to landing page

----------------------------------------------------------------------------------------------
**Edit access level**

Current (and expected) behavior for share draft:
creates a link to `/uploads/<id>`, which is draft editing page

Current behavior for share published record:
renders landing page `/records/<id>` with "Edit" button present. 

Thoughts: should we change the behavior to automatically create draft and open the draft edit page `/uploads/<id>` to keep consistent with share draft?

**Decided solution:**
- leave as it is -> creating a new draft every time somebody clicks on this link is expensive and unnecessary operation

----------------------------------------------------------------------------------------------
**Additional**:
Add explanation of each permission to docs, similar to communities: https://help.zenodo.org/docs/communities/about-communities/

**Comment by Samk13** [comment]
Question:
Should Invenio automatically delete all shared links/users access created during the draft state once the draft is accepted as a final record, requiring users to create new links for the final record to ensure proper access control?
