### ISSUE TITLE
administration: drafts link is incorrect

### ISSUE THREAD

**Issue by tmorrell** [inveniosoftware/invenio-app-rdm#2703]
Package version (if known): v12rc2

## Describe the bug
The drafts administration panel at /administration/drafts links the title of the results to /records/rec-id. Since these are drafts, there is no landing page and this results in an error. They should link to /uploads/rec-id.

## Steps to Reproduce
1. Go to /administration/drafts
2. Click on the title of a draft
3. See the 404 error

## Expected behavior

Should link to the draft at /uploads

## Additional context

It looks like the links.self_html value returned for the results needs to be fixed. Here is a reference https://github.com/inveniosoftware/invenio-app-rdm/blob/75b3fd72d977789bce7b9dc390cf6d5db1b7fc12/invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/search/SearchResultItemLayout.js#L59. Alternatively a different SearchResultItemLayout could be created specifically for drafts.

**Comment by tmorrell** [comment]
May be fixed by https://github.com/inveniosoftware/invenio-rdm-records/pull/1700/files (needs extensive testing)

**Comment by tmorrell** [comment]
May also be fixed by https://github.com/inveniosoftware/invenio-app-rdm/pull/2722/files

**Comment by tmorrell** [comment]
May have been fixed by https://github.com/inveniosoftware/invenio-users-resources/pull/136/files

**Comment by utnapischtim** [comment]
this would fix it: https://github.com/inveniosoftware/invenio-rdm-records/pull/1700

**Comment by utnapischtim** [comment]
closed with https://github.com/inveniosoftware/invenio-rdm-records/pull/1700
