### ISSUE TITLE
v12-upgrade: `removalreasons` vocabularies aren't created

### ISSUE THREAD

**Issue by max-moser** [inveniosoftware/invenio-app-rdm#2717]
Package version (if known): 12.0.0rc2

## Describe the bug
v12 introduces the record deletion feature, which uses a new vocabulary type "removalreasons".
The upgrade script from an existing v11 instance to v12 doesn't create those vocabularies however.

## Expected behavior
The vocabularies get updated appropriately.

## VocabularyTypes in our v12

```python
In [5]: VocabularyType.query.all()
Out[5]: 
[<VocabularyType languages>,
 <VocabularyType licenses>,
 <VocabularyType creatorsroles>,
 <VocabularyType contributorsroles>,
 <VocabularyType descriptiontypes>,
 <VocabularyType datetypes>,
 <VocabularyType relationtypes>,
 <VocabularyType titletypes>,
 <VocabularyType resourcetypes>,
 <VocabularyType names>,
 <VocabularyType funders>,
 <VocabularyType awards>,
 <VocabularyType communitytypes>]
```

**Comment by utnapischtim** [comment]
fixed by #2710
