### ISSUE TITLE
Unable to create record

### ISSUE THREAD

**Issue by carsonicator** [inveniosoftware/invenio-app-rdm#272]
Package version (if known): invenio-cli, version 0.16.0

## Describe the bug
I'm unable to create a record. Publishing a record returns me to the record creation page with error triangles in all section headers, including those that are "COMING SOON".

## Steps to Reproduce
1. After installation, create a user account and log in.
2. Click "Uploads" in top menu bar.
3. Click "New Deposit".
4. Enter all required information and optional info if you like.
5. Click on "Publish".
6. Click "Publish" on the popup.
7. See red triangles as you are returned to the record page, but no error message.

## Expected behavior
Record is created as long as all required information is entered. I would expect an error message if these criteria weren't met.

## Screenshots (if applicable)

Expected publish popup:

<img width="928" alt="Screen Shot 2020-09-01 at 6 25 29 PM" src="https://user-images.githubusercontent.com/11506832/92035471-5f3ae900-ed34-11ea-8d0b-c29254a31a80.png">

After clicking "Publish" I was returned to the record page with those red triangles in all section headers:

<img width="1199" alt="Screen Shot 2020-09-01 at 6 20 26 PM" src="https://user-images.githubusercontent.com/11506832/92035428-50543680-ed34-11ea-872b-01cf0e4af684.png">

<img width="892" alt="Screen Shot 2020-09-02 at 10 49 59 AM" src="https://user-images.githubusercontent.com/11506832/92035647-a1fcc100-ed34-11ea-90f2-09b371f525e7.png">

When I go to search for it, it's not there:

<img width="1154" alt="Screen Shot 2020-09-01 at 6 28 33 PM" src="https://user-images.githubusercontent.com/11506832/92035721-bfca2600-ed34-11ea-8d17-635c02e588d0.png">

## Additional context
I created one community before I created a record.

**Comment by cenouralm** [comment]
I was able to replicate the issue. After filling all the necessary fields and clicking on the "Publish" pop-up I stay on the same page with all the warning triangles showing up. Not only that but when I hop to the "deposits" page there is no new record.

**Comment by cenouralm** [comment]
The "Family Name" field from the creator's part, should be marked as "required" since if not filled will yield the above-presented error.

**Comment by fenekku** [comment]
Thanks for validating it. I am now placing it in Todo with the goal being to solve it. (removing good first issue)
