### ISSUE TITLE
Requests: Cursor keeps getting repositioned when writing comments

### ISSUE THREAD

**Issue by max-moser** [inveniosoftware/invenio-app-rdm#2730]
Package version: 12.0.0rc2

## Browser
Firefox 127.0.2 (not to be confused with localhost) on Linux

## Describe the bug
When writing comments on requests, the cursor keeps getting repositioned to the beginning of the input field, which makes writing comments very painful.
It looks like this happens periodically, probably the refresh timer.

## Steps to Reproduce
1. Open a request (e.g. community-submission)
3. Visit the request's timeline/details page
4. Write some long text
5. Feel the pain

## Expected behavior

The cursor keeps its position

**Comment by max-moser** [comment]
Potentially related: [5s refresh interval for requests](https://github.com/inveniosoftware/invenio-requests/blob/master/invenio_requests/assets/semantic-ui/js/invenio_requests/InvenioRequestsApp.js#L33)

**Comment by Samk13** [comment]
I didn't understand the browser part: Firefox 127.0.2 (not to be confused with localhost) on Linux. However, I tested it on both Chrome and Firefox, and it seems like I am unable to reproduce the issue. Am I missing something @max-moser ? I am testing on Linux: Pop_OS. 
![cursor-test](https://github.com/inveniosoftware/invenio-app-rdm/assets/36583694/c3021400-d303-4421-8c7b-abf534e7c543)

**Comment by fenekku** [comment]
> I didn't understand the browser part: Firefox 127.0.2 (not to be confused with localhost) on Linux.

That was a reference to his version of Firefox. The version number 127.0.2 looks like a local network IP of the 127.0.X.Y variety.

If you type out a long comment 255 chars+ (much longer than just "asdfgadfs" and no new lines). Do you get the same behaviour?

**Comment by Samk13** [comment]
Got it now Firefox version 127.0.2, not your local IP! 😅 

Okay, using Firefox 127.0 (June 11, 2024 release), I tested with a long comment (255+ characters, single line). The cursor only jumps when pressing enter, as I mentioned earlier.
![cursor-2](https://github.com/inveniosoftware/invenio-app-rdm/assets/36583694/40bd56ae-d419-48da-a0a1-f706f51eb395)

Any ideas on the cause @fenekku ?

**Comment by fenekku** [comment]
> The cursor only jumps when pressing enter, as I mentioned earlier.
> I've also noticed that it loses focus randomly, as seen in the SR when clicking and pressing space rapidly also not related to the timer.

Ugh... I am still thinking it has to do with the textarea being re-rendered by React. It's a known problem that the cursor position will be lost in those situations unless kept in the state or using a Ref (:stuck_out_tongue_closed_eyes: ). If it's not (only) the 5s timer causing re-renders, but perhaps other events that would explain it. I am working on something else so perhaps a React expert could chime in.
