### ISSUE TITLE
De-commission https://invenio-app-rdm.readthedocs.io/en/latest/installation.html

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#278]
## Is your feature request related to a problem? Please describe.

This site is accessed by people wanting to use invenio-rdm, but it is not the right resource for them (or anyone at this point). It's just not maintained or meant to be used at all anymore. The nuance that this is the low-level documentation for this module cannot be communicated to passer-bys easily. IMHO it's easier to remove it.

**Comment by lnielsen** [comment]
Deleted
