### ISSUE TITLE
Share link: "Can view drafts and restricted files of all versions of this record." not working

### ISSUE THREAD

**Issue by chriz-uniba** [inveniosoftware/invenio-app-rdm#2827]
Package version (if known): v12.0.5

## Describe the bug
When sharing a link with a "people", and using the "Can preview drafts" (Can view drafts and restricted files of all versions of this record.), the people gets a notification, but gets a "page not found" when clicking on the link in the email.

## Steps to Reproduce
1. Go to saved record draft.
2. Click on "Share"
3. Click on "Add people"
4. Select a people and grant access "Can preview drafts".
5. People gets an email with a link
6. People clicks on the link
7. Gets "page not found"

## Expected behavior

People is allowed to see the page.

**Comment by utnapischtim** [comment]
is this draft part of a community?

**Comment by chriz-uniba** [comment]
Steps to Reproduce says no, so no community involved.
