### ISSUE TITLE
Empty querystring returns no result

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#284]
Package version (if known): v0.14.0

## Describe the bug

Empty querys tring returns no result instead of "latest"

## Steps to Reproduce
1. Query like
```bash
$ curl -k -XGET https://localhost:5000/api/records?&page=1

{"hits": {"hits": [], "total": 0}, "links": {"self": "https://127.0.0.1:5000/api/records?page=1&q=&size=25&sort=bestmatch"}, "aggregations": {"resource_type": {"doc_count_error_upper_bound": 0, "sum_other_doc_count": 0, "buckets": []}, "access_right": {"doc_count_error_upper_bound": 0, "sum_other_doc_count": 0, "buckets": []}}}%
```

If removing the `q=` from que url, the latest are returned.

## Expected behavior

Latest shown

## Additional context

NOTE: This will most likely propagate to `invenio-records-resources` at query interpreter level.

When querying with content it works and displays correctly. e.g.

![Screenshot 2020-10-02 at 13 22 09](https://user-images.githubusercontent.com/6756943/94918375-bc03fd80-04b2-11eb-861e-05acd01cd4ef.png)

**Comment by ppanero** [comment]
invenio-drafts-resources fails on that: https://github.com/inveniosoftware/invenio-drafts-resources/pull/61

**Comment by fenekku** [comment]
> $ curl -k -XGET https://localhost:5000/api/records?&page=1
> If removing the q= from que url, the latest are returned.

Typo? `q=` is already absent from the curl call. Which combination is problematic?

How is this: https://github.com/inveniosoftware/invenio-records-resources/pull/120/files?file-filters%5B%5D=.py&hide-deleted-files=true#diff-44e1955900a1e73ea159f47da8d424e9R59 passing ? (what is the difference?)

**Comment by ppanero** [comment]
@fenekku shown in PR of `records-resources`. The problem was that `q=` was actually forcing the query to look for **fully empty documents** ... just cuz of an `if` 😅
