### ISSUE TITLE
global: integrate invenio v3.2

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#29]
We are already using the latest `invenio` version `v3.2.0a9`.

- We can already start testing files upload (REST API)
- Wait for the release of 3.2
- Pin to 3.2 (using only bundles)
- Investigate possible inconsistencies in pinned versions.

**Comment by fenekku** [comment]
Closed via https://github.com/inveniosoftware/invenio-rdm-records/pull/41
