### ISSUE TITLE
Old `invenio-admin` administration panel is active

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-app-rdm#2924]
The old `invenio-admin` administration menu entry seems to be active, which displays two entries (the other one for the `invenio-administration` UI):

<img width="200" alt="image" src="https://github.com/user-attachments/assets/c556d815-60cf-4bef-98e8-87c22ec57142">

The visibility of the `invenio-admin` entry is controlled [via permissions config](https://github.com/inveniosoftware/invenio-admin/blob/11c8f025ce79e505bce25c7a1f0dcf61183bd83d/invenio_admin/config.py#L28), so for now we can disable it.

The long-term solution is to upgrade to `invenio-access v3.x` which is the last dependency that doesn't have `invenio-admin` as an optional.

**Comment by utnapischtim** [comment]
[this](https://github.com/inveniosoftware/invenio-app-rdm/commit/4834c7a482c3aa6eaccea65c50ad3e531f072300) commit has removed the configuration to suppress the second administration menu entry. 

a quick solution would be to add add the missing configuration to the invenio.cfg file

**Comment by slint** [comment]
> a quick solution would be to add add the missing configuration to the invenio.cfg file

I think we'll have to add it back, or else the alternative is to bump to `invenio-access v3.x`, which I guess wouldn't be that bad of a solution... Was the major bump done because of the SQLAlchemy v2 compatibility or because of the removal of `invenio-admin` form the default install requirements?

**Comment by utnapischtim** [comment]
and as usual i thought that after i merged the PR in invenio-app-rdm i will do the change necessary for invenio-access in one go. and as usual it didn't happend as planned
