### ISSUE TITLE
[Discussion] How to handle records in the front-end

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#304]
The deposit form has two main issues:

1- Formik does not display the fields unless the are "expanded" by using empty content.
2- The record coming from the backend is transformed back and forth:
    - https://github.com/inveniosoftware/invenio-app-rdm/blob/a8e6f6085c442fba5cfe7859227d4752daac4ed3/invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js#L113
    - The `dump_empty` function might not be fully compatible with the new `MetadataSchemaV1`. Needs to be verified. https://github.com/inveniosoftware/invenio-app-rdm/blob/a8e6f6085c442fba5cfe7859227d4752daac4ed3/invenio_app_rdm/theme/views.py#L67

-----

Question: We need a concise way of representing the record in the frontend, that allows formik to display fields but does not go forth and back unnecessarily.

**Comment by zzacharo** [comment]
We should also consider that the frontend defines its own "empty" record too [here](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js#L29).

**Comment by fenekku** [comment]
One of those things to keep in mind:

Right now, after a save draft where no contributors were filled, we get:

![image](https://user-images.githubusercontent.com/1932651/95770881-b8753100-0c7f-11eb-9926-9cf25d027820.png)

but it should be 

![image](https://user-images.githubusercontent.com/1932651/95770959-d773c300-0c7f-11eb-891b-da3b75868074.png)

**Comment by lnielsen** [comment]
What should be reviewed in this issue?

**Comment by fenekku** [comment]
Let's close this. The main issue was how to load the record from the backend. With the refactor, @zzacharo and I did of the serializer it is now clear how to deserialize/serialize.

I would even go further and not have the backend generate an empty record for the frontend when creating a new record. The frontent record is very custom to the JS library, so it's better to separate those concerns and not have invenio-rdm-records need to care about frontend record formats. The deserialization process on the frontend know how to create an empty record compatible with our fields and formik, so we would be fine.
