### ISSUE TITLE
Contributors not on record landing page (check if already fixed)

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#305]
Package version (if known): 0.14.8

## Describe the bug
Filled contributors in the deposit page don't show up on the record landing page.

## Steps to Reproduce
1. Go to `/uploads/new`
2. Fill out a deposit correctly with a contributor as well.
3. Save draft and publish
4. See record landing page without contributors section.

## Expected behavior

4. See record landing page with listed contributors.

## Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/1932651/95772121-d8a5ef80-0c81-11eb-8dd0-3c2148fc1a51.png)

## Additional Context

It very well might be that we are not saving the contributors correctly in the first place (didn't investigate very far).

**Comment by lnielsen** [comment]
I think this one has been fixed, so the task here is just to verify that indeed it's fixed.

**Comment by ppanero** [comment]
It is :)
