### ISSUE TITLE
Contributor role error message is missing 

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#306]
Package version (if known): 0.14.8

## Describe the bug
When filling a contributor data on the deposit page, but forgetting to fill out the role, the contributors section is highlighted in red (good!), but the pop-over for the role field (the one that says "Missing required data...") isn't showing up (bad!). 

## Steps to Reproduce
1. Go to `/uploads/new`
2. Fill out contributors except for role
3. Save Draft
4. See highligted mistake but missing pop-over

## Expected behavior

Having the pop-over like there is one for the resource type.

**Comment by Glignos** [comment]
![Screenshot 2020-11-09 at 11 48 40](https://user-images.githubusercontent.com/16304052/98532153-9a502000-2281-11eb-8f81-1f0680b4b008.png)
Cannot be reproduced anymore since the role filed always gets a default value.
