### ISSUE TITLE
Indicate ownership / depositor

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#315]
As an owner, I would like to see this confirmed on the landing and deposit/edit pages for my own records so that I recall I am the owner - especially in the case where the record was proxy deposited.

(from DevSci partner)

**Comment by lnielsen** [comment]
@fenekku Can you confirm that this is solved by adding the edit button and manage bar to the landing page?

**Comment by fenekku** [comment]
I think this will be resolved with the "Manage permissions" button/modal. The underlying use case here was:

I am a researcher. I tell my administrative staff to enter one of my research output where I am the owner into InvenioRDM . I participate in many other projects where I am not the owner. I visit the page of that research project a year later for academic assessment / future work. Do I own this record or was I just a collaborator? Who entered this? 
    
By having the "Manager permissions" section, they will be able to see that they are the owner. Presumably there will also be an indicator that their assistant entered it. Either in the same permission modal or somewhere else; I think there was talk of adding this to the search results next to "Created on" - Could be something similar at the bottom of the page.

**Comment by lnielsen** [comment]
Solved by having the edit, and management bar shown if you can edit
