### ISSUE TITLE
ui: record page

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#32]
Ideas:

- Title
- Description
- Side part with permissions/access information
- Cool DOI highlighted top right (?)

**Comment by fenekku** [comment]
Let's omit permission and DOI since we are not minting DOI yet and permissions are not settled.

**Comment by ppanero** [comment]
@fenekku  permissions are not settled, but we are allowing them to be customized (with the current schema) therefore for clarity I would (if possible) add a simple something on the right (as in the mockups Lars send).

I understand they are not settled yet, but at least would give the impression of where the permissions would be.

I also understand the perspective of "its gonna change, is not settled, why shall we do it". But all might change... :sweat_smile: : no?
