### ISSUE TITLE
search result page: remove whitespace to header

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#329]
Remove the white space marked in the screenshot.

![Screenshot 2020-10-21 at 14 34 39](https://user-images.githubusercontent.com/1698163/96720180-c119e580-13aa-11eb-86fd-d51038c782ff.png)

**Comment by cenouralm** [comment]
PR `https://github.com/inveniosoftware/invenio-search-ui/pull/106`
