### ISSUE TITLE
search result page: sort option text is wrapped 

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#332]
Current:

![Screenshot 2020-10-21 at 14 45 02](https://user-images.githubusercontent.com/1698163/96721202-14406800-13ac-11eb-9f6d-ca066cdbe758.png)

Expected:

![Screenshot 2020-10-21 at 14 46 03](https://user-images.githubusercontent.com/1698163/96721263-26220b00-13ac-11eb-9855-493639afff79.png)

**Comment by Glignos** [comment]
![Screenshot 2020-10-26 at 11 48 39](https://user-images.githubusercontent.com/16304052/97163625-36a5fd00-1781-11eb-84b9-a21e257b0458.png)
Can't replicate in latest.
