### ISSUE TITLE
landing page: fix styling of description section

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#342]
Notice:

- Bold header.
- No italics
- Help icon with tooltip for license
- Fontsize is the same all over.
- Also rename "Keywords" to "Subjects"
- Only display a given section if there is any data.

### Current

![Screenshot 2020-10-21 at 15 58 21](https://user-images.githubusercontent.com/1698163/96730195-3e972300-13b6-11eb-89b1-d9e58aef3dfa.png)

### Exepcted

<img width="775" alt="Screenshot 2020-10-21 at 15 59 01" src="https://user-images.githubusercontent.com/1698163/96730340-57073d80-13b6-11eb-9cd8-324ecb1b8d30.png">

**Comment by frankois** [comment]
I am not sure about the text I should add in the `Help icon with tooltip for license`?
