### ISSUE TITLE
Contact record person responsible for record

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#347]
As someone finding a record of interest, I want to contact the person responsible for the record by clicking on a "Contact" button, so that I can discuss the record with them.

person responsible for the record: owner, proxy, contact email ?
contact button: leads to a text area to write up the message
stale emails: if the contact email is stale, it would be nice to send an email to alert the site's administrators (*that* email should always be valid ;) ). (don't know yet if possible...)

**Comment by lnielsen** [comment]
Closing in favour of inveniosoftware/product-rdm#31
