### ISSUE TITLE
Selecting sqlite in review installation results in "ERROR: Service 'web-ui' depends on service 'db' which is undefined."

### ISSUE THREAD

**Issue by origliante** [inveniosoftware/invenio-app-rdm#367]
Package version: invenio-cli 0.17.2

## Describe the bug
When selecting sqlite as the database in "invenio-cli init rdm" and then starting containers with "invenio-cli containerize --pre" results in:
```
Making sure containers are up...
ERROR: Service 'web-ui' depends on service 'db' which is undefined.
subprocess.CalledProcessError: Command '['docker-compose', '--file', 'docker-compose.full.yml', 'up', '--build', '-d']' returned non-zero exit status 1.
```

## Steps to Reproduce
1. selecting sqlite as the database in "invenio-cli init rdm"
2. starting containers with "invenio-cli containerize --pre"

## Expected behavior
image yaml to support sqlite

**Comment by ppanero** [comment]
Is this still an issue with the latest `docker-services-cli`?

**Comment by origliante** [comment]
@ppanero checking and getting back to you

**Comment by origliante** [comment]
@ppanero tested with

`invenio-cli containers start --lock --build --setup`

I got:
`ERROR: Service 'worker' depends on service 'db' which is undefined.
Failed to start containerized instance.`

**Comment by lnielsen** [comment]
Closing the issue, as I've put the inveniosoftware/cookiecutter-invenio-rdm#16 on the board for the next iteration.
