### ISSUE TITLE
theme: refactor css files

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#374]
## Is your feature request related to a problem? Please describe.
Currently there are files for specific css/styling of each "page". E.g. `frontpage.less` for the frontpage etc. However, the main `theme.less` files contains styling for all of them. Some of this styling is duplicated, some is overwritten, etc.

## Describe the solution you'd like
Refactor it in a way that each file contains its page css and the main `theme.less` is reduced to:

```
@import "variables.less";
@import "footer.less";
@import "frontpage.less";
@import "deposit.less";
@import "search.less";
```

It might include generic class overwrites.

**Comment by lnielsen** [comment]
CSS needs a full review so I'm closing as this is not easily actionable without first doing the review and design
