### ISSUE TITLE
docs: how to get access to the code?

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#38]
As from the invenio-talk forum on [release 2 - November](https://invenio-talk.web.cern.ch/t/inveniordm-alpha-2-november-release/51/6)

We got:

> how to get access to the codes like html, python files and etc.

Shall we document some sort of "module architecture", i.e. which modules are involved in RDM and who does what?

**Comment by fenekku** [comment]
Asked clarification on discourse about that.

**Comment by fenekku** [comment]
Answered the person asking this question. Code and chat are linked from the https://inveniosoftware.org/products/rdm/ page. Access to the instance specific code will be documented in the wiki as we deal with that part of the customization. 

Marking this as done.
