### ISSUE TITLE
ux: footer space 

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#384]
The footer should be at the end of the browser and also spaced with the "jump" button

![Screenshot 2020-11-10 at 16 17 08](https://user-images.githubusercontent.com/6756943/98693204-4cfeac00-2370-11eb-96a2-caa4c6be2f36.png)

![Screenshot 2020-11-10 at 16 16 57](https://user-images.githubusercontent.com/6756943/98693218-512ac980-2370-11eb-9f85-f8967b7575e2.png)

![Screenshot 2020-11-10 at 16 16 40](https://user-images.githubusercontent.com/6756943/98693229-52f48d00-2370-11eb-9f61-e867da7ab222.png)

![Screenshot 2020-11-10 at 16 18 28](https://user-images.githubusercontent.com/6756943/98693292-63a50300-2370-11eb-9497-773f76eaf462.png)

**Comment by fenekku** [comment]
Especially problematic for the pagination and "number of results" dropdown when there are results. Where are they :grin: ?

![search_page_footer](https://user-images.githubusercontent.com/1932651/98732396-b24ca000-2364-11eb-8158-1491e714ce11.png)
