### ISSUE TITLE
deposit form: publish activates even if save draft fails

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#387]
When saving a draft for the first time, even if the save fails (i.e. there is no draft created) the `publish` button gets activated. This would lead to inconsistencies (or even failures if pressed before a successful `save`).

In the following screenshot, the `publish` button should still be grayed out.

![Screenshot 2020-11-10 at 16 42 51](https://user-images.githubusercontent.com/6756943/98696503-2b072880-2374-11eb-9472-629e7c9915ed.png)

**Comment by Glignos** [comment]
@ppanero I cannot reproduce the described issue by setting the tab to offline, thus having the creation request fail.
The code that enables the button is [here](https://github.com/inveniosoftware/react-invenio-deposit/blob/1c223b017b07aa6ddd9ac37b2026b6219e478781/src/lib/actionButtons/PublishButton/PublishButton.js#L21) so for the moment I don't see how these could be set if the request failed.
