### ISSUE TITLE
dependencies: avoid hardcoding versions of non-bundles

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#39]
Currently we need to be in line with `invenio_search` and `invenio_db` versions. It would be nice if we could just specify `invenio` with different extras. At the moment that seems to be ignored by pip/setuptools, it checks that the dependency is installed and ignores the fact that extras are different.

It would result in a `setup.py` file much more condensed:

 ``` python

invenio_version = '==3.2'

extras_require = {
    'elasticsearch6': [
        'Invenio[elasticsearch6]{}'.format(invenio_version)
    ],
    'elasticsearch7': [
        'Invenio[elasticsearch7]{}'.format(invenio_version)
    ],
    'mysql': [
        'Invenio[mysql]{}'.format(invenio_version)
    ],
    'postgresql': [
        'Invenio[postgresql]{}'.format(invenio_version)
    ],
    'sqlite': [
        'Invenio[sqlite]{}'.format(invenio_version)
    ]
}

install_requires = [
    'Invenio[base,auth,metadata,files]{}'.format(invenio_version),
    'invenio-rdm-records>=1.0.0a7',
    'invenio-records-permissions>=1.0.0a5',
]
```

**Comment by fenekku** [comment]
Does that above `setup.py` work? If yes, it sounds like a good plan to me.

**Comment by ppanero** [comment]
@fenekku nope, sadly no :( I spend almost a day trying to make something similar work before christmas but didn't manage. I can retake the work if needed.

**Comment by fenekku** [comment]
For myself: we want invenio version to determine the invenio_search and invneio_db versions that are compatible.

**Comment by fenekku** [comment]
**Grooming**
This amounts to exploding the bundles into their constituent packages and specifying their versions separately. We are already doing this now, because we move faster than the Invenio package.

I am closing this since we dealt with this on this sprint.
