### ISSUE TITLE
ux: language dropdown cuts off descenders

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#391]
Package version (if known): 0.16.4

## Describe the bug
The language dropdown cuts off the [descenders](https://en.wikipedia.org/wiki/Descender) of words in it (at least on Firefox + ubuntu).

## Screenshots (if applicable)

![footer_dropdown](https://user-images.githubusercontent.com/1932651/98728242-d86f4180-235e-11eb-8ccd-21f1322bbdf9.png)

(same for Turkçe)

**Comment by lnielsen** [comment]
@fenekku Can you confirm that this is still an issue. If it is please add to "InvenioRDM April Planning" project, if not close :-)

**Comment by fenekku** [comment]
We don't use translations (no dropdown at all) at our site or on the CERN demo site. I can close this and we can re-open/create new one when translations are brought back. Our instance doesn't plan on supporting translations.
