### ISSUE TITLE
Move frontpage default code to cookiecutter

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#407]
Having the frontpage's html, less and assets in this repo, means it is always part of the webpack build process making it slower and generating bigger assets that are eventually unused anyway. Placing the frontpage related things in the cookiecutter gives an immediate customization point to installers and is more efficient.

**Comment by zzacharo** [comment]
@fenekku I am closing this and maybe we could open a more specific issue if it's still needed for improving customization :)

**Comment by lnielsen** [comment]
Log ideas to https://github.com/inveniosoftware/product-rdm/issues/14

**Comment by fenekku** [comment]
Oh I thought this was quite specific: move the frontpage html/js/less from app-rdm into the cookiecutter project, so that the frontpage. which will always be overwritten, doesn't stay in app-rdm. Otherwise, more configuration needed / webpack still builds its assets (pretty sure) and app-rdm is laden with dead code. I will put that in the product one.
