### ISSUE TITLE
Service config overrides not taken into account

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-app-rdm#418]
Package version (if known): 0.17.1

## Describe the bug

Overriding service configuration via `invenio.cfg` variables, is not taken into account. 

## Steps to Reproduce

1. Follow the ["Change permissions"](https://inveniordm.docs.cern.ch/develop/make_it_your_own/#change-the-permissions) chapter from RDM docs
2. Requests with an API token from a `SuperUser` to `POST /api/records` get a 403 response 

## Expected behavior

Service config overrides should be respected (e.g. to change permissions).

## Additional context

The issue seems to be with the way the service sub-class hierarchy (i.e. `ConfigLoaderMixin.load_config` is not called at the right moment/place).

**Comment by fenekku** [comment]
I tried to reproduce this with the November release 0.17.4 and I wasn't able to do so. Preventing creation except for super user worked fine (not able to create as non-super user, and able to create as super-user). I am closing this for now, re-open if you are still experiencing issues.
