### ISSUE TITLE
Identifier scheme field is case sensitive

### ISSUE THREAD

**Issue by carsonicator** [inveniosoftware/invenio-app-rdm#423]
Package version (if known): 0.17.0

## Describe the bug
When creating or editing a record, adding identifier name “ORCID” instead of “orcid” generates an error when attempting to save a draft. Once I changed it to “orcid” I was able to save a draft and publish the record:

## Steps to Reproduce
1. Create a new record or edit an existing record.
2. Add a creator and an ORCID identifier for that creator typing "ORCID" in the "Scheme" field.
3. Click "Save draft".
4. See error.
5. Change identifier "Scheme" field to "orcid".
6. Error does not occur.

## Expected behavior

Text fields should be case insensitive.

## Screenshots (if applicable)

<img width="650" alt="Screen Shot 2020-11-30 at 4 23 08 PM" src="https://user-images.githubusercontent.com/11506832/100673513-2efde900-3329-11eb-8b59-163a219c4394.png">

After clicking "Save draft" with "ORCID" typed in the "Scheme" field:

<img width="1177" alt="Screen Shot 2020-11-30 at 4 23 37 PM" src="https://user-images.githubusercontent.com/11506832/100673498-29080800-3329-11eb-8f9e-37428a5e23af.png">

**Comment by lnielsen** [comment]
For February iteration:
- Check REST API validaiton to see if both ORCID and orcid is allowed. The UI was changed so that the scheme is no longer avialable as an input field.
