### ISSUE TITLE
[previewer] Image (JPG) preview does not work

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#424]
Package version (if known): november release

## Describe the bug
After uploading a JPG image via UI or API, the previewer is unable to display the image.

![image](https://user-images.githubusercontent.com/1932651/100794723-96786f00-33e3-11eb-986d-f7a01bb62dee.png)

## Steps to Reproduce
Follow the upload steps:

UI
1. Upload image, save draft and publish

API
1. `curl -k -XPOST https://127.0.0.1:5000/api/records/jnmmp-51n47/draft/files -H "Content-Type: application/json" -d '[
  {"key": "leaf_doge.jpg"},
]
'`
2. `curl -k -XPUT https://127.0.0.1:5000/api/records/jnmmp-51n47/draft/files/leaf_doge.jpg/content -H "Content-Type: application/octet-stream" --data-binary @leaf_doge.jpg
` 
3. `curl -k -XPOST https://127.0.0.1:5000/api/records/jnmmp-51n47/draft/files/leaf_doge.jpg/commit`
4. `curl -k -XPOST https://127.0.0.1:5000/api/records/jnmmp-51n47/draft/actions/publish`

## Additional notes

The file is fetched from the network correctly. PDFs can be previewed fine.

**Comment by fenekku** [comment]
:thinking: some jpg work and some don't... Needs further investigation if this is just a private instance problem or not...

**Comment by ppanero** [comment]
closing this as I found out that it's the same problem (Size) than for png images. Working on https://github.com/inveniosoftware/invenio-previewer/issues/147
