### ISSUE TITLE
[ux] notification banner shows raw html when redirect to landing page

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#428]
Package version (if known): november release

## Describe the bug
The notification banner after signup shows raw html.

## Steps to Reproduce
1. Go to record page
2. Click Sign up, fill it out and get redirected
2. See error

## Expected behavior
Nice notification banner

## Screenshots (if applicable)

![signup-header-bug_blacked](https://user-images.githubusercontent.com/1932651/101036444-a5c0ff00-3540-11eb-9cf1-a2f865f2d297.png)

**Comment by ppanero** [comment]
Tried to reproduce. What happened:

- Got redirected to frontpage (not landing page 🤔 )
- Got a proper banner:
<img width="1789" alt="Screenshot 2021-01-11 at 12 16 26" src="https://user-images.githubusercontent.com/6756943/104174902-edbc2700-5406-11eb-8d10-2ee275f1df5e.png">

**Comment by fenekku** [comment]
As of february release, this is still happens :thinking:

**Comment by fenekku** [comment]
Only affecting NU apparently. Closing in favour of an internal issue.
