### ISSUE TITLE
Augmenting search results using top-level facets does not work 

### ISSUE THREAD

**Issue by carsonicator** [inveniosoftware/invenio-app-rdm#440]
Package version (if known): November release

## Describe the bug
Search results are not updated after augmenting a search for one resource type using an additional top-level resource type facet, i.e., applying a second top-level filter to a search does not work.

## Steps to Reproduce

1. Create three records; two with resource type `Text Resources --> Technical Documentation` and one of type `Conference Objects --> Conference Poster`
2. Search for all records
3. Facet by `Text Resources --> Technical Documentation`
4. Observe results (two records of type `Technical Documentation`)
5. Choose an additional filter for search: `Conference Objects`
6. Observe that no update to the search is displayed; the conference object does not appear. The result is the same as in step 4.

## Expected behavior

Expected my initial search for `Technical Documentation` to be updated when applying a second filter for `Conference Objects`, and to see both types of records ( a total of three results in this example).

## Screenshots (if applicable)

<img width="1177" alt="Screen Shot 2020-12-10 at 1 02 52 PM" src="https://user-images.githubusercontent.com/11506832/102373112-7a4d0400-3f85-11eb-83c1-349584a794cf.png">

**Comment by lnielsen** [comment]
Confirmed, that problem still exists in v1.0.0.

The problem seems to be related to the subtype. E.g. choose two main types (Lesson and Presentation), produces desired results of having records from both types in the search result. However, choosing a subtype (e.g. Publication / Preprint) and a main type (e.g. Lesson) does not produce correct results.

**Comment by ParthS007** [comment]
@lnielsen @fenekku 

https://user-images.githubusercontent.com/24358501/113722645-e8facc80-96f0-11eb-843a-c7d7f05b4046.mov
