### ISSUE TITLE
Large video files cannot be added to record

### ISSUE THREAD

**Issue by carsonicator** [inveniosoftware/invenio-app-rdm#441]
Package version (if known): November Release

## Describe the bug
Uploading a large video file (106,533 KB) failed. The uploaded file made it to 23% before stopping.

## Steps to Reproduce
1. Create or edit a record.
2. Choose a large video file to upload.
3. See error.

## Expected behavior

The file would have uploaded without problems. 

## Screen shot

![invenio test - Karen Gutzman](https://user-images.githubusercontent.com/11506832/102392844-382fbc80-3f9d-11eb-859a-fecfe517794b.PNG)

## Edit - Solution
The files API route in nginx needs to match up with the files API route in records-resources. Since they don't, the nginx configuration doesn't help us.

Key files:
- Cookiecutter nginx config: https://github.com/inveniosoftware/cookiecutter-invenio-rdm/blob/60ba9c42a44d85257f392c5dd14d4fb2ee67b13e/%7B%7Bcookiecutter.project_shortname%7D%7D/docker/nginx/conf.d/default.conf#L99
- Invenio-records-resources files API route: https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/resources/files/config.py#L27

**Comment by mb-wali** [comment]
@ppanero could this be because of Nginx configuration see [here](https://github.com/inveniosoftware/cookiecutter-invenio-rdm/blob/60ba9c42a44d85257f392c5dd14d4fb2ee67b13e/%7B%7Bcookiecutter.project_shortname%7D%7D/docker/nginx/conf.d/default.conf#L97) ?

**Comment by fenekku** [comment]
Thank you @mb-wali! 

Well that was embarassing: nginx is [configured for the files api below](https://github.com/inveniosoftware/cookiecutter-invenio-rdm/blob/60ba9c42a44d85257f392c5dd14d4fb2ee67b13e/%7B%7Bcookiecutter.project_shortname%7D%7D/docker/nginx/conf.d/default.conf#L99) but the actual [files API doesn't use that route](https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/resources/files/config.py#L27) :facepalm: . I've edited the ticket to reflect that.

**Comment by fenekku** [comment]
Still valid

**Comment by ppanero** [comment]
@fenekku Is this still valid? @mb-wali reported it was working for him this released (I think you actually change the nginx conf in cookiecutter IIRC)

**Comment by fenekku** [comment]
Right, this was solved and tested with 300MB+ files.
