### ISSUE TITLE
[form][ux] Display top-level and field-level errors consistently

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#451]
**Edit 2021-03-17**
Approach: make a top-level field correspondence. https://codimd.web.cern.ch/AsTpJ0NHQHWW9y5n7SxYhA?both
Not a big deal in the end, only because we did hard work of keeping complexity at bay.

**EDIT 2021-03-16**
Related issues:
- [ ] https://github.com/inveniosoftware/react-invenio-deposit/issues/213
- [ ] https://github.com/inveniosoftware/invenio-app-rdm/issues/483
- [ ] https://github.com/inveniosoftware/invenio-app-rdm/issues/674

**Original**
prefix errors with top-level **label** in the banner (group nested errors). Example:
        **Creators**: 
         - Error 1 is described here.
         - Error 2 is described there.
    - use ``<ul><li>Error 1 is described here.</li><li>...</li></ul>`` 
    - :nail_care: make it stick to top of viewport as you scroll down
    - :nail_care: link errors in that banner to the fields in the form

- E-B: When there are errors, only the top-level sections **containing** an error are highlighted:
    - could be highlighted via the warning symbol well spaced
    - could be a light red background

**Comment by lnielsen** [comment]
Tasks:
- Top-level errors:
  -  Frontend:
    - Display all top-level error messages correctly (instead of ``[Object] object``)
  -  Backend
