### ISSUE TITLE
[form][ux] Add help text to fields

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#453]
Add help text to the fields according to the below list:

### Publication date

In case your upload was already published elsewhere, please use the date of the first publication. Format: ``YYYY-MM-DD``, ``YYYY-MM``, or ``YYYY``. For intervals use ``DATE/DATE``, e.g. ``1939/1945``.

### Version

Mostly relevant for software and dataset uploads. A semantic version string is preferred (see [semver.org](https://semver.org)), but any version string is accepted.

### Publisher

The publisher is used to formulate the citation, so consider the prominence of the role.

### Related works

Specify identifiers of related works. Supported identifiers include DOI, Handle, ARK, PURL, ISSN, ISBN, PubMed ID, PubMed Central ID, ADS Bibliographic Code, arXiv, Life Science Identifiers (LSID), EAN-13, ISTC, URNs, and URLs.

Placement: Between field group segment and the "<icon> Related work" label.

**Comment by lnielsen** [comment]
For February:
- Split in smaller tasks for each field, with the acutal helptext to add as well.
