### ISSUE TITLE
deposit: Disable identifier component and field group 

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#457]
Remove the identifiers accordion including the identifiers component itself

![Screenshot 2021-02-01 at 15 35 33](https://user-images.githubusercontent.com/1698163/106472687-3796ab00-64a3-11eb-8f42-e744a88d3d9d.png)

**Comment by zzacharo** [comment]
included in https://github.com/inveniosoftware/invenio-app-rdm/issues/522
