### ISSUE TITLE
Consider revisiting identifiers storage

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#458]
Consider revisiting metadata storage of identifiers from dict to an array in the backend?
    - would greatly simplify serialization, deserialization and error handling on the frontend

**Comment by lnielsen** [comment]
Here's a use cases which requires that we implement this method.

In the deposit form, we need to be able to send identifiers without necessarily providing a scheme. For instance something like:

```
{
   "identifiers": [{"scheme": "", "value": "0000-0001-8135-3489"}]
}
```

This way the backend, can automatically determine the scheme of the identifier. If we use the dictionary structure:

```
{
   "identifiers": {
       "<scheme>": "<identifier>",
       "<scheme>": "<identifier>",
   }
}
```

Then, we cannot send multiple identifiers.
