### ISSUE TITLE
ui: field groups styling

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#466]
Field groups: 
![Screenshot 2021-01-21 at 14 33 06](https://user-images.githubusercontent.com/1698163/105357771-95024080-5bf5-11eb-9a2c-5d8d30746add.png)
  - Should have rounded corners (default semantic-ui styling).
  - The color should be easily changeable similar to [signup color](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/variables.less#L14). Perhaps we just use the "brand-primary" color. At least the color has to somehow fit with the header.

- Errors triangle inside, should look good no matter which color is used (do we need it at all?)

**Comment by lnielsen** [comment]
Examples of possible styling:

![Screenshot 2021-01-21 at 14 38 10](https://user-images.githubusercontent.com/1698163/105358299-499c6200-5bf6-11eb-9599-ca6f15f19849.png)
![Screenshot 2021-01-21 at 14 38 23](https://user-images.githubusercontent.com/1698163/105358318-515c0680-5bf6-11eb-9c0e-39825e761b82.png)
![Screenshot 2021-01-21 at 14 38 39](https://user-images.githubusercontent.com/1698163/105358344-5ae56e80-5bf6-11eb-8c2a-4e9bb52cc55f.png)

**Comment by zzacharo** [comment]
As discussed with @lnielsen I will merge this and if there is any issue will create a separate PR.
