### ISSUE TITLE
No spaces allowed in fields when creating a custom license 

### ISSUE THREAD

**Issue by carsonicator** [inveniosoftware/invenio-app-rdm#487]
Package version (if known): December release

## Describe the bug

When creating a custom license, no spaces are allowed in any of the three fields on the pop up.

## Steps to Reproduce

1. Create a new record.
2. Scroll down the the 'Licenses' section.
3. Go to 'Add a license' --> 'Create custom'.
4. Single click in any field and type a few letters, then hit the space bar.
5. See error.
6. Cancel the custom license creation.
7. Go to 'Add a license' --> 'Create custom' again.
8. Double click in any field and type a few letters, then hit the space bar.
9. Spaces should be allowed; no error.

## Expected behavior

A single click on a field should allow you to type all characters including spaces.

## Screenshots (if applicable)

If I use a single click, I cannot add spaces in any of the three fields within the custom license window:

<img width="929" alt="Screen Shot 2021-01-28 at 2 29 56 PM" src="https://user-images.githubusercontent.com/11506832/106195447-c343cb00-6175-11eb-91ed-abe18381770e.png">

If I double-click, I can add spaces in any field:

<img width="925" alt="Screen Shot 2021-01-28 at 2 31 55 PM" src="https://user-images.githubusercontent.com/11506832/106195457-c8a11580-6175-11eb-9499-2e25dbed59b7.png">

## Additional context

It's difficult to show in this context, but the inability to use the space bar seems tied to a switching back and forth between the parent page and the pop up as the active window (an attempt to show this is below):

Typing letters in the 'Title' field before hitting the space bar...

<img width="1064" alt="Screen Shot 2021-01-28 at 2 38 56 PM" src="https://user-images.githubusercontent.com/11506832/106196292-e15dfb00-6176-11eb-9c68-c16dc08ee44c.png">

After hitting the space bar, the license menu pops up in the background on the parent page (see the lower left corner of the image):

<img width="1076" alt="Screen Shot 2021-01-28 at 2 39 09 PM" src="https://user-images.githubusercontent.com/11506832/106196486-19653e00-6177-11eb-970d-7c7e434272fd.png">

**Comment by fenekku** [comment]
Thanks for that. This should show as solved for the january release - see https://github.com/inveniosoftware/react-invenio-deposit/issues/152 . Will close for now. Feel free to re-open if it's not solved when the january release is deployed.
