### ISSUE TITLE
Discarding draft of published record with file fails

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#489]
Package version (if known): january

## Describe the bug
See steps to reproduce

## Steps to Reproduce
1. Go to '/uploads/new' and create a record with a file and publish it
2. On the record's landing page, click on "Edit"
3. On the edit form, click on "Discard"
4. Get redirected to uploads and see the draft still there.

## Expected behavior
4. the draft should have disappeared

## Additional context

This is a backend issue with draft deletion:

```
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) update or delete on table "rdm_drafts_metadata" violates foreign key constraint "fk_rdm_drafts_files_record_id_rdm_drafts_metadata" on table "rdm_drafts_files"
DETAIL:  Key (id)=(af830f74-4a0f-4282-8c7b-7ba23df6005d) is still referenced from table "rdm_drafts_files".

[SQL: DELETE FROM rdm_drafts_metadata WHERE rdm_drafts_metadata.id = %(id)s AND rdm_drafts_metadata.version_id = %(version_id)s]
[parameters: {'id': UUID('af830f74-4a0f-4282-8c7b-7ba23df6005d'), 'version_id': 7}]
```

**Comment by lnielsen** [comment]
See also inveniosoftware/invenio-drafts-resources#99
