### ISSUE TITLE
Missing access right icon in label of search results

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#490]
Package version (if known): January

## Describe the bug
Notice the missing open lock icon:

![image](https://user-images.githubusercontent.com/1932651/106207506-7d8ffe00-6187-11eb-9a83-68949e6f16a5.png)

## Steps to Reproduce
1. Go to '/search' or `/uploads`

## Additional context
This happens for demo recordd or created records or drafts .

![image](https://user-images.githubusercontent.com/1932651/106671097-8e6bb580-6573-11eb-98c3-6cf9cfcb2954.png)

**Comment by lnielsen** [comment]
This has to be fixed, but there's an open question on how access rights should be recorded, and the vocabulary needs to be updated as well, so probably the task has to be integrated with access control tasks.

**Comment by zzacharo** [comment]
The issue comes from the fact that access_right before was a vocabulary but now we deprecated the previous implementation and thus this file https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/vocabularies/access_right.py is not used anymore. The icon should be populated probably as part of the future `access_right` vocabulary.

**Comment by lnielsen** [comment]
Here's the first iteration for the new icons:

We rely on the [COAR access status vocabulary](http://vocabularies.coar-repositories.org/documentation/access_rights/). Here's a proposed mapping:

1. Open: 
  a. Public records **with public files**
2. Embargoed
  a. Public records **with restricted files under embargo**
  b. Restricted records **under embargo**
3. Metadata-only
  a. Public records **without files**
  b. Public records **with restricted files** (not under embargo)
4. Restricted
  a. Restricted records **with restricted files** (not under embargo)
  b. Restricted records **without files**

The ones I find a bit tricky is the case 2b. Should restricted records under embargo (with or without files) be displayed as embargoed. E.g. a restricted record without files under embargo, will first be classified as "Embargoed" and next "Metadata only".

![Screenshot 2021-02-09 at 14 05 45](https://user-images.githubusercontent.com/1698163/107368620-0d676d80-6ae1-11eb-8b39-f35e92aa91fb.png)

**Comment by lnielsen** [comment]
Issue is blocked until the core implementation has been finished.
