### ISSUE TITLE
Affiliation 'Name' field is auto-populated with the value entered in Creators and Contributors name fields

### ISSUE THREAD

**Issue by carsonicator** [inveniosoftware/invenio-app-rdm#492]
Package version (if known): December release

## Describe the bug

Affiliation 'Name' field is auto-populated with the value entered in Creator’s 'Family Name' and 'Given Name' fields (also occurs for Contributor’s Affiliation name):

## Steps to Reproduce

1. Go to 'Uploads'.
2. Click on 'New upload'.
3. Scroll down to 'Creators' and type a 'Family Name' or a 'Given Name' that has been used previously on the same machine.
4. Scroll down to 'Contributors' and type a 'Family Name' or a 'Given Name' that has been used previously on the same machine.
5. See error.

## Expected behavior

Autocomplete for Affiliations 'Name' should not suggest 'Family Name' and 'Given Name' from Creators or Contributors.

## Screenshots (if applicable)

Results for 'Creator' Affiliation autocomplete:

<img width="891" alt="Screen Shot 2021-01-28 at 5 59 03 PM" src="https://user-images.githubusercontent.com/11506832/106214261-0f9e0380-6194-11eb-92e2-1651d70eff5e.png">

Results for 'Contributor' Affiliation autocomplete:

<img width="877" alt="Screen Shot 2021-01-28 at 5 59 48 PM" src="https://user-images.githubusercontent.com/11506832/106214273-14fb4e00-6194-11eb-850b-65d2190b0087.png">

**Comment by fenekku** [comment]
Fixed / could not reproduce anymore.
