### ISSUE TITLE
customization: css 

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#5]
Support loading/adding custom CSS

**Comment by ppanero** [comment]
Made to work in debug mode. Steps to follow:

1. Install `invenio-app-rdm`. 
2. Edit the `config.py` and add:

``` python
from invenio_app.config import APP_DEFAULT_SECURE_HEADERS

APP_DEFAULT_SECURE_HEADERS['content_security_policy'] = {}
WEBPACKEXT_STORAGE_CLS = 'pywebpack.storage.LinkStorage'
```
3. Install `invenio-assets` from GitHub master branch.
    - Edit the `invenio_assets/assets/build/webpack.config.js` and add:

``` javascript
var webpackConfig = {
  ...
  resolve: {
    ...
    symlinks: false
  },
...
}
```

4. Since `--watch` does not work with symlinks we need to edit `DirectoryWatcher.js`. Edit `<instance_path>/assets/node_modules/watchpack/lib/DirectoryWatcher.js`

``` javascript

function DirectoryWatcher(directoryPath, options) {
        ...
	this.watcher = chokidar.watch(directoryPath, {
                ...
		followSymlinks: true,
```

5. Open two terminals: In each one of them export:
     - `FLASK_ENV=development`
     - `NODE_PRESERVE_SYMLINKS=1`

6. In Terminal 1 run:
``` console
./scripts/bootstrap
./scripts/setup
 invenio run --cert ./docker/nginx/test.t --key ./docker/nginx/test.key 

7. In Terminal 2 run:

``` console
invenio webpack run start
```

Starting implementing the changes in the correct places.

Kudos @slint for the guidelines and work :)

**Comment by slint** [comment]
Since it's not sure if more changes are coming, I've made [the `webpack-fixes` WIP branch](assets` https://github.com/inveniosoftware/invenio-assets/tree/webpack-fixes) in `invenio-assets`, which can be checked out and contains part of the changes

**Comment by ppanero** [comment]
@slint Thanks! I added a comment here: https://github.com/inveniosoftware/invenio-assets/commit/094c1ef4d0c67b46ab890d8303d51bab1782ba55

The most problematic might be point 4.

- `followSymlinks` was added on watchpack (see https://github.com/webpack/watchpack/pull/114). However, it is not compatible with webpack **4** (it cannot be set from there) and as stated here https://github.com/webpack/webpack/issues/6845 it will come with webpack **5**... 

Thoughts?

**Comment by zzacharo** [comment]
For making it work on macos I had to change unfortunately another line in the `DirectoryWatcher.js`:

```js
function DirectoryWatcher(directoryPath, options) {
        ...
	this.watcher = chokidar.watch(directoryPath, {
                ...
		followSymlinks: true,
                 depth: 1,

```

Seems that on macos if you don't increase the depth of the traversed subdirectories changes are not detected. I have opened a ticket https://github.com/webpack/watchpack/issues/141 to understand if this is something is known and fixed in the latest beta version.

**Comment by lnielsen** [comment]
Isn't this solved by #55 ?

**Comment by zzacharo** [comment]
@lnielsen if we move the information on how to you can make webpack work locally in another issue this one can be closed! I will create an issue and I will close it!

**Comment by zzacharo** [comment]
Created this https://github.com/inveniosoftware/invenio-app-rdm/issues/65 out of the information here!
