### ISSUE TITLE
styling: footer is covering body content

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#511]
### Steps
1. Go to e.g. a setting page - https://127.0.0.1:5000/account/settings/profile/
2. Resize the browse to a small window.
3. See that the footer is covering the body content (see screenshot)

![Screenshot 2021-02-02 at 11 00 29](https://user-images.githubusercontent.com/1698163/106583983-f5727580-6545-11eb-848d-a2d41bd8c0cb.png)

**Comment by mb-wali** [comment]
The issue appears only on **safari** browser.
