### ISSUE TITLE
list uploads: align page with mockups

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#515]
4 tasks:

1. The search box should say "Search uploads" instead of search.
2. Sort by dropdown should be added (see also https://github.com/inveniosoftware/invenio-rdm-records/issues/354)

![Screenshot 2021-02-02 at 11 40 38](https://user-images.githubusercontent.com/1698163/106589446-5309c080-654c-11eb-92eb-f873629dff00.png)

3. Move pagination outside the box and use ``mini`` size. Expected result:

![Screenshot 2021-02-02 at 11 52 45](https://user-images.githubusercontent.com/1698163/106590226-2ace9180-654d-11eb-8852-c307bded347b.png)

4. Move "X results found" - See screenshot:
![Screenshot 2021-02-02 at 11 57 42](https://user-images.githubusercontent.com/1698163/106590950-f7d8cd80-654d-11eb-8961-99c00b5ca9ad.png)

**Comment by fenekku** [comment]
Does 4. replace "Select all" or should it be right of it?
