### ISSUE TITLE
landing page: make JSON export return the record's JSON 

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#523]
Now that only JSON is exported on the landing page, a JSON representation of the record should actually be exported.

**Comment by lnielsen** [comment]
Example from Zenodo: 

- https://zenodo.org/record/4485744/export/json
- https://github.com/zenodo/zenodo/blob/master/zenodo/config.py#L748-L810
- https://github.com/zenodo/zenodo/blob/master/zenodo/config.py#L820-L827
