### ISSUE TITLE
form: subjects field

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#533]
From https://github.com/inveniosoftware/invenio-app-rdm/issues/459

### Subjects
- Autocompletion input field
- Have an inline dropdown with the `limit to` options (Guillaume: I am unclear about what is meant here)
- Autocompletion should filter by the `limit to` parameter (Ensure is the case now)
- Guillaume: At Northwestern, we've suddenly had people asking for subjects and keywords split. I don't agree with it, but I don't understand why (we are investigating).
- Guillaume: How should the `limit to` behave when terms from a vocabulary have been chosen and a different vocabulary is now selected for `limit to`: I think the chosen terms should always be shown and only the terms in the dropdown be filtered (but for a while that was not the case). 
    - Zach: I agree with that! The `limit to` should control only the suggestions you get. The chosen items are not affected. The only potential confusion I see is the following:
        - User has `limit to` option to "Filter from A"
        - Searches a term that is not in A, but maybe in B
        - Subject component allows additions if not found
        - User adds their suggestion
        - Now we end up with a custom choice even though the term could be found in the B collection. 
            - Custom terms might need some "smart" cleanup.

**Comment by fenekku** [comment]
closed via https://github.com/inveniosoftware/invenio-app-rdm/pull/925 as well
