### ISSUE TITLE
form: display errors with consistent message styling

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#534]
The "flash messages" used for display errors should be used consistently throughout the side.

The deposit form error messages are currently shown as below:
![Screenshot 2021-02-03 at 14 12 12](https://user-images.githubusercontent.com/1698163/106751846-0f858400-662a-11eb-8b58-2325ad7fba1f.png)

# Expected behavior

The error message should be displayed in a similar style yo below:

![Screenshot 2021-02-03 at 14 12 39](https://user-images.githubusercontent.com/1698163/106751849-10b6b100-662a-11eb-8248-e4cee1f07a4d.png)

The warning message should be shown below the header, and if possible sticky, so that when you scroll down it stays on the top. It has to be seen how this plays with the sticky right sidebar with the buttons

**Comment by fenekku** [comment]
This issue is included in this one essentially: https://github.com/inveniosoftware/invenio-app-rdm/issues/451
