### ISSUE TITLE
search: phrase search is not working 

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#559]
Package version (if known): <version>

## Steps to Reproduce
1. Go to https://127.0.0.1:5000/search?q=&p=1&s=10&sort=bestmatch
2. Type ``"open science"`` in the search field and hit enter.
3. Copy/paste the URL (should match ``https://127.0.0.1:5000/search?q=%22open%20science%22&p=1&s=10&sort=bestmatch``)
4. Paste the URL in the browser address bar and hit enter.

See that ``"open science"`` changed to ``open science`` (i.e. without quotes).

![bug](https://user-images.githubusercontent.com/1698163/107992248-96e2d800-6fd8-11eb-9471-203f17489581.gif)

**Comment by ntarocco** [comment]
Here the bug in RSK: https://github.com/inveniosoftware/react-searchkit/issues/176

**Comment by mb-wali** [comment]
fixed with https://github.com/inveniosoftware/react-searchkit/pull/177
