### ISSUE TITLE
theme: header does not have consistent spacing on search/uploads page

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#562]
Package version (if known): <version>

## Steps to Reproduce
1. Go to 'https://127.0.0.1:5000/uploads'
2. Go to 'https://127.0.0.1:5000/search'
3. Compare the spacing between the search field and "Uploads" menu item and see that it's different.

## Screenshots (if applicable)

![Screenshot 2021-02-16 at 02 56 16](https://user-images.githubusercontent.com/1698163/108009424-f7870a80-7002-11eb-9c48-724fb6c44771.png)
![Screenshot 2021-02-16 at 02 56 22](https://user-images.githubusercontent.com/1698163/108009425-f81fa100-7002-11eb-8a01-0342491ba779.png)

**Comment by max-moser** [comment]
on `/uploads`, there an extra empty `<li>` tag appears:

![image](https://user-images.githubusercontent.com/6437519/108269006-a8a9b400-716d-11eb-8cf4-2bc001067792.png)
