### ISSUE TITLE
search: correctly report "invalid query syntax" errors to users

### ISSUE THREAD

**Issue by mb-wali** [inveniosoftware/invenio-app-rdm#569]
Package version (if known): <version>
invenio-app-rdm v0.20.1 
## Describe the bug
searching for some phrases that are not allowed by ```elasticsearch``` the UI throws unknown error.

## Steps to Reproduce
1. Go to './search'
2. Type in the search bar ```"Open Science ```
2. Click on 'search button'
3. See error

**Stacktrace**
```
  File "/home/unix/projects/latest_base/lib/python3.8/site-packages/elasticsearch/transport.py", line 381, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/home/unix/projects/latest_base/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 273, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/unix/projects/latest_base/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 322, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'Failed to parse query ["Open Science]')
```

**UI**
![error-ui](https://user-images.githubusercontent.com/44528277/108359522-64abc300-71f0-11eb-8115-8432602cddbc.png)

## Expected behavior
![expected-err](https://user-images.githubusercontent.com/44528277/108359535-67a6b380-71f0-11eb-8496-507a942990b0.png)

**Comment by chriz-uniba** [comment]
@mb-wali do you think that my search of an urn `urn:nbn:de:bvb:473-opus-1130` has the same error-reason, or would I need to open a new issue:

![image](https://user-images.githubusercontent.com/74763324/122907907-e30da280-d353-11eb-9728-c71e7f5f3e3d.png)

this is the current demo-version (https://inveniordm.web.cern.ch/search?q=urn%3Anbn%3Ade%3Abvb%3A473-opus-1130&p=1&s=10&sort=bestmatch) - I guess it is invenioRDM-v4

**Comment by mb-wali** [comment]
> @mb-wali do you think that my search of an urn `urn:nbn:de:bvb:473-opus-1130` has the same error-reason, or would I need to open a new issue:
> 
> ![image](https://user-images.githubusercontent.com/74763324/122907907-e30da280-d353-11eb-9728-c71e7f5f3e3d.png)
> 
> this is the current demo-version (https://inveniordm.web.cern.ch/search?q=urn%3Anbn%3Ade%3Abvb%3A473-opus-1130&p=1&s=10&sort=bestmatch) - I guess it is invenioRDM-v4

Yes, it is the same error: the elasticsearch is throwing an exception error which explains that the giving query cannot be executed for this and that reason. we should catch these exceptions and give a user a nice response to the actual error.

**Comment by lnielsen** [comment]
The REST API side of things have been fixed, but the frontend part is missing to report 400 errors properly:

![Screenshot 2021-08-04 at 23 27 00](https://user-images.githubusercontent.com/1698163/128257129-bdcaa9e2-1604-4dbb-80cc-e5cdd7b22445.png)

**Comment by fenekku** [comment]
closed via https://github.com/inveniosoftware/invenio-app-rdm/pull/1074 (well when merged into master)
