### ISSUE TITLE
customization: templates

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#6]
Support customizing UI using some templating mechanism (e.g. Jinja), from the `templates` folder created by the `init` command of invenio-scripts (https://github.com/inveniosoftware/invenio-scripts/issues/2).

**Comment by fenekku** [comment]
Related to https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/14

**Comment by fenekku** [comment]
Closing since taken care by: https://github.com/inveniosoftware/invenio-app/blob/master/invenio_app/factory.py#L67-L76
