### ISSUE TITLE
Deleting a record from admin panel.

### ISSUE THREAD

**Issue by mb-wali** [inveniosoftware/invenio-app-rdm#60]
Deleting a record from the admin panel will delete only the ```json``` field from table ```records_metadata```, and the references and other fields are not deleted.

see screenshot 1 for the admin panel delete icon.
After navigating back to the search page I am able to see the exact record in the list, see screenshot 2
once I click on record i get this error see screenshot 3

* 1
![#1](https://user-images.githubusercontent.com/44528277/73742077-e5199600-474b-11ea-8518-b160980cc443.PNG)

* 2
![#2](https://user-images.githubusercontent.com/44528277/73742084-e945b380-474b-11ea-84d6-a163c6e3d73e.PNG)

* 3
![#3](https://user-images.githubusercontent.com/44528277/73742096-ee0a6780-474b-11ea-9d62-f0063901bc37.PNG)

**Comment by lnielsen** [comment]
We're tracking work related to an admin interface in https://github.com/inveniosoftware/product-rdm/issues/28. The invenio-admin panel is not useful and we should likely disable the interface completely.
