### ISSUE TITLE
Input elements (e.g. Preview & Download buttons) seem to be unresponsive when out of bounds

### ISSUE THREAD

**Issue by max-moser** [inveniosoftware/invenio-app-rdm#645]
Package version (if known): 0.20.9

## Describe the bug
Input elements (e.g. buttons and links) seem to become unresponsive if they're placed too far to the right.
It seems that elements lose their interactivity once they go "out of bounds" of their container.

## Steps to Reproduce
1. Create and publish a record with files (with very long file names)
2. Visit the record's landing page
3. Try to preview another file
4. See that the buttons aren't clickable, and the file name (link) becomes unclickable after moving out of bounds (see screenshot)

## Expected behavior

The elements remain interactive, regardless of their position (maybe the text should be line-wrapped?)

## Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/6437519/109292757-271beb00-782b-11eb-8daa-dcce5d632595.png)

**Comment by fenekku** [comment]
closed via https://github.com/inveniosoftware/invenio-app-rdm/pull/1073
