### ISSUE TITLE
List uploads: split in  unpublished, published, draft

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#649]
We want to split the record/draft status per search page as follows:

- Search page
  - Records should have a `status == published` and `is_published == True`.
- Uploads page - records status
  - `published`: records that are published and have no draft. (`is_published == True`)
  - `draft`: records that are published but have an active draft i.e being edited. (`is_published == True`
  - `unpublished`: new drafts with no associated published records. `is_published == False`

**Comment by fenekku** [comment]
Exchanging ideas here about the uploads page...

What about keeping draft and unpublished together? I am wondering about the benefit of keeping them separate. There seems to be more work implementation-wise to separate them and then that's more to display to the user / more decision for them to make/remember.

What about making the published records just be all records that are... published (period)? That tweak was notoriously confusing to our users when using the framework directly. They would think their published record was back to a draft only. 

Drafts would just be drafts. 

 An indicator and/or link to draft/published record would make clear the respective published record/draft.

**Comment by zzacharo** [comment]
Eventually, after discussing with @lnielsen we will go for:

- `Published` records or drafts or published records
- `New` drafts of not published records i.e new drafts
