### ISSUE TITLE
webpack: assets development

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#65]
Made to work in debug mode. Steps to follow:

1. Install `invenio-app-rdm`. 
```console
export FLASK_ENV=development
invenio-cli install
invenio-cli update
invenio-cli services
invenio-cli demo
```
2. In one terminal  run:
``` console
export FLASK_ENV=development
invenio-cli run
```
3. In another terminal run:
``` console
export FLASK_ENV=development
invenio webpack run start
```

Starting implementing the changes in the correct places.

**NOTE 1**:  Seems that on macos if you don't increase the depth of the traversed subdirectories changes are not detected. I have opened a ticket https://github.com/webpack/watchpack/issues/141 to understand if this is something is known and fixed in the latest beta version.

**NOTE 2**: `followSymlinks` was added on watchpack (see https://github.com/webpack/watchpack/pull/114). However, it is not compatible with webpack **4** (it cannot be set from there) and as stated here https://github.com/webpack/webpack/issues/6845 it will come with webpack **5**... 

Credits also to @slint and @ppanero :)

**Comment by zzacharo** [comment]
## [DRAFT] Develop locally react-searchkit(invenio react libraries)

Let's take for example the local development of `react-searchkit` in invenio:

1. Follow the steps above to work on a local setup
2. Go to you local repo of `react-searchkit` and run the commands:
```console
npm run link-dist && npm run watch
```
3. Rerun the command `invenio webpack run start`

**NOTE 1**: The react-searchkit commands are part of this [react-searchkit/pr/107][https://github.com/inveniosoftware/react-searchkit/pull/107].

**NOTE 2**: The react-searchkit commands can be used in all invenio react libraries so we can standarize the way we develop.

**Comment by ppanero** [comment]
@zzacharo This has been fixed with the latest invenio-cli right?
