### ISSUE TITLE
service: provide a way to check permissions in a result item

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#650]
Currently, in order to apply permissions in a result item we need to do something like `result_item._record.access`. We should avoid accessing the `_record` from the presentation layer!

The problem raised from the fact that the permission_policy requires a record to check against but checking for permissions in views is dealing with a result item i.e output of a service action e.g `service.read(...)`. 

See 
- https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/records_ui/views/decorators.py#L140
- https://github.com/inveniosoftware/invenio-records-permissions/blob/master/invenio_records_permissions/policies/base.py#L86
- https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/services/generators.py#L93

**Comment by fenekku** [comment]
:+1: the record_item (result of service operations) should provide a public interface to the permissions analysis tailored to the originating identity e.g. 

```
>>> record_item.to_dict()
{
  ...,
  "permissions": ["can_read", "can_update", "can_read_files"]
}
```

**Comment by fenekku** [comment]
went another way :)
