### ISSUE TITLE
permissions: implement proper permission policy for draft vs record files

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#662]

**Comment by fenekku** [comment]
In records-resources, there is:

`self.require_permission(identity, "read_files", record=record)` 

(and their variations) embedded in many methods.

A way would be to override these methods in drafts-resources, copy the code wholesale and only change the `require_permission`:

`self.require_permission(identity, "read_draft_files", record=record)`

**Comment by lnielsen** [comment]
replaced by inveniosoftware/invenio-rdm-records#498
