### ISSUE TITLE
landing-page: localize EDTF dates

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#663]
- [ ] EDTF dates are not localised
- [ ] ~~Display human-readable labels when needed~~

**Comment by fenekku** [comment]
splitting the human-readable labels on a case by case basis so they are actionable.

**Comment by lnielsen** [comment]
@mb-wali Can I ask you to verify this ticket? 

In principle this should have been fixed via this: https://github.com/inveniosoftware/marshmallow-utils/blob/master/marshmallow_utils/fields/babel.py#L119

**Comment by mb-wali** [comment]
> @mb-wali Can I ask you to verify this ticket?
> 
> In principle this should have been fixed via this: https://github.com/inveniosoftware/marshmallow-utils/blob/master/marshmallow_utils/fields/babel.py#L119

So far I can see it's localized the strings, not the numbers. I am not sure if we are targeting the numbers also or not.
**Some screenshots**

*English*
![english-edtf](https://user-images.githubusercontent.com/44528277/128483506-8a317d78-5e99-438d-8619-e98f08283745.png)

*German*
![german-edtf](https://user-images.githubusercontent.com/44528277/128483536-df978551-4d2e-4aa1-8ac4-c4efc9283c48.png)

*Farsi* 
![farsi-edtf](https://user-images.githubusercontent.com/44528277/128483659-3839e045-df92-4317-bfd7-51098f1d5d62.png)

**Comment by lnielsen** [comment]
Thanks a lot. I'm closing since as discussed in thechat Babel doesn't support number formatting :-(
