### ISSUE TITLE
landing-page: add title tag

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#666]
The Jinja template doesn't have access to a `{{ title }}` or equivalent variable that it would place in the title block. Just providing the `title` variable is enough as the parent template of the landing page already tries to place it in the HTML `<title></tilte>` element.

**Comment by audrium** [comment]
@zzacharo, why is it needed?
Parent template currently displays [config.THEME_SITENAME](https://github.com/inveniosoftware/invenio-theme/blob/f8818f4cd87462621052f62fb28ad71f552427b6/invenio_theme/templates/invenio_theme/page.html#L26) as a title, so it can be controlled from `invenio-app-rdm `. Or is there a use case for a separate title config?

**Comment by lnielsen** [comment]
- https://inveniordm.web.cern.ch/uploads - "Uploads"
- https://inveniordm.web.cern.ch/uploads/new - "New upload/Edit upload/New version" i.e. same as headline on page.
- https://inveniordm.web.cern.ch/search - "Search results"
