### ISSUE TITLE
data fixtures: allow instance to override fixtures.

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#668]
Implement a way for users to be able to override the available fixtures currently placed in https://github.com/inveniosoftware/invenio-rdm-records/tree/master/invenio_rdm_records/fixtures.

The goal is for these fixtures to be available when a user cookiecutters a new instance so they can change according to their preferences. To achieve that, we need to implement a way of loading these fixtures dynamically from user's instance.

**Comment by fenekku** [comment]
related to: https://github.com/inveniosoftware/invenio-rdm-records/issues/425
