### ISSUE TITLE
Allow filtering by embargoed records

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#694]
At NU, some people voiced desire to facet by embargoed records. (they were suggesting it as a nice-to-have)

**Comment by lnielsen** [comment]
Possible now:
![Screenshot 2022-02-09 at 11 28 03](https://user-images.githubusercontent.com/1698163/153179651-1df964aa-fb8e-4838-81fc-02c692721ec1.png)
