### ISSUE TITLE
Display human-readable text for 'Related works' in record view

### ISSUE THREAD

**Issue by carsonicator** [inveniosoftware/invenio-app-rdm#695]
Package version (if known): February release

## Describe the bug
When viewing record after publishing, the details table does not show human-readable text for 'Related works' information.

## Steps to Reproduce
1. Create a record.
2. Scroll down and add content to 'Related works'.
3. Save a draft and publish the record.
4. View the record.

## Expected behavior
Human-readable text is displayed for all fields.

## Screenshots (if applicable)

_Example 1, record creation page:_
<img width="794" alt="Screen Shot 2021-03-12 at 11 41 55 PM" src="https://user-images.githubusercontent.com/11506832/111020691-61d66500-838d-11eb-816c-d2445fd25304.png">

_Example 1, viewing record:_
<img width="801" alt="Screen Shot 2021-03-12 at 11 38 44 PM" src="https://user-images.githubusercontent.com/11506832/111020710-79155280-838d-11eb-8987-18ab1cc506a0.png">

_Example 2, record creation page:_
<img width="800" alt="Screen Shot 2021-03-12 at 11 41 28 PM" src="https://user-images.githubusercontent.com/11506832/111020694-669b1900-838d-11eb-96e8-feff4b9c7047.png">

_Example 2, viewing record:_
<img width="810" alt="Screen Shot 2021-03-12 at 11 39 25 PM" src="https://user-images.githubusercontent.com/11506832/111020706-73b80800-838d-11eb-9538-b0aaac563859.png">

**Comment by fenekku** [comment]
Don't *think* this was meant to be placed in Auth team, but just added it in QA team board in case :)

**Comment by carsonicator** [comment]
This behavior is also seen in the April release.
