### ISSUE TITLE
list uploads: all versions filter not working

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#722]
![Screenshot 2021-03-24 at 14 05 43](https://user-images.githubusercontent.com/1698163/112315403-66165280-8caa-11eb-9ee8-a025e4081514.png)

- Create a versions facet to filter between all or latest versions for both 1) search and 2) list uploads page

- [x] backend see https://github.com/inveniosoftware/invenio-drafts-resources/pull/128
- [ ] frontend

**Comment by fenekku** [comment]
This task is about making the search only show the latest version by default.
