### ISSUE TITLE
deposit: resource type field doesn't show the value for type publication

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#728]
Package version (if known): latest

## Describe the bug
In the deposit form, the `resource_type` field for type `publication` doesn't show the value if there is no subtype. This is happening because the component always expects a subtype to exist. On the other hand, the `invenio-rdm-records.cli` allows the generation of resource type `publication` without subtype.

## Steps to Reproduce
1. Go to '/uploads/'
2. Find a demo record with `type: publication` (See the `Publication` value in the badge of the search results )
3. Click the `Edit` button of the result
4. See the `Resource type` field being empty.

## Expected behavior

The resource type component should either generate an option of `type: publication` without a subtype or the cli should not generate records with resource type `publication` and no subtype.

## Additional context
The cli allows the publication type generation because facets weren't working properly. For more information refer to @fenekku probably :)

**Comment by ppanero** [comment]
This has been solved

![Screenshot 2021-06-07 at 14 44 54](https://user-images.githubusercontent.com/6756943/121018616-ed01a400-c79e-11eb-8a1c-1ae6cbef0de5.png)
![Screenshot 2021-06-07 at 14 46 25](https://user-images.githubusercontent.com/6756943/121018812-23d7ba00-c79f-11eb-8ec4-346a15dbb1d2.png)
