### ISSUE TITLE
landing page: caption of the preview box does not change

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#735]
Package version (if known): <version>

## Describe the bug

Preview: The caption of the preview box does not change when selecting another file for the preview.

## Steps to Reproduce

1. Upload and publish a new record with two files.
2. On the landing page, click preview of the first file, then the next. 
3. Observe that the filename in the previewbox does not change.

## Expected behavior

The filename in the previewbox should display the file being previewed.

**Comment by fenekku** [comment]
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/642 ;
Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/74
