### ISSUE TITLE
deposit form: publish button disabled if files are missing

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#736]
Package version (if known): <version>

## Describe the bug

Missing files: If files are missing to be uploaded, the publish button is disabled, but there is no feedback to the end-user that files are missing.

## Steps to Reproduce

1. Start a new upload
2. Fill out all required fields in the deposit form (do not upload a file).
3. Click save, and observe that the message says "Record successfully saved" and that the "Publish button" is disabled.
4. Now upload a file, or click the "Metadata-only record" checkbox

## Expected behavior

- As long as the draft is not publishable, the message should be a warning (not green saying successfully saved).
- As a user, I expect to see a message that files are missing to be uploaded (or that i need to check the "metadata only" checkbox.

**Comment by fenekku** [comment]
duplicate of https://github.com/inveniosoftware/invenio-app-rdm/issues/456 (close both when done)
