### ISSUE TITLE
deposit form: language vocabulary search results are not ranked properly for the query.

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#738]
Package version (if known): <version>

## Describe the bug

Languages: The language vocabulary search results are not ranked properly for the query. For instance searching for "english" will show less relevant results first.

## Steps to Reproduce

1. Start a new upload
2. Go to the languages field and try to search for english
3. Observe that English option is not part of the results.

## Expected behavior

- I would expect when there's a direct match on the title, that the record shows up first.
- I would expect to be able to see more options  - e.g. scroll through them.

## Additional context

- Implementation done for Records-REST: https://github.com/inveniosoftware/invenio-records-rest/pull/311
- Design discussion: https://codimd.web.cern.ch/TvrR3CJDTP-SZD75xC-sog

As for implementation, likely some generic parts have to go to Invenio-Records-Resources and other parts have to go to Invenio-Vocabularies.

- Invenio-Records-Resources: [QueryStrParam](https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/services/records/params/querystr.py)
- Invenio-Vocabularies: [VocabularyServiceConfig](https://github.com/inveniosoftware/invenio-vocabularies/blob/master/invenio_vocabularies/services/service.py#L28)

My thinking is that you can likely in your service config specify the fields to boost - something along the lines of:

```
class SearchOptions:
    # ...
    query_boost_fields = ["field1^5", "field2^2", ...]
```

**Comment by fenekku** [comment]
@lnielsen I am leaving that one for you to review - it would take me time to get up to speed with this.
