### ISSUE TITLE
record landing page: does not show version number 1 for two different versions

### ISSUE THREAD

**Issue by cfgamboa** [inveniosoftware/invenio-app-rdm#744]
After upgrading  from V1 to V2. 

## Describe the bug
The record shows  two versions with the same  number
<img width="1184" alt="Screen Shot 2021-03-29 at 8 42 01 PM" src="https://user-images.githubusercontent.com/30438971/112917011-c86abb00-90cf-11eb-8c4b-7ff4e8d0fc50.png">

**Comment by fenekku** [comment]
Oh strange. @cfgamboa Can you provide the exact steps you took to get this? e.g. 
1- created a record 
2- Clicked on "Edit" on landing page 
3- Clicked on "New Version" in Edit page
...

Thanks!

**Comment by cfgamboa** [comment]
1. Created a test record  on invenioV1.
2. Upgraded the local instance to invenioV2 ([upgrade_log_v1_v2.pdf](https://github.com/inveniosoftware/invenio-app-rdm/files/6232420/upgrade_log_v1_v2.pdf)
3. Edited the test record [1] by creating a new version. I have added another file.

**Comment by lnielsen** [comment]
Needs also an update to the documentation page with a note on how to fix an already migrated repository.
