### ISSUE TITLE
Frontpage links are broken (404)

### ISSUE THREAD

**Issue by chriz-uniba** [inveniosoftware/invenio-app-rdm#759]
Package version (if known): 

invenio-cli 0.23.0
InvenioRDM v2.0
Instance: https://inveniordm.web.cern.ch/ 2021-04-07

## Describe the bug

At least two links on the frontpage are not working (404 Not Found - https://inveniordm.docs.cern.ch/develop/make_it_your_own/ ).

## Steps to Reproduce
1. Go to https://inveniordm.web.cern.ch/
2. Click on "configuration section in the docs. " (Point 1)
3. See error: The current linked page is https://inveniordm.docs.cern.ch/develop/make_it_your_own/ which doesn't exist anymore, therefore giving a 404.

4. Go to https://inveniordm.web.cern.ch/
5. Click on "here" (Point 2)
6. See error: The current linked page is https://inveniordm.docs.cern.ch/develop/make_it_your_own/ which doesn't exist anymore, therefore giving a 404.

## Expected behavior

Seeing an existing documentation with information.
Something like https://inveniordm.docs.cern.ch/customize/ or https://inveniordm.docs.cern.ch/customize/styling/

**Comment by ppanero** [comment]
@ines-cruz 
1- Configure:
    - https://inveniordm.docs.cern.ch/develop/make_it_your_own/ --> https://inveniordm.docs.cern.ch/install/configuration/
2- Customize:
    - https://inveniordm.docs.cern.ch/develop/make_it_your_own/ --> https://inveniordm.docs.cern.ch/customize/styling/
3- Seems alright

**Comment by ppanero** [comment]
@chriz-uniba We are working on fixing them. Please note that even if this issue has been fixed, said fixes might take a bit to reach the actual website due to the deployment cycle. Thanks for reporting!
