### ISSUE TITLE
Not able to preview files with a '.txt' extension

### ISSUE THREAD

**Issue by carsonicator** [inveniosoftware/invenio-app-rdm#767]
Package version (if known): Since March release (v2.0) . Still valid as of v5.0

## Describe the bug
When adding a text file with a .txt extension to a record, selecting the 'Preview' option, then publishing the record, there is no preview of the file content. 

## Steps to Reproduce
1. Go to 'Uploads'.
2. Click on 'New upload'.
3. Add content and upload a .txt file and check the box next to this file to enable the preview.
4. Save draft.
5. Publish record.
6. View the record and see no preview.

## Expected behavior
Should be able to preview .txt file content.

## Screenshots (if applicable)
**v5.0**
![image](https://user-images.githubusercontent.com/1932651/126791115-d7fe443d-86e0-4d22-b636-4c4e5cad2120.png)

**v2.0**
<img width="794" alt="Screen Shot 2021-04-08 at 12 06 51 PM" src="https://user-images.githubusercontent.com/11506832/114108418-ac69d500-9898-11eb-9894-6991837a6693.png">

**Comment by carsonicator** [comment]
This behavior is also seen in the April release (v3.0)

**Comment by lnielsen** [comment]
Confirmed in latest v5.0. Needs a previewer for text (should simply render as plain text)
