### ISSUE TITLE
rest: enable CSRF validation in REST API

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#778]
- Set ``REST_CSRF_ENABLED = True`` in ``config.py``.
- Read and follow instructions. 
- Test thoroughly the impact.

**Comment by ppanero** [comment]
ILS checklist: https://github.com/inveniosoftware/invenio-app-ils/issues/867
Docs pending issue: https://github.com/inveniosoftware/invenio-rest/issues/113

**Comment by ppanero** [comment]
- Share
- Edit
- New version
- Publish
- Save
- Preview
