### ISSUE TITLE
deposit form: re-enable language field in additional titles/descriptions

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#781]
**Blocked as of 2021-04-23**

This task requires:
- changing react-invenio-deposit to save `additional_titles[].lang = {id: <suggest id>}` (same for additional description)
- changing invenio-rdm-records to have the schema accept this change and the data layer relations field to dereference the localized language correctly -- :warning: this step is the blocker because the structure: `id` of attribute (`lang`) of array element for field (`additional_titles`) is not supported right now
- changing invenio-app-rdm to display the human readable localized language (`invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html`)

Draft WIP PRs have been made in those repos but they should not be merged.

**Comment by fenekku** [comment]
**blocked**

For `https://127.0.0.1:5000/api/vocabularies/languages?q=engl&size=20`, the languages endpoint is returning:

```json
{
  "hits": {
    "hits": [], 
    "total": 0
  }, 
  "sortBy": "bestmatch", 
  "aggregations": {}, 
  "links": {"self": "https://127.0.0.1:5000/api/vocabularies/languages/?page=1&q=engl&size=20&sort=bestmatch"}}
```
(notice that the `links.self` has a typo too making the link invalid)

Environment:
- `http://localhost:9200/vocabularies-vocabulary-v1.0.0-1619035738/_search` returns language hits though e.g. 
```
{

    "_index": "vocabularies-vocabulary-v1.0.0-1619035738",
    "_type": "_doc",
    "_id": "1d604d93-3794-4117-85c2-9c83894e4510",
    "_score": 1.0,
    "_source": {
        "$schema": "local://vocabularies/vocabulary-v1.0.0.json",
        "type": {
            "id": "languages",
            "pid_type": "lng"
        },
        "tags": [
            "individual",
            "living"
        ],
        "title": {
            "en": "Armenian Sign Language"
        },
        "id": "aen",
        "pid": {
            "pk": 100,
            "pid_type": "lng",
            "status": "R",
            "obj_type": "rec"
        },
        "uuid": "1d604d93-3794-4117-85c2-9c83894e4510",
        "version_id": 2,
        "created": "2021-04-21T20:09:14.946286+00:00",
        "updated": "2021-04-21T20:09:14.966377+00:00"
    }

},
``` 

- invenio-vocabularies master
- invenio-app-rdm master
- invenio-records             1.5.0a4
- invenio-records-resources   0.14.8 

What could be causing this?

**Comment by lnielsen** [comment]
Note, you have to use ``suggest`` instead of ``q`` now for auto-complete use cases:

https://127.0.0.1:5000/api/vocabularies/languages?suggest=engl&size=20

**Comment by fenekku** [comment]
closed via https://github.com/inveniosoftware/invenio-app-rdm/pull/927 + https://github.com/inveniosoftware/invenio-app-rdm/pull/924
