### ISSUE TITLE
config: remove SITE_HOSTNAME

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#782]
The usage of ``SITE_HOSTNAME`` should be fully removed. It has been superseded by ``SITE_API_URL`` and ``SITE_UI_URL``.

This includes (but not limited to):

- Docs
  - Documentation should remove refeferences, and add the new variableas.
- Invenio-CLI
  - Invenio-CLI uses a trick to correctly set SITE_HOSTNAME - this should be used for new varaibles.
- Invenio-RDM-Records
  - Secret links have not been refactored to new code (still using )

SITE_API_URL and SITE_UI_URL should

- end with :5000 for the local install (it does +1 )
- end without :5000 for the containerized install (it doesn't -1 )

**Comment by fenekku** [comment]
I've observed those as well when trying out the containerized setup :+1:
