### ISSUE TITLE
frontpage: add TU Wien logo

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#785]
Add it the frontpage of InvenioRDM and to https://inveniosoftware.org/products/rdm/

Ping Lars to get the logo.

**Comment by Pineirin** [comment]
I cannot link a pull request from other repository, so I will post here the pull request of the inveniosoftware.org part.
https://github.com/inveniosoftware/inveniosoftware.org/pull/156.
