### ISSUE TITLE
SITE_API_URL/SITE_UI_URL should not end with :5000 for containerized setup

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#786]
Package version (if known): april release

## Describe the bug

`SITE_API_URL` and `SITE_UI_URL` should 
- end with `:5000` for the local install (it does :+1: )
- end without `:5000` for the containerized install (it doesn't :-1: )

The docs should indicate that this change to the invenio.cfg is needed / maybe there is something to be done with the `invenio-cli containers start` command.

By default this causes cross-site errors (I thought we had done something for this in the past...)  

## Steps to Reproduce
1. Follow the containerized quick start / long start
2. Try to create a record
3. Get console error about cross-site posting

**Comment by lnielsen** [comment]
Part of #782
