### ISSUE TITLE
deposit form: publish button enabled for invalid form on new upload

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#788]
Package version (if known): <version>

## Steps to Reproduce

1. Go to 'https://127.0.0.1:5000/uploads/new'
2. Click on 'Metadata-only record'
3. See that the publish button is enabled (even though field has not been filled in).

## Expected behavior

That publish button is not enabled.

## Screenshot

![Screenshot 2021-04-22 at 11 48 50](https://user-images.githubusercontent.com/1698163/115694549-43d32b80-a361-11eb-8b3d-89c46bd73347.png)

**Comment by ppanero** [comment]
the reason is the fact that when going to preview it is saved, otherwise it is not. i.e. the publish button should not be active. Closing in favour of existing #794 (added to the board).
