### ISSUE TITLE
Move react-searchkit integration / theming to invenio-search-ui

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#79]
We have (or will have at time of writing) merged search integration and theming code here, but that code would be helpful to wider community by being in invenio-search-ui. It would also reduce the amount of custom code in this repository.

**Comment by lnielsen** [comment]
A lot of work has already been done here, and I'm closing the ticket. If there's pending work to do, it should be opened as specific issues.
