### ISSUE TITLE
deposit form: import files errors when being used on metadata-only records

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#793]
Package version (if known): <version>

## Steps to Reproduce
1. Create and publish a metadata-only record.
2. Create a new version of the metadata-only record.
3. Click on 'Import files'

![Screenshot 2021-04-23 at 08 32 30](https://user-images.githubusercontent.com/1698163/115828952-a33b4500-a40e-11eb-852d-fe3b88371f8f.png)

## Expected behavior

I expect that either 1) the import files is not shown or 2) an error message is displayed that the previous version is a metadata-only record.

**Comment by fenekku** [comment]
The solution already used for file upload in that same case is to precede the action with an API call to save the draft. This way the `files.enabled` is set correctly which allows subsequent action.
