### ISSUE TITLE
deposit form: publish button should be disabled until successful save and after changes

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#794]
## Steps to Reproduce

**Publish enabled before successful save**

0. Go to new uploads page
1. Fill out some fields
2. Notice that the publish button is enabled

**Publish enabled after change (without save)**

0. Go to new uploads page
1. Fill out all required fields
1. Click on 'Save draft' (all successful)
2. Change the title
3. See that publish is enabled.
5. Click on 'Publish'
6. See on the landing page that the changed title is not updated

## Expected behavior

I would expect e.g. the publish button not to be enabled 

- until I have saved a successful draft
- until after i have saved the title in step 3.

**Comment by fenekku** [comment]
Yes, no question about it in my mind :) 

My take is that we should operate with a `server_record` and a `working_record` on the frontend and whenever the server_record != `working_record`, the publish button should be disabled. But that should be part of the larger frontend discussion.

**Comment by ppanero** [comment]
Related to <https://github.com/inveniosoftware/react-invenio-deposit/pull/270> (React part)

When solving this check that the following cases were also solved:
#872
#873
#788

**Comment by ntarocco** [comment]
This [PR](https://github.com/inveniosoftware/react-invenio-deposit/pull/427) partially fixes the issue. See comment in the PR for more info.

**Comment by ntarocco** [comment]
The PR above is not an idea solution.
