### ISSUE TITLE
customization: plugins and extensions

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#8]
Support the usage of different:
- [ ] plugins (e.g. Storage via `invenio-s3`, `OCFL`).
- [x] extensions (e.g. `invenio-github`).

Note: via CLI or `invenio.cfg` (+`pipenv`) manual configuration.

**Comment by fenekku** [comment]
What is the difference we make between a plugin and an extension?

**Comment by ppanero** [comment]
**Plugin**: There is a specific API to be implemented, then it is "plugged-in" into an existing invenio-module (e.g. previewers, authentication, storage back-ends).

**Extension**: i.e. Flask extensions. For example GitHub, you can authenticate with it, but you can also do everything GitHub allows you to (e.g. via webhooks). For example list, add, etc. repositories. Therefore, it is a significant amount of code, without a defined API.

**Comment by fenekku** [comment]
These 2 things are the same for our purposes: just extension.

Each extension needs to document how/what needs to be loaded in the entrypoint and how the configuration needs to be set in the invenio.cfg (and sometimes that means importing and overriding in the invenio.cfg)
