### ISSUE TITLE
creation of 2 records with same DOI

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#847]
Package version (if known): April

Not 100% sure if this is "expected": it seems to be possible to create a record, get its DOI and paste it in the DOI field for a new record and create that record. Will need double-checking (from a report).

## Steps to Reproduce
1. Go to 'uploads/new'
2. Fill and publish
3. Copy generated DOI
4. Go to 'uploads/new'
5. Pass copied DOI into the "already have a DOI for this record field"
6. publish no problem

## Expected behavior
Emit error about duplicate DOI (unless this is indeed fine)

**Comment by ppanero** [comment]
It is "expected"/known issue because the deduplication was not merged last month... closing this since is duplicated and there is a PR <https://github.com/inveniosoftware/invenio-rdm-records/pull/592>
