### ISSUE TITLE
upgrade: test InvenioRDM 3.0 to 4.0

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/invenio-app-rdm#854]
Test upgrade InvenioRDM from 3.0 to 4.0 and update the docs section.

**Comment by fenekku** [comment]
Some details about resource type transition:

- resource types are now vocabulary records
- in the API and in storage they appear as `"resource_type": {"id": "image-photo"}`
- there is a script in invenio-rdm-records to convert csv fixture to yaml fixture. Administrators that were using custom resource types should run that script to convert their csv file first. Then run `invenio-cli services setup --no-demo-data` to load them in DB and ES. Then the migration script for this month needs to add a section to apply the structural change above (resource_type without id to resource_type with id).
