### ISSUE TITLE
citations generation: React app

### ISSUE THREAD

**Issue by ines-cruz** [inveniosoftware/invenio-app-rdm#867]
React app that displays the citation 
in Invenio-App-RDM add the citations style and the default citation style
That config should be fed to a React-App, that will use it to render the citation string as in the mockup in https://github.com/inveniosoftware/product-rdm/issues/17. When the App is loading it should display a placeholder.

**Comment by ines-cruz** [comment]
![citations1](https://user-images.githubusercontent.com/30771373/120661443-8face080-c488-11eb-9b9d-5ff132dbd29d.png)

**Comment by fenekku** [comment]
This was in pending review, but I think this is meant to be in progress. So I am moving it back there. I've added comments to the linked PRs to re-orient the approach :smile_cat:
