### ISSUE TITLE
deposit: can preview link not working

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#876]
Occasionally sharing a can-preview link for a record with restricted / embargoed files (with non-admin user) does not work.

**Comment by ppanero** [comment]
**Tested**
- Restricted record with embargoed files ✅ ([record](https://inveniordm-qa.web.cern.ch/records/dar71-0qe75) and [can_preview link](https://inveniordm-qa.web.cern.ch/records/dar71-0qe75?preview=1&token=eyJhbGciOiJIUzUxMiJ9.eyJpZCI6ImNjOGU5YTQ5LTMzOTItNGYzYS1hYWRmLTVjYTY0NzU3YTAxYiIsImRhdGEiOnt9LCJyYW5kb20iOiI2NmNlZjRhMmM2OGRmM2FhNGE0ZjgzOGRhYjgzMDlhOCJ9.l4K_sWrB8TI4Hi31ix48XzvHnLA4PoqYRKeFmYKYXksz8_MnKGeh8GQfjOKQ4y-pglSt5QJHfd6-Oz3oyMh6mg))
-

**Comment by saragon02** [comment]
I might be able to see the user's confusion. Whether I made my record restricted or embargoed, I received edit access when I used either the Edit or View links. The screen result once I logged in was identical, e.g.:

![EditResult_WithViewLink](https://user-images.githubusercontent.com/39839586/122281110-87549c80-ceaf-11eb-9fda-aa583d191b49.png)

When I used the Preview link, the result was this:

![PreviewResult_WithPreviewLink](https://user-images.githubusercontent.com/39839586/122281201-9f2c2080-ceaf-11eb-93fb-7b1101297c71.png)

With the latter, it's a little confusing to me that it says at the top: "You are previewing changes that have not yet been published". Is this the intention with the Preview link? These changes had been published.

**Comment by ppanero** [comment]
Hi @saragon02, I see your point now... I guess this has to do with the preview link using the same template than the *preview* functionality from the deposit form (which are not published). I opened an issue for that https://github.com/inveniosoftware/invenio-app-rdm/issues/909 Thanks!
