### ISSUE TITLE
Same header and footer as site in search page [semantic-ui transition]

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#88]
(we have purposefully deferred this task, but we need to not forget it)

As a user navigating the site, I want to have a consistent header / footer to help orient myself.
As a developer, I want to have 1 place to set the header/footer and know it is applied on all pages, so I am more efficient and address the above. 

By default, header/footer should be the same across pages, right now it isn't.

Now we have:

record page

![image](https://user-images.githubusercontent.com/1932651/75364255-09ffb580-5881-11ea-80f0-7f46773c93ed.png)

search page

![image](https://user-images.githubusercontent.com/1932651/75364300-1f74df80-5881-11ea-9110-9ecc6858d399.png)

(frontpage is different but that's fine)

**Comment by lnielsen** [comment]
This will be solved by migrating to Semantic UI.
