### ISSUE TITLE
communities: search shows all instance records

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#882]
Searching Communities lists all records in the Invenio instance

cc @slint @zzacharo

**Comment by slint** [comment]
This could be marked as a known issue, but in the end, it's just that we don't have the Communities records integration yet, and just wanted to have an example of how it would look like. If communities is enabled by default in the current release, The results in the page should be disabled.

**Comment by ppanero** [comment]
Added the tag. I created it because it was reported by Sara (Northwestern) from the usability test, I think the fact that the search was not 100% functional was not clear in the [v3 release notes](https://inveniordm.docs.cern.ch/releases/versions/version-v3.0.0/#communities-feature-preview).
