### ISSUE TITLE
Related works: urn - resource type invalid

### ISSUE THREAD

**Issue by chriz-uniba** [inveniosoftware/invenio-app-rdm#916]
Package version (if known): current (2021-06-22) invenioRDM at https://inveniordm.web.cern.ch --- I guess invenioRDM-v4

## Steps to Reproduce
1. Begin a new record: https://inveniordm.web.cern.ch, signup, login, and click New Upload
2. Fill metadata for required fields with valid input (step might not be needed)
3. Add 'related works':

Relation: `Is supplement to` Scheme: `URN` Identifier: `urn:nbn:de:bvb:473-opus-1130` Resource type: `Publication / Thesis`
4. Click: Save draft
5. See error

![image](https://user-images.githubusercontent.com/74763324/122909598-a5aa1480-d355-11eb-9223-22a2bf18be76.png)

![image](https://user-images.githubusercontent.com/74763324/122910560-9aa3b400-d356-11eb-927d-aaa1e6aca9f8.png)

## Expected behavior

Either: it is a valid resource type, then it should be saved.
Or: it is not a valid resource type, then a proper error message where you now see the empty speech bubble and I might want to be hindered to put resource types that are not valid in the first place.

By the way: which aren't valid and why?

**Comment by lnielsen** [comment]
This issue have now be fixed after we fixed the error reporting for related identifiers field.

![Screenshot 2021-08-04 at 23 52 06](https://user-images.githubusercontent.com/1698163/128260008-7a4974eb-788b-43c4-a60c-1587607fee51.png)
