### ISSUE TITLE
Affiliations frontend

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#919]
### Invenio-RDM-Records
- [x] Minimal subset of demo affiliations with the RDM partners
    - Missing Data Futures, Cottage Labs, OpenAire, GEO, National Center for Data to Health (cd2h)
    - See https://github.com/inveniosoftware/invenio-rdm-records/issues/681

### Invenio-App-RDM

- [x] Landing page: add display of human-readable labels
- [x] Search results: add display of human-readable labels if needed

### react-invenio-deposit

- [x] Work on widget for auto-suggesting.
- [x] Update relevant (de)serialization field react-invenio-deposit/src/lib/DepositRecordSerializer.js
- [x] Update relevant react component react-invenio-deposit/src/lib/components

**Comment by ppanero** [comment]
Landing page is working
![Screenshot 2021-06-28 at 11 13 32](https://user-images.githubusercontent.com/6756943/123611924-615dbf00-d802-11eb-946e-5cd474427091.png)

Search does not display any records... investigating...

**Comment by ppanero** [comment]
Miising ROR partners:
- Data Futures
- Cottage Labs
- OpenAire
- Calltech Library 
- GEO
- National Center for Data to Health (cd2h)

**Comment by tmorrell** [comment]
For Caltech Library we'd use https://ror.org/05dxps055. This does bring up a good UI use case. ROR won't get down to the department level, but sometimes researchers will want to add that. Will we allow modifications to how the affiliation is displayed on the record and retain the ROR, or will they be a separate vocabulary entry?

**Comment by ppanero** [comment]
@tmorrell Thanks for the ROR!

As for the use case... *for now* (emphasis on this hehe) affiliations are vocabularies, and only the original *name* (i.e. no translations) and the ROR id are dereferenced to ES. The rest (acronyms and localized titles) can be dereferenced from DB. This means:
- Search results can be customized to show the ROR or name (right now they don't show)
- Landing page can be customized to show something different (e.g. a localized title), it might require a tiny bit of work though.
