### ISSUE TITLE
template color palette

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#94]
Create variables for a color palette. For example:

- button primary
- button primary hover
- button secondary
- button secondary hover
- title
- subtitle
- text

This would be helpful to avoid situations like here where the black text is to bold. In the main page its a bit softer but it is done ad-hoc for that class.

![](https://user-images.githubusercontent.com/6756943/77451832-7d9bd080-6df5-11ea-9c34-3ca6d48d1c58.png)

Same goes for the buttons, etc.

**Comment by lnielsen** [comment]
We now have a ``brand-color`` as well as a [UX style guide](https://inveniordm.docs.cern.ch/maintenance/styleguide/). If there are any left-over things to do, new specific issues should be opened.
