### ISSUE TITLE
global: fix errors from npm audit (PRs in issue)

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#956]
When you build assets, you see the following output: 

```
found 7 vulnerabilities (2 moderate, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

Should be fixed so we dont' see any audit output

### yup dependency vulnerability
https://github.com/inveniosoftware/invenio-app-rdm/pull/975

### axios vulnerability
https://github.com/inveniosoftware/invenio-search-ui/pull/122
https://github.com/inveniosoftware/react-invenio-forms/pull/86

### admin-lte vulnerability
https://github.com/inveniosoftware/invenio-theme/pull/246

### node-sass vulnerability
https://github.com/inveniosoftware/invenio-assets/pull/140

## Note
A moderate vulnerability is remaining but npm audit recommends a move to webpack 5.45 to address it and we are using webpack 4. So I think we should wait for it. It's not that bad since it's a dev dependency vulnerability anyway.

Everything was still working with those changes, but I wouldn't be surprised if I missed some parts that are now not quite behaving the same. Manual testing will be valuable to uncover those.

**Comment by fenekku** [comment]
Interesting related read: https://overreacted.io/npm-audit-broken-by-design/

**Comment by fenekku** [comment]
Running `invenio-cli assets build` I am getting 

```
found 6 vulnerabilities (2 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by fenekku** [comment]
### node-sass vulnerability
https://github.com/inveniosoftware/invenio-assets/pull/140
