### ISSUE TITLE
deposit form: inconsistent marking of required fields

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#966]
Notice the small red dots for marking a field required. It's used inconsistently 

![Screenshot 2021-07-16 at 07 24 53](https://user-images.githubusercontent.com/1698163/125896165-98dcc1ef-3005-4847-ab27-36b8271bd912.png)

![Screenshot 2021-07-16 at 07 25 06](https://user-images.githubusercontent.com/1698163/125896176-58347d26-5208-45ba-93b7-b0374c347e66.png)

![Screenshot 2021-07-16 at 07 25 22](https://user-images.githubusercontent.com/1698163/125896205-79c991cf-d563-4f44-a672-7870326a1363.png)

![Screenshot 2021-07-16 at 07 25 44](https://user-images.githubusercontent.com/1698163/125896237-e8e1c18c-c866-4dff-aad2-ab8e9c1ba694.png)

**Comment by fenekku** [comment]
The correct consistent approach should be: 
- If top-level field is required, then have the red star on it.
- If subfield is required (whether subfield of required field or optional field), then have the red star on it.

But then there is a lot of red stars and they may be mistaken for required fields when in fact they are part of an optional field. We can try that and see how users react... 

Should Additional Title and Additional Description both have similar boldness? i.e. both bold or both not.
