### ISSUE TITLE
datacite xml: affiliations missing

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#967]
![Screenshot 2021-07-16 at 07 28 53](https://user-images.githubusercontent.com/1698163/125896516-63f13f62-64c6-4227-883d-0c1080a38d0d.png)

**Comment by lnielsen** [comment]
The affiliation is there now, but the ROR identifier is missing.

![Screenshot 2021-07-16 at 15 21 13](https://user-images.githubusercontent.com/1698163/125954632-e785da99-3acc-4ac5-b27d-dcd7b3b6b4d9.png)
![Screenshot 2021-07-16 at 15 21 31](https://user-images.githubusercontent.com/1698163/125954674-8ec3eb43-4877-4b3f-b62c-1a9bfb3af75a.png)

Internal metadata:

![Screenshot 2021-07-16 at 15 21 40](https://user-images.githubusercontent.com/1698163/125954703-17766373-14d5-4e80-9c98-b4e17d77f274.png)

**Comment by ppanero** [comment]
This is pretty weird, as you see it did not happen on the tests... The ROR was there... Checking

**Comment by ppanero** [comment]
What is being added as fixture in rdm-records:
```
{'revision_id': 1, 'updated': '2021-07-16T14:21:22.365850+00:00', 'id': 'cern', 'acronym': 'CERN', 'identifiers': [{'scheme': 'ror', 'identifier': '01ggx4157'}, {'scheme': 'isni', 'identifier': '000000012156142X'}], 'name': 'CERN', 'created': '2021-07-16T14:21:22.347597+00:00', 'links': {}}
```

What is being indexed by the fixtures loading in app-rdm:

```
{'links': {}, 'acronym': 'CERN', 'name': 'European Organization for Nuclear Research', 'created': '2021-07-16T12:04:19.527824+00:00', 'title': {'de': '\xa0Europäische Organisation für Kernforschung', 'en': 'European Organization for Nuclear Research', 'fr': 'Organisation européenne pour la recherche nucléaire'}, 'id': '01ggx4157', 'updated': '2021-07-16T12:04:19.541135+00:00', 'revision_id': 1}
```

Options:
1. Rely on the `id`, but then we loose schema
2. Edit affiliation loading (the yaml file basically) and add the `identifiers` field

Implementing 2) but will keep id to the main identifier (ror in this case)
