### ISSUE TITLE
verify links of docs

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#97]
in the frontpage.html there was a reference to `configuration` of the docs. Since now they are migrated into `Make it your own` this link should be changed.

**Step 1**
"configuration section in the docs" should point to https://inveniordm.docs.cern.ch/develop/make_it_your_own/#define-a-custom-controlled-vocabulary

**Step 2**
"here" should point to https://inveniordm.docs.cern.ch/develop/make_it_your_own/#change-the-logo or  https://inveniordm.docs.cern.ch/develop/make_it_your_own/ directly.

The steps order should parallel the order on the docs page, but they are not right now. Customzation should be step 1 on the frontpage or configuration sections should be at the top in the Make it your own document.

**Comment by alexsdutton** [comment]
I can pick this one up :-)

**Comment by ppanero** [comment]
@fenekku @alexsdutton Do you thinkg this still applies? The maybe the solution is to have a separate `configure` and `customize` section. But pointing to specific points can be prone to error since sections are more prone to change.

**Comment by fenekku** [comment]
Taking a step back, the fact that a developer configures their instance in order to customize it is what blurs the line between those steps anyway. Perhaps 2 steps:

1- Make it your own (with a link to the documentation's first section showing how to modify your instance)
2- Deploy (with a link to the deploy documentation)

is cleaner?

**Comment by ppanero** [comment]
Yes, that could be. I think somehow it was intended to differentiate config from templating. I sort of see it growing a lot for just one section (`make it your own`) So maybe is good to split. But for the future. Now maybe we can leave it as is and see where it goes?

**Comment by lnielsen** [comment]
The frontpage needs a full review, and the docs need a bit of refactor so closing.
